# -*- coding: utf-8 -*-
"""
Bai viet cum C (hop dong & boi thuong) va cum D (suc khoe & bao ve thu nhap).
Song song voi benhvien.py, dung chung bo render trong build.py.

NGUYEN TAC BIEN TAP - doc truoc khi sua file nay:
  1. Moi con so PHAI co nguon va ngay. Khong co nguon -> khong dang.
  2. KHONG SO SANH AIA VOI CAC HANG KHAC. Khong nêu ten hang de xep hang,
     cham diem, hay noi hang nao tot hon. Lien la dai ly AIA.
     Duoc phep: trich nguyen van danh sach doi tac bao lanh vien phi do BENH VIEN
     cong bo (do la dữ kiện cua benh vien, khong phai danh gia cua minh).
  3. Dan luat thi dan dung so dieu, so van ban, ngay ban hanh.
  4. Truong "kiem_chung" cua moi bang: "chinh-thuc" | "thu-cap" | "chua-xac-minh"

CUM:
  "C" -> hop dong & boi thuong   -> tru cot /san-pham.html
  "D" -> suc khoe & benh nang    -> tru cot /suc-khoe.html
  "E" -> bao ve thu nhap         -> tru cot /bao-ve-thu-nhap.html

MOI ENTRY:
{
 "slug": "bay-ly-do-tu-choi-boi-thuong",   # -> /kien-thuc/<slug>.html
 "cum": "C",
 "ngay_dang": "2026-09-04",
 "tag": "Bồi thường",              # nhan ngan hien tren the bai viet
 "doc": "7 phút đọc",
 "title": "...",                   # the <title>, co the dai
 "h1": "...",                      # tieu de tren trang, ngan hon title
 "desc": "...",                    # meta description
 "tom_tat": "...",                 # doan mo dau, HTML cho phep
 "canh_bao": "",                   # tuy chon, hien trong callout warn
 "bang": [ {"ten":..., "kiem_chung":..., "nguon":..., "cot":[...], "hang":[[...]]} ],
 "y_chinh": [ ("Tiêu đề", "Nội dung") ],   # cac muc noi dung chinh
 "khong_ro": [ "..." ],            # nhung gi chua co du lieu chac chan - tuy chon
 "faq": [ ("Hỏi", "Đáp") ],
 "lien_quan": ["slug-khac"],       # tuy chon, link noi bo them
}
"""

BAI_VIET = [

# =====================================================================
{
 "slug": "chi-phi-dieu-tri-ung-thu",
 "cum": "D",
 "ngay_dang": "2026-09-04",
 "tag": "Chi phí thật",
 "doc": "9 phút đọc",
 "title": "Điều trị ung thư ở Việt Nam tốn bao nhiêu: vì sao không ai trả lời được, và con số đã đo được",
 "h1": "Chi phí điều trị ung thư ở Việt Nam",
 "desc": "Từ 01/01/2025 không còn bảng giá viện phí chung toàn quốc, mỗi bệnh viện tự định giá. Nhưng nghiên cứu bình duyệt đã đo được phần gia đình tự trả và tỷ lệ hộ kiệt quệ tài chính.",
 "tom_tat": "Có một nghiên cứu bình duyệt theo dõi 1.141 bệnh nhân ung thư suốt 12 tháng ở Bạch Mai, Bệnh viện K và Bệnh viện Ung Bướu TP.HCM. Tiền túi mỗi gia đình bỏ ra trung bình 43,8 triệu đồng một năm, <b>82,6%</b> hộ rơi vào chi phí thảm hoạ. Dữ liệu thu thập giai đoạn 2011&ndash;2013, nên con số tuyệt đối đã cũ, phần còn dùng được là tỷ lệ. Còn câu hỏi một ca hoá trị hết bao nhiêu thì hiện không ai trả lời chung được, vì từ 01/01/2025 mỗi bệnh viện tự định giá.",
 "canh_bao": "Bài này không có bảng giá hoá trị, xạ trị hay phẫu thuật, vì không tồn tại một bảng giá chung hiện hành để dẫn. Thông tư 22/2023/TT-BYT từng quy định giá dịch vụ khám chữa bệnh BHYT toàn quốc đã <b>hết hiệu lực ngày 31/12/2024</b>. Từ 01/01/2025, mỗi bệnh viện tự xây giá theo phương pháp tại Thông tư 21/2024/TT-BYT. Chúng tôi đăng phần đo được và nói rõ phần không có.",

 "bang": [
   {"ten": "Gánh nặng tài chính, đo trên 1.141 bệnh nhân trong 12 tháng",
    "kiem_chung": "chinh-thuc",
    "nguon": "Hoang Van Minh và cộng sự, 2017, <i>BioMed Research International</i>, DOI 10.1155/2017/9350147. Nghiên cứu theo dõi dọc tại Bệnh viện Bạch Mai, Bệnh viện K và Bệnh viện Ung Bướu TP.HCM. Dữ liệu thu thập giai đoạn 2011&ndash;2013.",
    "cot": ["Chỉ số", "Kết quả"],
    "hang": [
      ["Chi tiền túi trung bình trong 12 tháng", "<b>43,8 triệu đồng</b>"],
      ["Chi tiền túi trung vị", "33,4 triệu đồng"],
      ["Hộ rơi vào chi phí thảm hoạ (ngưỡng 20% thu nhập hộ)", "<b>82,6%</b>"],
      ["Hộ rơi vào chi phí thảm hoạ (ngưỡng 50% thu nhập hộ)", "56,9%"],
      ["Hộ bị đẩy xuống dưới chuẩn nghèo", "<b>37,4%</b>"],
    ]},
   {"ten": "Giá ngày giường và khám bệnh theo khung BHYT cũ",
    "kiem_chung": "chinh-thuc",
    "nguon": "Thông tư 22/2023/TT-BYT, Bộ Y tế, ban hành 17/11/2023. <b>Đã hết hiệu lực ngày 31/12/2024.</b> Đăng ở đây làm mốc tham chiếu, không phải giá hiện hành.",
    "cot": ["Dịch vụ", "Mức BHYT theo khung cũ"],
    "hang": [
      ["Khám bệnh, bệnh viện hạng đặc biệt và hạng I", "42.100đ"],
      ["Khám bệnh, hạng II", "37.500đ"],
      ["Khám bệnh, hạng III / hạng IV", "33.200đ / 30.100đ"],
      ["Ngày giường hồi sức tích cực, hạng đặc biệt và hạng I", "<b>867.500đ/ngày</b>"],
      ["Ngày giường hồi sức tích cực, hạng II", "786.300đ/ngày"],
      ["Ngày giường hồi sức tích cực, hạng III", "673.900đ/ngày"],
      ["Ngày giường hồi sức cấp cứu", "279.400 &ndash; 509.400đ/ngày"],
      ["Ngày giường nội trú loại 1", "176.900 &ndash; 273.100đ/ngày"],
    ]},
   {"ten": "Cách tính ngày giường theo khung cũ, chỗ dễ hiểu nhầm nhất khi quyết toán",
    "kiem_chung": "chinh-thuc",
    "nguon": "Thông tư 22/2023/TT-BYT, phần quy định chung về thanh toán ngày giường. <b>Đã hết hiệu lực ngày 31/12/2024.</b> Cách tính này chỉ còn là mốc tham chiếu, phải hỏi lại quy định hiện hành của bệnh viện.",
    "cot": ["Tình huống", "Cách tính"],
    "hang": [
      ["Số ngày giường", "ngày ra viện trừ ngày vào viện, <b>cộng thêm 1</b>"],
      ["Nằm ghép 2 người một giường", "thanh toán <b>50%</b> giá ngày giường"],
      ["Nằm ghép từ 3 người trở lên", "thanh toán <b>33%</b>"],
      ["Khám chuyên khoa thứ hai trở đi trong cùng ngày", "tính <b>30%</b> giá khám, tối đa 2 lần"],
    ]},
   {"ten": "Số liệu khu vực Đông Nam Á &mdash; không tách riêng được Việt Nam",
    "kiem_chung": "thu-cap",
    "nguon": "ACTION Study Group, 2015, <i>BMC Medicine</i>, DOI 10.1186/s12916-015-0433-1. Nghiên cứu 8 nước Đông Nam Á, 9.513 bệnh nhân. Bài gốc không bóc tách riêng số của Việt Nam, nên đây là số toàn vùng.",
    "cot": ["Sau 12 tháng kể từ chẩn đoán", "Tỷ lệ toàn vùng"],
    "hang": [
      ["Tử vong", "29%"],
      ["Người còn sống rơi vào chi phí thảm hoạ", "48%"],
      ["Hoặc tử vong, hoặc kiệt quệ tài chính", "<b>hơn 75%</b>"],
      ["Định nghĩa chi phí thảm hoạ dùng trong nghiên cứu", "chi tiền túi y tế vượt 30% thu nhập hộ trong năm"],
    ]},
 ],

 "y_chinh": [
   ("Vì sao không có bảng giá điều trị ung thư toàn quốc",
    "Trước đây Thông tư 22/2023/TT-BYT quy định một khung giá dịch vụ khám chữa bệnh BHYT áp chung. Thông tư đó hết hiệu lực ngày 31/12/2024. Từ 01/01/2025, mỗi bệnh viện tự xây giá dịch vụ của mình theo phương pháp định giá tại Thông tư 21/2024/TT-BYT. Nghĩa là giá một ca xạ trị ở Bệnh viện K và ở Bệnh viện Ung Bướu TP.HCM có thể khác nhau, và cả hai đều đúng luật. Ai đưa cho bạn một con số &ldquo;giá xạ trị ở Việt Nam năm 2026&rdquo; mà không nói bệnh viện nào thì con số đó không có nghĩa."),
   ("Con số 43,8 triệu là tiền túi, không phải tổng viện phí",
    "Đây là phần gia đình tự bỏ ra sau khi bảo hiểm y tế đã chi trả, cộng cả chi phí y tế lẫn chi phí phi y tế như đi lại, ăn ở của người nhà, thu nhập mất đi. Tổng viện phí lớn hơn con số này. Nhưng với người lập ngân sách, phần tiền túi mới là phần phải lo."),
   ("Vì sao 82,6% là con số cần chú ý hơn 43,8 triệu",
    "Chi phí thảm hoạ là khoản chi y tế vượt quá một tỷ lệ nhất định trong thu nhập hộ gia đình, ở đây lấy mốc 20%. Tỷ lệ 82,6% có nghĩa là với phần lớn hộ có người mắc ung thư, khoản chi này nằm ngoài khả năng chi trả thông thường. Trung bình 43,8 triệu nghe còn xoay được. Nhưng 37,4% hộ bị đẩy xuống dưới chuẩn nghèo thì cho thấy đa số không xoay nổi."),
   ("Dữ liệu đã cũ, và điều đó cần nói ra",
    "Nghiên cứu công bố năm 2017 nhưng dữ liệu thu thập giai đoạn 2011 đến 2013. Từ đó tới nay chi phí y tế đã tăng, phác đồ điều trị đã đổi, danh mục thuốc BHYT đã mở rộng. Con số tuyệt đối 43,8 triệu chắc chắn không còn đúng cho năm 2026. Cái còn giá trị là tỷ lệ và cấu trúc: phần lớn hộ gia đình rơi vào chi phí thảm hoạ, và hơn một phần ba bị đẩy xuống dưới chuẩn nghèo."),
   ("Thuốc đích và thuốc miễn dịch là khoản chúng tôi chưa xác minh được",
    "Đây thường là khoản đắt nhất trong điều trị ung thư hiện đại, và cũng là khoản hay bị hiểu nhầm nhất. Cơ chế thì rõ: danh mục thuốc BHYT có cột tỷ lệ thanh toán, tức có thuốc BHYT trả 100%, có thuốc chỉ trả một phần. Nhưng từng hoạt chất cụ thể được trả bao nhiêu thì nằm trong phụ lục danh mục thuốc, và chúng tôi chưa đọc được bản đầy đủ. Vì vậy bài này không đưa con số nào cho nhóm thuốc đó."),
   ("Điều nên hỏi bệnh viện trước khi bắt đầu phác đồ",
    "Một: phác đồ dự kiến gồm bao nhiêu chu kỳ, mỗi chu kỳ chi phí ước tính bao nhiêu tại chính bệnh viện này. Hai: thuốc trong phác đồ có nằm trong danh mục BHYT không, tỷ lệ thanh toán bao nhiêu phần trăm. Ba: nếu phải nằm hồi sức tích cực thì giá ngày giường ở đây là bao nhiêu. Ba câu này quyết định phần lớn ngân sách, và chỉ bệnh viện điều trị mới trả lời được."),
 ],

 "khong_ro": [
   "Giá hoá trị, xạ trị và phẫu thuật khối u. Các mã này nằm ở phụ lục của thông tư và ở bảng giá riêng từng bệnh viện. Bản HTML của thông tư không hiển thị phụ lục. Website Bệnh viện K chặn ở tầng chứng chỉ nên không mở được; bốn file bảng giá của Bệnh viện Ung Bướu TP.HCM đặt trên Google Drive và bị chặn tải.",
   "Tỷ lệ BHYT chi trả cho từng thuốc đích và thuốc miễn dịch. Chúng tôi xác nhận được cơ chế tỷ lệ thanh toán tồn tại trong quy định, nhưng chưa đọc được phụ lục danh mục để biết từng hoạt chất được trả bao nhiêu.",
   "Giá dịch vụ ung bướu hiện hành của từng bệnh viện sau ngày 01/01/2025. Mỗi bệnh viện tự công bố, chúng tôi chưa mở được bảng nào.",
   "Số liệu Việt Nam tách riêng trong nghiên cứu ACTION 2015. Bài gốc chỉ báo cáo số toàn vùng tám nước.",
   "Chi phí điều trị theo từng loại ung thư và từng giai đoạn. Nghiên cứu 2017 báo cáo số gộp, không tách theo bệnh.",
 ],

 "faq": [
   ("Điều trị ung thư ở Việt Nam hết bao nhiêu tiền?",
    "Không có con số chung. Từ 01/01/2025 mỗi bệnh viện tự định giá dịch vụ theo Thông tư 21/2024/TT-BYT, nên không tồn tại bảng giá toàn quốc. Cái đo được là phần tiền túi gia đình bỏ ra: trung bình 43,8 triệu đồng trong 12 tháng, theo nghiên cứu trên 1.141 bệnh nhân tại Bạch Mai, Bệnh viện K và Bệnh viện Ung Bướu TP.HCM. Dữ liệu thu thập giai đoạn 2011 đến 2013 nên con số tuyệt đối này không còn đúng cho năm 2026, chỉ dùng để thấy quy mô."),
   ("Bảo hiểm y tế chi trả bao nhiêu khi điều trị ung thư?",
    "Tuỳ dịch vụ và tuỳ thuốc. Với dịch vụ kỹ thuật, BHYT thanh toán theo mức hưởng của thẻ và theo giá bệnh viện công bố. Với thuốc, danh mục BHYT có cột tỷ lệ thanh toán, có thuốc trả đủ, có thuốc chỉ trả một phần. Chúng tôi chưa đọc được phụ lục danh mục nên không đưa tỷ lệ cụ thể cho từng thuốc."),
   ("Chi phí thảm hoạ nghĩa là gì?",
    "Là khoản chi y tế tiền túi vượt quá một tỷ lệ nhất định trong thu nhập hộ gia đình trong năm. Nghiên cứu năm 2017 dùng hai ngưỡng 20% và 50%, cho kết quả 82,6% và 56,9%. Nghiên cứu ACTION dùng ngưỡng 30% thu nhập năm."),
   ("Ngày giường hồi sức tích cực bao nhiêu một ngày?",
    "Theo khung BHYT cũ tại Thông tư 22/2023/TT-BYT: 867.500đ mỗi ngày ở bệnh viện hạng đặc biệt và hạng I, 786.300đ ở hạng II, 673.900đ ở hạng III. Khung này đã hết hiệu lực từ 31/12/2024, nên chỉ dùng làm mốc tham chiếu, phải hỏi lại giá hiện hành của bệnh viện."),
   ("Vì sao bài này ít con số hơn các trang khác?",
    "Vì phần lớn con số đang lan truyền không dẫn được nguồn hiện hành. Khung giá chung đã hết hiệu lực gần hai năm, mà nhiều bài vẫn đăng lại như giá 2026. Chúng tôi đăng đúng phần kiểm chứng được và ghi rõ phần chưa đọc được."),
 ],
},

# =====================================================================
{
 "slug": "ly-do-ho-so-bi-tu-choi-boi-thuong",
 "cum": "C",
 "ngay_dang": "2026-09-04",
 "tag": "Bồi thường",
 "doc": "10 phút đọc",
 "title": "Hồ sơ bảo hiểm bị từ chối bồi thường: mười ba lý do, và điều luật tương ứng cho từng lý do",
 "h1": "Vì sao hồ sơ bị từ chối bồi thường",
 "desc": "Mỗi lý do từ chối đều gắn với một điều trong Luật Kinh doanh bảo hiểm 2022. Biết điều luật nào áp cho trường hợp của mình là bước đầu tiên để biết mình có cãi được không.",
 "tom_tat": "Doanh nghiệp bảo hiểm không được từ chối tuỳ ý. Mỗi lý do từ chối hợp lệ đều phải dựa vào một điều cụ thể trong <b>Luật Kinh doanh bảo hiểm số 08/2022/QH15</b>, hiệu lực từ 01/01/2023. Bài này liệt kê mười ba lý do thường gặp, kèm điều luật và trích nguyên văn. Vài trường hợp trong đó, luật đứng về phía người mua rõ hơn nhiều người vẫn nghĩ.",

 "bang": [
   {"ten": "Mười ba lý do từ chối và điều luật tương ứng",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Kinh doanh bảo hiểm số 08/2022/QH15, Quốc hội thông qua 16/06/2022, hiệu lực 01/01/2023. Trích rút gọn, giữ nguyên từ ngữ của luật.",
    "cot": ["Tình huống", "Điều luật", "Nội dung luật"],
    "hang": [
      ["Khai không trung thực khi ký hợp đồng", "Điều 22 khoản 2",
       "Áp dụng khi bên mua <b>cố ý</b> cung cấp thông tin sai <b>nhằm giao kết hợp đồng để được bồi thường</b>. Doanh nghiệp có quyền huỷ hợp đồng và phải hoàn lại phí sau khi trừ chi phí hợp lý."],
      ["Rơi vào điều khoản loại trừ", "Điều 20 khoản 1 điểm d",
       "Được từ chối nếu không thuộc phạm vi trách nhiệm bảo hiểm hoặc thuộc trường hợp loại trừ <b>theo thoả thuận trong hợp đồng</b>."],
      ["Hãng chưa từng giải thích điều khoản loại trừ", "Điều 19 khoản 2",
       "Doanh nghiệp phải giải thích rõ ràng, đầy đủ và <b>có bằng chứng xác nhận</b> bên mua đã được giải thích và hiểu rõ khi giao kết."],
      ["Lấy lý do bạn báo chậm", "Điều 19 khoản 3",
       "Nếu có bất khả kháng hoặc trở ngại khách quan thì <b>không được áp dụng</b> điều khoản loại trừ về việc chậm thông báo."],
      ["Điều khoản mập mờ, hai bên hiểu khác nhau", "Điều 24",
       "Điều khoản không rõ ràng dẫn đến cách hiểu khác nhau thì được giải thích <b>theo hướng có lợi cho bên mua bảo hiểm</b>."],
      ["Hợp đồng bị tuyên vô hiệu", "Điều 25 khoản 1",
       "Có 11 trường hợp, trong đó có: không có quyền lợi có thể được bảo hiểm; bên mua <b>biết sự kiện bảo hiểm đã xảy ra</b>; giả tạo; lừa dối; đe doạ, cưỡng ép. Hậu quả là hai bên hoàn trả cho nhau những gì đã nhận."],
      ["Hãng đơn phương chấm dứt hợp đồng", "Điều 26",
       "Danh sách <b>đóng</b>, chỉ 4 trường hợp: không đóng đủ phí sau thời gian gia hạn; không chấp nhận thay đổi mức độ rủi ro; không bảo đảm an toàn; không đồng ý chuyển giao danh mục."],
      ["Nợ phí nhưng sự kiện đã xảy ra trước khi chấm dứt", "Điều 27 khoản 1 điểm b",
       "Doanh nghiệp <b>vẫn có trách nhiệm trả tiền bảo hiểm</b> nếu sự kiện xảy ra trước thời điểm đơn phương chấm dứt, và được khấu trừ phí còn thiếu."],
      ["Nộp hồ sơ quá hạn", "Điều 30 khoản 1 và 2",
       "Thời hạn nộp yêu cầu bồi thường là <b>01 năm</b> kể từ ngày xảy ra sự kiện. Thời gian bất khả kháng hoặc trở ngại khách quan không tính vào. Khoản 2 tính từ ngày bên mua <b>biết</b> sự kiện."],
      ["Hãng kéo dài, không trả lời", "Điều 31",
       "Không có thoả thuận khác thì phải trả trong <b>15 ngày</b> kể từ ngày nhận đủ hồ sơ hợp lệ. Chậm thì <b>phải trả lãi</b> trên số tiền chậm trả."],
      ["Từ chối miệng, không nêu lý do", "Điều 20 khoản 2 điểm e",
       "Doanh nghiệp có nghĩa vụ <b>giải thích bằng văn bản</b> lý do từ chối bồi thường."],
      ["Đổ lỗi cho nhà tái bảo hiểm", "Điều 29 khoản 1",
       "Doanh nghiệp chịu trách nhiệm <b>duy nhất</b> với bên mua, <b>không được từ chối hoặc trì hoãn</b> kể cả khi bên nhận tái bảo hiểm không thực hiện nghĩa vụ."],
      ["Muốn rút trong thời gian cân nhắc", "Điều 35",
       "Với hợp đồng thời hạn <b>trên 01 năm</b>, trong <b>21 ngày kể từ ngày nhận được hợp đồng</b>, bên mua có quyền từ chối tiếp tục tham gia."],
    ]},
   {"ten": "Hai mốc thời gian rất hay bị lẫn",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Kinh doanh bảo hiểm 2022 và Bộ luật Dân sự 2015",
    "cot": ["Việc cần làm", "Thời hạn", "Căn cứ"],
    "hang": [
      ["Nộp hồ sơ yêu cầu bồi thường cho doanh nghiệp bảo hiểm", "<b>01 năm</b> kể từ ngày xảy ra sự kiện", "Điều 30 Luật Kinh doanh bảo hiểm 2022"],
      ["Khởi kiện ra toà về hợp đồng bảo hiểm", "<b>03 năm</b>", "Điều 429 Bộ luật Dân sự 2015"],
      ["Doanh nghiệp phải trả tiền sau khi nhận đủ hồ sơ", "15 ngày", "Điều 31 Luật Kinh doanh bảo hiểm 2022"],
      ["Từ chối tiếp tục tham gia hợp đồng trên 1 năm", "21 ngày từ ngày nhận hợp đồng", "Điều 35 Luật Kinh doanh bảo hiểm 2022"],
    ]},
 ],

 "y_chinh": [
   ("Chữ quan trọng nhất trong Điều 22 là chữ &ldquo;cố ý&rdquo;",
    "Điều 22 khoản 2 chỉ cho phép huỷ hợp đồng khi bên mua <b>cố ý</b> cung cấp thông tin sai <b>nhằm mục đích được bồi thường</b>. Quên một lần khám cách đây nhiều năm, hoặc không biết mình có bệnh, về mặt câu chữ không phải là cố ý nhằm trục lợi. Ranh giới này là chỗ tranh chấp nhiều nhất trong thực tế, và cũng là lý do hồ sơ bệnh án cũ quan trọng đến thế."),
   ("Nghĩa vụ chứng minh đã giải thích thuộc về doanh nghiệp",
    "Điều 19 khoản 2 không chỉ yêu cầu doanh nghiệp giải thích, mà yêu cầu <b>có bằng chứng xác nhận</b> bên mua đã hiểu rõ điều khoản loại trừ. Nếu bạn bị từ chối vì một điều khoản loại trừ mà chưa từng được giải thích, câu hỏi ngược lại là bằng chứng đó đâu."),
   ("Điều 24 là điều nhiều người không biết mình có",
    "Khi một điều khoản có thể hiểu theo hai cách, luật buộc phải hiểu theo hướng có lợi cho bên mua. Đây không phải thiện chí của doanh nghiệp mà là quy định. Trong tranh chấp về từ ngữ hợp đồng, đây thường là căn cứ mạnh nhất của người mua."),
   ("Danh sách được đơn phương chấm dứt là danh sách đóng",
    "Điều 26 liệt kê đúng bốn trường hợp. Ngoài bốn trường hợp đó, doanh nghiệp không có quyền đơn phương chấm dứt hợp đồng. Nếu nhận được thông báo chấm dứt, việc đầu tiên nên làm là đối chiếu lý do trong thông báo với bốn trường hợp này."),
   ("Nợ phí không xoá trách nhiệm với sự kiện đã xảy ra trước đó",
    "Điều 27 khoản 1 điểm b nói rõ: sự kiện bảo hiểm xảy ra trước thời điểm đơn phương chấm dứt thì doanh nghiệp vẫn phải trả tiền, và chỉ được khấu trừ phần phí còn thiếu. Đây là tình huống hay bị hiểu ngược."),
   ("Từ chối phải bằng văn bản, và phải nêu lý do",
    "Điều 20 khoản 2 điểm e đặt đây là nghĩa vụ của doanh nghiệp. Một cuộc gọi báo &ldquo;hồ sơ không được duyệt&rdquo; không phải là từ chối hợp lệ. Hãy yêu cầu văn bản, vì văn bản đó là thứ bạn cần khi khiếu nại hoặc khởi kiện."),
   ("Đừng lẫn một năm với ba năm",
    "Một năm là thời hạn nộp hồ sơ cho doanh nghiệp bảo hiểm, theo Điều 30. Ba năm là thời hiệu khởi kiện ra toà, theo Điều 429 Bộ luật Dân sự 2015. Luật Kinh doanh bảo hiểm 2022 không có điều riêng về thời hiệu khởi kiện, nên nhiều bài viết dẫn nhầm sang điều của luật cũ năm 2000 đã hết hiệu lực."),
 ],

 "khong_ro": [
   "Thế nào là hồ sơ hợp lệ. Mốc 15 ngày ở Điều 31 tính từ ngày nhận đủ hồ sơ hợp lệ, nhưng luật không định nghĩa hợp lệ gồm những gì.",
   "Số lần và thời hạn yêu cầu bổ sung hồ sơ. Luật không giới hạn, nên việc yêu cầu bổ sung nhiều lần có thể kéo dài mà vẫn đúng luật.",
   "Thời hạn tối đa cho việc thẩm định và xác minh hồ sơ.",
   "Nội dung tối thiểu của văn bản từ chối. Luật buộc phải giải thích bằng văn bản nhưng không quy định văn bản đó phải dẫn điều khoản nào và phải gửi trong bao lâu.",
   "Mức trần của &ldquo;chi phí hợp lý&rdquo; được trừ khi hoàn phí, ở Điều 22 và Điều 35. Luật để hợp đồng tự thoả thuận.",
   "Mức lãi suất chậm trả ở Điều 31 khoản 2. Luật chỉ dẫn sang Bộ luật Dân sự, không ấn định con số.",
   "Loại bằng chứng nào được chấp nhận để chứng minh khách hàng đã hiểu điều khoản loại trừ.",
   "Không có cơ quan tài phán chuyên trách cho tranh chấp bảo hiểm, cũng không có thủ tục khiếu nại bắt buộc trước khi khởi kiện.",
   "Số liệu về tỷ lệ từ chối bồi thường trên thị trường. Chúng tôi không tìm thấy thống kê công khai chính thức nào. Vì vậy bài này không đưa ra bất kỳ con số phần trăm nào về chuyện đó.",
 ],

 "faq": [
   ("Bị từ chối bồi thường thì làm gì đầu tiên?",
    "Yêu cầu văn bản nêu rõ lý do từ chối. Điều 20 khoản 2 điểm e của Luật Kinh doanh bảo hiểm 2022 quy định doanh nghiệp phải giải thích bằng văn bản. Có văn bản rồi mới đối chiếu được lý do đó với điều khoản trong hợp đồng và với luật."),
   ("Khai thiếu bệnh cũ thì chắc chắn mất quyền lợi?",
    "Không chắc chắn. Điều 22 khoản 2 chỉ áp dụng khi bên mua cố ý cung cấp thông tin sai nhằm mục đích được bồi thường. Quên hoặc không biết là tình huống khác về mặt câu chữ của luật, và trên thực tế đây là chỗ tranh chấp nhiều nhất."),
   ("Nộp hồ sơ trễ bao lâu thì mất quyền?",
    "Thời hạn là 01 năm kể từ ngày xảy ra sự kiện bảo hiểm, theo Điều 30. Thời gian xảy ra bất khả kháng hoặc trở ngại khách quan không tính vào thời hạn này. Riêng thời hiệu khởi kiện ra toà là 03 năm, theo Điều 429 Bộ luật Dân sự 2015."),
   ("Hãng bảo chờ tái bảo hiểm duyệt thì sao?",
    "Điều 29 khoản 1 quy định doanh nghiệp bảo hiểm chịu trách nhiệm duy nhất với bên mua và không được từ chối hoặc trì hoãn, kể cả khi bên nhận tái bảo hiểm không thực hiện nghĩa vụ. Quan hệ giữa doanh nghiệp và nhà tái bảo hiểm không phải việc của người mua."),
   ("Hợp đồng đã ký rồi có rút được không?",
    "Với hợp đồng thời hạn trên 01 năm, Điều 35 cho quyền từ chối tiếp tục tham gia trong 21 ngày kể từ ngày nhận được hợp đồng. Doanh nghiệp hoàn lại phí sau khi trừ chi phí hợp lý. Lưu ý mốc 21 ngày tính từ ngày nhận hợp đồng, không phải ngày ký đơn yêu cầu."),
   ("Bài này có nói hãng nào hay từ chối hơn hãng nào không?",
    "Không. Chúng tôi không tìm thấy thống kê công khai chính thức về tỷ lệ từ chối theo từng doanh nghiệp, nên mọi so sánh kiểu đó đều không có căn cứ. Bài này nói về luật, áp dụng như nhau cho mọi doanh nghiệp bảo hiểm."),
 ],
},

# =====================================================================
{
 "slug": "chi-phi-dieu-tri-dot-quy",
 "cum": "D",
 "ngay_dang": "2026-09-06",
 "tag": "Chi phí thật",
 "doc": "8 phút đọc",
 "title": "Chi phí điều trị đột quỵ ở Việt Nam: số đo được tại từng bệnh viện, và phần chưa ai đo",
 "h1": "Chi phí điều trị đột quỵ ở Việt Nam",
 "desc": "Không có bảng giá điều trị đột quỵ chung toàn quốc từ 01/01/2025. Đây là số thật đo tại Bạch Mai năm 2021 và Thống Nhất Đồng Nai năm 2024, kèm phần chúng tôi chưa tìm được số đáng tin.",
 "tom_tat": "Trung tâm Thần kinh Bệnh viện Bạch Mai có một nghiên cứu trên 500 bệnh nhân nhồi máu não, dữ liệu thu nửa cuối năm 2021. Chi phí trực tiếp một đợt nội trú trung bình <b>10,5 triệu đồng</b>, nhưng dao động từ 3,3 đến 39,8 triệu. Riêng thuốc tiêu sợi huyết, ở nhóm phải dùng, trung bình 17,2 triệu, tức là một mình nó đã đắt hơn cả đợt nằm viện trung bình.",
 "canh_bao": "Bài này không có bảng giá điều trị đột quỵ áp chung toàn quốc, vì từ 01/01/2025 không còn thứ đó. Thông tư 22/2023/TT-BYT từng quy định khung giá dịch vụ khám chữa bệnh BHYT toàn quốc đã hết hiệu lực ngày 31/12/2024; từ 01/01/2025 mỗi bệnh viện tự xây giá theo Thông tư 21/2024/TT-BYT. Số trong bài là số đo tại từng bệnh viện cụ thể, kèm năm thu dữ liệu. Đọc kèm cả hai thông tin đó, đừng tách con số ra khỏi bệnh viện và năm.",

 "bang": [
   {"ten": "Chi phí trực tiếp một đợt nội trú, đo trên 500 bệnh nhân nhồi máu não",
    "kiem_chung": "chinh-thuc",
    "nguon": "Nghiên cứu tại Trung tâm Thần kinh, Bệnh viện Bạch Mai, đăng trên Tạp chí Y học Việt Nam. Dữ liệu thu từ 01/07 đến 31/12/2021, cỡ mẫu 500 bệnh nhân. Đơn vị gốc của nghiên cứu là nghìn đồng, chúng tôi quy về triệu đồng để dễ đọc. Bốn khoản mục dưới đây là các khoản nghiên cứu tách riêng, cộng lại chưa bằng tổng chi phí trực tiếp.",
    "cot": ["Khoản mục", "Trung bình một đợt nội trú"],
    "hang": [
      ["Tổng chi phí trực tiếp", "<b>10,5 triệu đồng</b> (độ lệch chuẩn 7,3 triệu)"],
      ["Khoảng dao động", "3,3 &ndash; 39,8 triệu đồng"],
      ["Tiền giường", "3,64 triệu (lệch chuẩn 2,98 triệu)"],
      ["Thuốc", "2,84 triệu (lệch chuẩn 3,04 triệu)"],
      ["Chẩn đoán hình ảnh", "1,50 triệu (lệch chuẩn 1,22 triệu)"],
      ["Vật tư y tế", "0,118 triệu (lệch chuẩn 0,077 triệu)"],
    ]},
   {"ten": "Thuốc tiêu sợi huyết, khoản đắt nhất khi phải dùng",
    "kiem_chung": "chinh-thuc",
    "nguon": "Cùng nghiên cứu Bạch Mai, dữ liệu 2021. Đây là chi phí riêng của thuốc tiêu sợi huyết ở nhóm bệnh nhân được chỉ định, không phải mọi bệnh nhân đều dùng.",
    "cot": ["Khoản mục", "Trung bình"],
    "hang": [
      ["Thuốc tiêu sợi huyết", "17,2 triệu đồng (độ lệch chuẩn 5,96 triệu)"],
      ["So với tổng một đợt nội trú trung bình", "cao hơn khoảng 6,7 triệu"],
    ]},
   {"ten": "Chi phí ngoại trú và tỷ lệ BHYT chi trả",
    "kiem_chung": "chinh-thuc",
    "nguon": "Nghiên cứu tại Bệnh viện Đa khoa Thống Nhất, Đồng Nai, đăng trên Tạp chí Y học Việt Nam. Dữ liệu năm 2024, cỡ mẫu 1.903 bệnh nhân với 9.051 lượt khám.",
    "cot": ["Chỉ số", "Kết quả"],
    "hang": [
      ["Chi phí y tế trực tiếp mỗi đợt ngoại trú", "470.627đ (khoảng tin cậy 95%: 456.949 &ndash; 484.305đ)"],
      ["Phần BHYT chi trả", "89,5%"],
      ["Phần người bệnh tự trả", "<b>10,5%</b>"],
    ]},
   {"ten": "Quy mô đột quỵ ở Việt Nam",
    "kiem_chung": "thu-cap",
    "nguon": "Phát biểu của Thứ trưởng Bộ Y tế Trần Văn Thuấn tại hội nghị đột quỵ ngày 24/07/2025, VnExpress đưa tin cùng ngày. Đây là số nêu trong phát biểu, không kèm công bố nghiên cứu, nên chúng tôi gắn nhãn thứ cấp.",
    "cot": ["Chỉ số", "Con số nêu trong phát biểu"],
    "hang": [
      ["Tỷ lệ hiện mắc", "1.541 trên 100.000 dân"],
      ["Mới mắc mỗi năm", "khoảng 222 trên 100.000 dân"],
      ["Mất khả năng lao động sau điều trị", "<b>71%</b>"],
      ["Số cơ sở điều trị đột quỵ", "12 cơ sở năm 2016, hơn 150 cơ sở năm 2025"],
    ]},
 ],

 "y_chinh": [
   ("Vì sao không có bảng giá điều trị đột quỵ cho năm 2026",
    "Thông tư 22/2023/TT-BYT từng đặt một khung giá dịch vụ khám chữa bệnh BHYT áp chung cả nước. Thông tư đó hết hiệu lực ngày 31/12/2024. Từ 01/01/2025, mỗi bệnh viện tự xây giá dịch vụ theo phương pháp định giá tại Thông tư 21/2024/TT-BYT. Nghĩa là cùng một ca can thiệp, giá ở Bạch Mai và ở một bệnh viện tỉnh có thể khác nhau, và cả hai đều đúng luật. Trang nào đưa cho bạn một con số giá điều trị đột quỵ ở Việt Nam năm 2026 mà không nói bệnh viện nào thì con số đó không kiểm chứng được."),
   ("Con số 10,5 triệu là chi phí trực tiếp, không phải toàn bộ gánh nặng",
    "Nghiên cứu Bạch Mai với dữ liệu nửa cuối năm 2021 đo chi phí trực tiếp của đợt điều trị nội trú, gồm giường, thuốc, chẩn đoán hình ảnh, vật tư và các khoản khác. Nó không tính tiền đi lại, ăn ở của người nhà, thu nhập mất đi trong thời gian nằm viện, và cũng không tính phục hồi chức năng sau khi ra viện. Vì vậy đừng đọc 10,5 triệu như tổng số tiền một gia đình phải bỏ ra."),
   ("Khoản đắt nhất là thứ bạn không chọn được",
    "Thuốc tiêu sợi huyết trung bình 17,2 triệu theo dữ liệu Bạch Mai năm 2021, đắt hơn cả một đợt nội trú trung bình. Có dùng hay không thì phụ thuộc bệnh nhân tới viện lúc nào và bác sĩ chỉ định thế nào, gia đình không quyết được. Vì vậy chi phí đột quỵ khó dự trù hơn nhiều loại bệnh khác. Hai người cùng chẩn đoán vẫn có thể chênh nhau hơn mười lần, từ 3,3 triệu tới 39,8 triệu, đúng bằng khoảng dao động nghiên cứu ghi nhận."),
   ("Tỷ lệ BHYT chi trả 89,5% là số của ngoại trú, tại một bệnh viện",
    "Con số này lấy từ nghiên cứu ở Bệnh viện Đa khoa Thống Nhất, Đồng Nai, năm 2024, và chỉ đo phần khám chữa ngoại trú. Đừng suy ra rằng nội trú cũng được trả 89,5%, và đừng suy ra rằng bệnh viện khác cũng vậy. Mức hưởng còn phụ thuộc loại thẻ, nơi đăng ký khám ban đầu và dịch vụ cụ thể."),
   ("Phần khiến bảo hiểm trở thành câu chuyện là hậu quả, không phải viện phí",
    "Theo phát biểu tại hội nghị đột quỵ tháng 07/2025, 71% người bệnh mất khả năng lao động sau điều trị. Nếu con số này gần đúng thì chi phí y tế của đợt cấp không phải phần nặng nhất. Phần nặng hơn là thu nhập dừng lại trong khi chi phí chăm sóc kéo dài. Đó là lý do các sản phẩm bảo vệ thu nhập và bệnh hiểm nghèo tồn tại, và cũng là phần chúng tôi không có số liệu Việt Nam để định lượng."),
   ("Ba câu nên hỏi bệnh viện khi người nhà bị đột quỵ",
    "Một: bệnh nhân có nằm trong cửa sổ điều trị để dùng tiêu sợi huyết hoặc can thiệp lấy huyết khối không, và nếu có thì chi phí tại chính bệnh viện này là bao nhiêu. Hai: thẻ BHYT của bệnh nhân được hưởng bao nhiêu phần trăm ở đây, khoản nào ngoài danh mục. Ba: sau giai đoạn cấp thì phục hồi chức năng ở đâu, kéo dài bao lâu, chi phí mỗi đợt bao nhiêu."),
 ],

 "khong_ro": [
   "Chi phí tiền túi của hộ gia đình có người bị đột quỵ. Không tìm được nghiên cứu Việt Nam nào đo riêng khoản này cho đột quỵ. Các nghiên cứu về chi tiêu y tế thảm hoạ ở Việt Nam đều đo y tế nói chung, không tách riêng đột quỵ, nên chúng tôi không mượn số của chúng.",
   "Chi phí phục hồi chức năng dài hạn tại Việt Nam. Có một nghiên cứu quốc tế đưa con số tổng khoảng 3.310 USD, nhưng chúng tôi chưa xác minh được nghiên cứu đó thực hiện tại Việt Nam nên không đăng.",
   "Cửa sổ giờ vàng theo hướng dẫn hiện hành. Nguồn Việt Nam chúng tôi mở được là bài từ năm 2017, nêu mốc 3 đến 6 giờ, đã lệch so với thực hành hiện nay. Chúng tôi không đăng mốc giờ vì đưa sai con số này nguy hiểm hơn là không đưa. Hãy hỏi trực tiếp cơ sở đột quỵ gần nhất.",
   "Tỷ lệ tàn tật sau đột quỵ có cỡ mẫu và phương pháp. Con số 71% đến từ một phát biểu tại hội nghị, không kèm công bố nghiên cứu.",
   "Chi phí điều trị đột quỵ hiện hành của từng bệnh viện sau ngày 01/01/2025. Mỗi bệnh viện tự công bố, chúng tôi chưa mở được bảng nào.",
   "Số liệu phân biệt nhồi máu não và xuất huyết não. Nghiên cứu Bạch Mai chúng tôi dùng chỉ đo nhóm nhồi máu não.",
 ],

 "faq": [
   ("Điều trị đột quỵ ở Việt Nam hết bao nhiêu tiền?",
    "Không có con số chung, vì từ 01/01/2025 mỗi bệnh viện tự định giá dịch vụ theo Thông tư 21/2024/TT-BYT. Số đo được cụ thể: tại Trung tâm Thần kinh Bệnh viện Bạch Mai, chi phí trực tiếp một đợt nội trú của bệnh nhân nhồi máu não trung bình 10,5 triệu đồng, dao động 3,3 đến 39,8 triệu, theo dữ liệu thu nửa cuối năm 2021 trên 500 bệnh nhân."),
   ("Vì sao chi phí đột quỵ chênh nhau tới hơn mười lần?",
    "Vì phụ thuộc bệnh nhân có phải dùng thuốc tiêu sợi huyết hay không, nằm viện bao lâu, và có phải vào hồi sức hay không. Riêng thuốc tiêu sợi huyết đã trung bình 17,2 triệu, cao hơn cả một đợt nội trú trung bình. Đây là số của nghiên cứu Bạch Mai với dữ liệu năm 2021."),
   ("Bảo hiểm y tế chi trả bao nhiêu khi điều trị đột quỵ?",
    "Tuỳ loại thẻ, nơi đăng ký khám ban đầu và dịch vụ cụ thể. Số đo được: tại Bệnh viện Đa khoa Thống Nhất Đồng Nai năm 2024, phần khám chữa ngoại trú được BHYT chi trả 89,5%, người bệnh tự trả 10,5%. Đây là số của riêng bệnh viện đó và riêng phần ngoại trú, không suy ra được cho nội trú hay bệnh viện khác."),
   ("Đột quỵ có để lại di chứng lâu dài không?",
    "Theo phát biểu của Thứ trưởng Bộ Y tế tại hội nghị đột quỵ ngày 24/07/2025, 71% người bệnh mất khả năng lao động sau điều trị. Đây là con số nêu trong phát biểu, không kèm công bố nghiên cứu, nên đọc như một chỉ dấu về quy mô chứ không phải số liệu đã bình duyệt."),
   ("Vì sao bài này không có bảng giá chi tiết như các trang khác?",
    "Vì bảng giá chung toàn quốc đã hết hiệu lực gần hai năm mà nhiều trang vẫn đăng lại như giá hiện hành. Chúng tôi chỉ đăng số đo được tại bệnh viện cụ thể, kèm năm thu dữ liệu, và ghi rõ những chỗ chưa tìm được số đáng tin."),
 ],
 "lien_quan": ["chi-phi-dieu-tri-ung-thu"],
},

# =====================================================================
{
 "slug": "benh-co-san-duoc-hieu-the-nao",
 "cum": "C",
 "ngay_dang": "2026-09-06",
 "tag": "Hợp đồng",
 "doc": "9 phút đọc",
 "title": "Bệnh có sẵn được hiểu thế nào: định nghĩa nằm ở Thông tư 67, không nằm ở Luật",
 "h1": "Bệnh có sẵn được hiểu thế nào",
 "desc": "Luật Kinh doanh bảo hiểm 2022 không có cụm từ bệnh có sẵn. Định nghĩa nằm ở Thông tư 67/2023/TT-BTC Điều 12, kèm bốn mốc thời gian doanh nghiệp không được vượt: 36 tháng, 90 ngày, 1 năm và 270 ngày.",
 "tom_tat": "Nhiều bài trên mạng nói định nghĩa bệnh có sẵn do từng công ty bảo hiểm tự đặt. Chỗ này đúng một nửa. Luật Kinh doanh bảo hiểm số 08/2022/QH15 không có cụm từ này, nhưng Thông tư 67/2023/TT-BTC thì có, ở Điều 12 khoản 3. Doanh nghiệp vẫn tự soạn quy tắc điều khoản, chỉ là phải nằm trong khung đó. Và khung đó đặt bốn mốc cứng: <b>36 tháng</b>, <b>90 ngày</b>, <b>1 năm</b>, <b>270 ngày</b>. Bài này trích nguyên văn điều khoản kèm số điều, số khoản để bạn tự đối chiếu, không thay cho tư vấn pháp lý cho trường hợp cụ thể.",
 "canh_bao": "Bài này trích nguyên văn điều khoản và ghi rõ số điều, số khoản để bạn tự đối chiếu. Chúng tôi không đưa ra tư vấn pháp lý cho trường hợp cụ thể, và không so sánh sản phẩm của các công ty bảo hiểm.",

 "bang": [
   {"ten": "Các mốc thời gian Thông tư 67 đặt ra, doanh nghiệp không được vượt",
    "kiem_chung": "chinh-thuc",
    "nguon": "Thông tư 67/2023/TT-BTC, Điều 12 khoản 2 và khoản 3, Bộ Tài chính. Các mốc dưới đây là mức tối đa, hợp đồng có thể quy định ngắn hơn.",
    "cot": ["Mốc", "Con số", "Nằm ở đâu"],
    "hang": [
      ["Truy ngược dấu hiệu, triệu chứng để coi là bệnh có sẵn", "tối đa <b>36 tháng</b> trước ngày hiệu lực", "Điều 12 khoản 3 điểm a"],
      ["Thời gian chờ với các trường hợp bệnh", "tối đa <b>90 ngày</b>", "Điều 12 khoản 2 điểm c"],
      ["Thời gian chờ khi doanh nghiệp chấp thuận bảo hiểm cho bệnh có sẵn", "tối đa <b>1 năm</b>", "Điều 12 khoản 2 điểm c"],
      ["Thời gian chờ quyền lợi thai sản", "tối đa 270 ngày", "Điều 12 khoản 2 điểm d"],
      ["Thời gian chờ với trường hợp tai nạn", "không được áp dụng", "Điều 12 khoản 2 điểm b"],
    ]},
   {"ten": "Ba yếu tố trong câu chữ Điều 22 khoản 2",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Kinh doanh bảo hiểm số 08/2022/QH15, Điều 22 khoản 2. Ba điều kiện dưới đây là phần bóc tách câu chữ của chính khoản đó.",
    "cot": ["Điều kiện", "Nguyên văn trong luật"],
    "hang": [
      ["Ý chí", "&ldquo;cố ý&rdquo;"],
      ["Hành vi", "&ldquo;cung cấp không đầy đủ thông tin hoặc cung cấp thông tin sai sự thật&rdquo;"],
      ["Mục đích", "&ldquo;nhằm giao kết hợp đồng bảo hiểm để được bồi thường, trả tiền bảo hiểm&rdquo;"],
    ]},
   {"ten": "Bệnh có sẵn trong bảo hiểm thương mại và trong BHYT là hai chuyện khác nhau",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Bảo hiểm y tế, văn bản hợp nhất số 47/VBHN-VPQH năm 2023, các Điều 2, 3 và 23 (danh sách các trường hợp không được hưởng). Luật số 51/2024/QH15 ngày 27/11/2024 có sửa đổi khoản 7 và khoản 8 của Điều 23. Đối chiếu với Thông tư 67/2023/TT-BTC Điều 12.",
    "cot": ["Tiêu chí", "Bảo hiểm thương mại", "Bảo hiểm y tế"],
    "hang": [
      ["Có khái niệm bệnh có sẵn không", "có, tại Thông tư 67 Điều 12 khoản 3", "Điều 23 không liệt kê bệnh có sẵn trong các trường hợp không được hưởng"],
      ["Được từ chối vì tiền sử bệnh không", "có thể, nếu quy tắc điều khoản quy định", "Điều 23 không có trường hợp loại trừ nào theo tiền sử bệnh"],
      ["Cách xác định mức hưởng", "theo hợp đồng", "theo mức độ bệnh tật và thời gian tham gia, không theo tình trạng sức khoẻ khi tham gia"],
      ["Tính chất", "tự nguyện, có lợi nhuận", "bắt buộc, không vì mục đích lợi nhuận"],
    ]},
 ],

 "y_chinh": [
   ("Định nghĩa chính thức, nguyên văn",
    "Thông tư 67/2023/TT-BTC, Điều 12 khoản 3 điểm a: &ldquo;Bệnh có sẵn là tình trạng bệnh tật hoặc thương tật của người được bảo hiểm đã được bác sỹ chẩn đoán hoặc điều trị trước ngày hiệu lực hoặc ngày khôi phục hiệu lực (gần nhất) của hợp đồng bảo hiểm.&rdquo; Điểm đáng chú ý nhất nằm ở chỗ định nghĩa gốc bám vào một hành vi y tế đã xảy ra, tức đã được chẩn đoán hoặc đã điều trị, chứ không bám vào việc trong người đã có mầm bệnh hay chưa."),
   ("Doanh nghiệp được mở rộng định nghĩa, nhưng bị chặn ở mốc 36 tháng",
    "Cũng tại điểm a, thông tư cho phép doanh nghiệp bổ sung các dấu hiệu, triệu chứng đặc thù, nhưng &ldquo;chỉ được xem xét đến các dấu hiệu, triệu chứng khởi phát trong vòng 36 tháng trước ngày hiệu lực hoặc ngày khôi phục hiệu lực (gần nhất) của hợp đồng bảo hiểm&rdquo;. Nghĩa là một triệu chứng xuất hiện cách đây bốn năm, chưa từng được chẩn đoán, thì nằm ngoài khung này."),
   ("Căn cứ để xác định bệnh có sẵn là một danh sách đóng",
    "Điều 12 khoản 3 điểm b liệt kê ba nguồn: hồ sơ y tế lưu tại bệnh viện hoặc cơ sở y tế được thành lập hợp pháp; tài liệu y khoa do Bộ Y tế và cơ quan có thẩm quyền ban hành; và thông tin do chính bên mua hoặc người được bảo hiểm tự kê khai. Đây là lý do hồ sơ bệnh án cũ trở thành thứ quan trọng nhất khi có tranh chấp."),
   ("Chữ quan trọng nhất trong Điều 22 vẫn là chữ cố ý",
    "Luật Kinh doanh bảo hiểm 2022, Điều 22 khoản 2, cho doanh nghiệp quyền huỷ bỏ hợp đồng khi bên mua &ldquo;cố ý cung cấp không đầy đủ thông tin hoặc cung cấp thông tin sai sự thật nhằm giao kết hợp đồng bảo hiểm để được bồi thường, trả tiền bảo hiểm&rdquo;. Ba yếu tố phải cùng có mặt: cố ý, hành vi kê khai sai, và mục đích để được bồi thường. Quên một lần khám nhiều năm trước, hoặc không biết mình có bệnh, về mặt câu chữ không thoả mãn cả ba."),
   ("Luật buộc doanh nghiệp phải chứng minh đã giải thích, không phải ngược lại",
    "Điều 19 khoản 2 quy định khi có điều khoản loại trừ trách nhiệm, doanh nghiệp &ldquo;phải quy định rõ trong hợp đồng bảo hiểm, phải giải thích rõ ràng, đầy đủ và có bằng chứng xác nhận việc bên mua bảo hiểm đã được doanh nghiệp bảo hiểm... giải thích đầy đủ và hiểu rõ nội dung này khi giao kết hợp đồng bảo hiểm&rdquo;. Nghĩa vụ chứng minh nằm ở phía doanh nghiệp."),
   ("Bệnh có sẵn không phải điều luật cấm bảo hiểm",
    "Điều 12 khoản 2 điểm c của Thông tư 67 viết: &ldquo;Đối với trường hợp doanh nghiệp bảo hiểm chấp thuận bảo hiểm cho các bệnh có sẵn, thời gian chờ tối đa là 1 năm.&rdquo; Câu này chỉ tồn tại nếu pháp luật dự liệu việc doanh nghiệp có thể nhận bảo hiểm cho bệnh có sẵn. Nhận hay không là quyền của doanh nghiệp, không phải nghĩa vụ, nhưng việc nhận là hợp pháp và có khung thời gian chờ riêng."),
   ("Không có quy tắc hai năm trong luật Việt Nam",
    "Một số nước có điều khoản gọi là incontestability: qua một số năm thì doanh nghiệp hết quyền huỷ hợp đồng vì kê khai sai. Luật Kinh doanh bảo hiểm 2022 không có quy định đó. Điều 22 khoản 2 không gắn thời hạn nào cho quyền huỷ bỏ này. Con số hai năm hay bị viện dẫn nằm ở Điều 40 khoản 1 điểm a, và điều đó nói về một trường hợp khác hẳn, không liên quan tới kê khai sai. Hai thứ này hay bị nhầm với nhau."),
   ("BHYT không có khái niệm bệnh có sẵn",
    "Điều 2 Luật Bảo hiểm y tế định nghĩa BHYT là hình thức bảo hiểm bắt buộc, không vì mục đích lợi nhuận, do Nhà nước tổ chức thực hiện. Điều 3 nêu nguyên tắc: mức hưởng xác định theo mức độ bệnh tật và thời gian tham gia, không theo tình trạng sức khoẻ lúc tham gia. Điều 23 liệt kê các trường hợp không được hưởng, và trong danh sách đó không có bệnh có sẵn, không có bệnh mắc trước khi tham gia, không có loại trừ nào theo tiền sử. Người đã có bệnh vẫn tham gia và vẫn hưởng BHYT bình thường."),
 ],

 "khong_ro": [
   "Danh mục bệnh nào được coi là bệnh có sẵn. Không có văn bản nhà nước nào liệt kê. Doanh nghiệp tự xác định trong quy tắc điều khoản, trong khung Điều 12 khoản 3 của Thông tư 67.",
   "Mức tăng phí hoặc loại trừ riêng phần khi người mua có bệnh có sẵn. Cả Luật Kinh doanh bảo hiểm 2022 lẫn Thông tư 67/2023/TT-BTC đều không quy định, để hợp đồng tự thoả thuận.",
   "Quy trình khiếu nại riêng cho tranh chấp về bệnh có sẵn. Không có, dùng chung đường khiếu nại và khởi kiện như mọi tranh chấp hợp đồng bảo hiểm.",
   "Tiêu chí y khoa riêng để xác định bệnh có sẵn. Bộ Y tế không ban hành bộ tiêu chí riêng; Thông tư 67 chỉ dẫn chiếu tới tài liệu y khoa nói chung.",
   "Nghị định 46/2023/NĐ-CP có nhắc tới bệnh có sẵn hay không. Chúng tôi chưa đọc hết nghị định này nên không khẳng định.",
 ],

 "faq": [
   ("Luật Việt Nam có định nghĩa bệnh có sẵn không?",
    "Luật Kinh doanh bảo hiểm số 08/2022/QH15 không có cụm từ này. Nhưng Thông tư 67/2023/TT-BTC, Điều 12 khoản 3 điểm a, thì có định nghĩa: bệnh có sẵn là tình trạng bệnh tật hoặc thương tật đã được bác sỹ chẩn đoán hoặc điều trị trước ngày hiệu lực hoặc ngày khôi phục hiệu lực gần nhất của hợp đồng."),
   ("Công ty bảo hiểm có được tự đặt định nghĩa bệnh có sẵn không?",
    "Doanh nghiệp soạn quy tắc điều khoản của mình, nhưng phải nằm trong khung Điều 12 Thông tư 67. Nếu bổ sung dấu hiệu, triệu chứng đặc thù thì chỉ được xem xét những dấu hiệu khởi phát trong vòng 36 tháng trước ngày hiệu lực hợp đồng."),
   ("Có bệnh có sẵn thì có mua được bảo hiểm không?",
    "Được, nếu doanh nghiệp chấp thuận. Thông tư 67 Điều 12 khoản 2 điểm c nêu rõ trường hợp doanh nghiệp chấp thuận bảo hiểm cho bệnh có sẵn thì thời gian chờ tối đa là 1 năm. Nhưng chấp thuận là quyền của doanh nghiệp, không phải nghĩa vụ, nên từ chối cũng không trái luật."),
   ("Quên khai một lần khám cũ thì có bị huỷ hợp đồng không?",
    "Điều 22 khoản 2 chỉ cho huỷ hợp đồng khi bên mua cố ý cung cấp thông tin sai nhằm mục đích được bồi thường. Ba yếu tố cố ý, kê khai sai và mục đích phải cùng có mặt. Quên hoặc không biết mình có bệnh thì về câu chữ không thoả mãn điều kiện đó. Trên thực tế đây là chỗ tranh chấp nhiều nhất, và hồ sơ bệnh án cũ là thứ quyết định. Kết quả từng vụ phụ thuộc hồ sơ thực tế, bài này không kết luận thay cho trường hợp của bạn."),
   ("Sau bao nhiêu năm thì công ty bảo hiểm không được huỷ hợp đồng vì kê khai sai nữa?",
    "Luật Kinh doanh bảo hiểm 2022 không quy định thời hạn nào cho quyền này. Điều 22 khoản 2 trao quyền huỷ bỏ mà không gắn thời hiệu. Con số hai năm hay xuất hiện trên mạng là nhầm với Điều 40 khoản 1 điểm a, một trường hợp hoàn toàn khác, không liên quan tới kê khai sai."),
   ("Bảo hiểm y tế có từ chối vì bệnh có sẵn không?",
    "Không. Điều 23 Luật Bảo hiểm y tế liệt kê các trường hợp không được hưởng, và trong đó không có loại trừ nào theo tiền sử bệnh. Mức hưởng xác định theo mức độ bệnh tật và thời gian tham gia, theo nguyên tắc tại Điều 3."),
 ],
 "lien_quan": ["ly-do-ho-so-bi-tu-choi-boi-thuong"],
},


# =====================================================================
{
 "slug": "thoi-gian-cho-tung-loai-quyen-loi",
 "cum": "C",
 "ngay_dang": "2026-09-07",
 "tag": "Hợp đồng",
 "doc": "7 phút đọc",
 "title": "Thời gian chờ của từng loại quyền lợi: bốn giới hạn trong Thông tư 67",
 "h1": "Thời gian chờ của từng loại quyền lợi",
 "desc": "Thông tư 67/2023/TT-BTC Điều 12 khoản 2 đặt trần cho thời gian chờ: 90 ngày với bệnh, 1 năm với bệnh có sẵn được chấp thuận, 270 ngày với thai sản, và không được áp dụng với tai nạn.",
 "tom_tat": "Thời gian chờ không phải chuyện doanh nghiệp muốn đặt bao lâu cũng được. Thông tư 67/2023/TT-BTC, Điều 12 khoản 2, đặt trần cho từng loại quyền lợi: <b>90 ngày</b> với các trường hợp bệnh, <b>1 năm</b> khi doanh nghiệp chấp thuận bảo hiểm cho bệnh có sẵn, <b>270 ngày</b> với quyền lợi thai sản. Riêng tai nạn thì không được áp dụng thời gian chờ. Hợp đồng có quyền để ngắn hơn, nhưng không được dài hơn các mức này. Bài trích nguyên văn để bạn tự đối chiếu, không thay cho tư vấn pháp lý cho trường hợp cụ thể.",

 "bang": [
   {"ten": "Bốn giới hạn, và mốc bắt đầu tính",
    "kiem_chung": "chinh-thuc",
    "nguon": "Thông tư 67/2023/TT-BTC, Bộ Tài chính, Điều 12 khoản 2. Đây là mức TỐI ĐA; quy tắc điều khoản của từng hợp đồng có thể quy định ngắn hơn.",
    "cot": ["Loại quyền lợi", "Thời gian chờ tối đa", "Điểm trong khoản 2"],
    "hang": [
      ["Tai nạn", "<b>không được áp dụng thời gian chờ</b>", "điểm b"],
      ["Các trường hợp bệnh", "90 ngày", "điểm c"],
      ["Bệnh có sẵn, khi doanh nghiệp chấp thuận bảo hiểm", "1 năm", "điểm c"],
      ["Quyền lợi thai sản", "270 ngày", "điểm d"],
      ["Mốc bắt đầu tính", "từ ngày bắt đầu thời hạn bảo hiểm, hoặc ngày khôi phục hiệu lực hợp đồng gần nhất", "điểm a"],
    ]},
   {"ten": "Trường hợp doanh nghiệp muốn đặt thời gian chờ khác",
    "kiem_chung": "chinh-thuc",
    "nguon": "Thông tư 67/2023/TT-BTC, Điều 12 khoản 2 điểm đ và khoản 7",
    "cot": ["Tình huống", "Thông tư quy định"],
    "hang": [
      ["Sản phẩm có thời gian chờ ngoài mức tại điểm c và điểm d", "doanh nghiệp phải giải trình rõ tại tài liệu giải trình phương pháp, cơ sở tính phí sản phẩm bảo hiểm"],
      ["Sản phẩm cũ đã bán trước khi thông tư áp dụng", "doanh nghiệp có trách nhiệm rà soát, chỉnh sửa để đáp ứng Điều 12 kể từ ngày 01/7/2025"],
    ]},
 ],

 "y_chinh": [
   ("Nguyên văn điểm c, chỗ chứa hai con số quan trọng nhất",
    "Thông tư 67/2023/TT-BTC, Điều 12 khoản 2 điểm c: &ldquo;Đối với các trường hợp bệnh, thời gian chờ tối đa không vượt quá 90 ngày. Đối với trường hợp doanh nghiệp bảo hiểm chấp thuận bảo hiểm cho các bệnh có sẵn, thời gian chờ tối đa là 1 năm.&rdquo; Hai mức này áp cho hai tình huống khác nhau, đừng lẫn: 90 ngày là mức chung cho bệnh, còn 1 năm chỉ đặt ra khi doanh nghiệp đã đồng ý nhận bảo hiểm cho một bệnh bạn đã có từ trước."),
   ("Tai nạn không được có thời gian chờ",
    "Điểm b viết thẳng: &ldquo;Không áp dụng thời gian chờ đối với trường hợp tai nạn.&rdquo; Đây là quy định tuyệt đối, không kèm điều kiện nào. Nếu quy tắc điều khoản đặt thời gian chờ cho quyền lợi tai nạn thì phần đó trái với thông tư."),
   ("Mốc tính lại từ đầu khi hợp đồng khôi phục hiệu lực",
    "Điểm a: thời gian chờ &ldquo;được tính từ ngày bắt đầu thời hạn bảo hiểm hoặc ngày khôi phục hiệu lực hợp đồng gần nhất&rdquo;. Nghĩa là nếu hợp đồng từng mất hiệu lực rồi được khôi phục, đồng hồ thời gian chờ chạy lại từ ngày khôi phục, không phải từ ngày ký ban đầu. Đây là hệ quả ít người để ý khi để hợp đồng mất hiệu lực vì quên đóng phí."),
   ("270 ngày thai sản là trần, không phải con số bắt buộc",
    "Điểm d đặt mức tối đa 270 ngày cho quyền lợi thai sản. Con số này hay được nhắc như thể là quy định chung cho mọi sản phẩm, nhưng thông tư chỉ nói đó là trần. Hợp đồng có thể để ngắn hơn. Khi so sánh, đọc đúng con số trong quy tắc điều khoản của sản phẩm mình định mua, đừng mặc định là 270 ngày."),
   ("Thông tư cho phép có ngoại lệ, nhưng buộc phải giải trình",
    "Điểm đ cho phép doanh nghiệp triển khai sản phẩm có thời gian chờ ngoài mức ở điểm c và d, với điều kiện &ldquo;giải trình rõ tại tài liệu giải trình phương pháp, cơ sở tính phí sản phẩm bảo hiểm&rdquo;. Tức là ngoại lệ tồn tại, nhưng phải có cơ sở tính toán chứ không phải muốn đặt sao cũng được."),
   ("Cả khoản 2 chỉ áp dụng khi hợp đồng CÓ quy định thời gian chờ",
    "Câu dẫn của khoản 2 bắt đầu bằng &ldquo;Trường hợp quy tắc, điều kiện, điều khoản bảo hiểm có quy định thời gian chờ&rdquo;. Nghĩa là thông tư không bắt buộc mọi sản phẩm phải có thời gian chờ. Nó chỉ đặt trần cho những sản phẩm nào có. Việc đầu tiên cần làm là mở quy tắc điều khoản ra xem sản phẩm của mình có điều khoản này hay không."),
   ("Ba việc nên làm trước khi ký",
    "Một: tìm trong quy tắc điều khoản mục thời gian chờ, đọc đúng con số của từng nhóm quyền lợi. Hai: nếu con số nào dài hơn trần ở Điều 12 khoản 2 thì hỏi doanh nghiệp căn cứ vào đâu. Ba: nếu bạn có bệnh đã được chẩn đoán trước đó, hỏi rõ hợp đồng có nhận bảo hiểm cho bệnh đó không, và nếu có thì thời gian chờ áp dụng là bao lâu."),
 ],

 "khong_ro": [
   "Thời gian chờ thực tế của từng sản phẩm trên thị trường. Thông tư chỉ đặt trần, con số cụ thể nằm trong quy tắc điều khoản của từng hợp đồng. Chúng tôi không so sánh sản phẩm giữa các doanh nghiệp.",
   "Danh sách bệnh nào thuộc nhóm nào để áp thời gian chờ tương ứng. Không có văn bản nhà nước nào liệt kê.",
   "Điều gì xảy ra nếu quy tắc điều khoản đặt thời gian chờ vượt trần mà không giải trình. Thông tư không nêu chế tài cụ thể trong Điều 12.",
   "Thời gian chờ có được tính lại khi chuyển đổi sản phẩm trong cùng một doanh nghiệp hay không. Điều 12 chỉ nói tới ngày bắt đầu thời hạn bảo hiểm và ngày khôi phục hiệu lực.",
 ],

 "faq": [
   ("Thời gian chờ tối đa của bảo hiểm sức khoẻ là bao lâu?",
    "Theo Thông tư 67/2023/TT-BTC Điều 12 khoản 2: tối đa 90 ngày với các trường hợp bệnh, tối đa 1 năm khi doanh nghiệp chấp thuận bảo hiểm cho bệnh có sẵn, và tối đa 270 ngày với quyền lợi thai sản. Với tai nạn thì không được áp dụng thời gian chờ."),
   ("Quyền lợi tai nạn có thời gian chờ không?",
    "Không. Điều 12 khoản 2 điểm b của Thông tư 67 quy định không áp dụng thời gian chờ đối với trường hợp tai nạn. Đây là quy định không kèm điều kiện nào."),
   ("Thời gian chờ tính từ ngày nào?",
    "Từ ngày bắt đầu thời hạn bảo hiểm, hoặc từ ngày khôi phục hiệu lực hợp đồng gần nhất, theo Điều 12 khoản 2 điểm a. Nếu hợp đồng từng mất hiệu lực rồi khôi phục thì đồng hồ chạy lại từ ngày khôi phục."),
   ("Thời gian chờ thai sản có phải luôn là 270 ngày không?",
    "Không. 270 ngày là mức tối đa mà thông tư cho phép, không phải con số bắt buộc. Hợp đồng có thể quy định ngắn hơn. Phải đọc đúng con số trong quy tắc điều khoản của sản phẩm mình mua."),
   ("Có bệnh sẵn thì thời gian chờ là bao lâu?",
    "Nếu doanh nghiệp chấp thuận bảo hiểm cho bệnh có sẵn đó thì thời gian chờ tối đa là 1 năm, theo Điều 12 khoản 2 điểm c. Nhưng chấp thuận là quyền của doanh nghiệp, không phải nghĩa vụ."),
 ],
 "lien_quan": ["benh-co-san-duoc-hieu-the-nao"],
},

# =====================================================================
{
 "slug": "bhyt-khong-chi-tra-nhung-gi",
 "cum": "D",
 "ngay_dang": "2026-09-07",
 "tag": "BHYT",
 "doc": "8 phút đọc",
 "title": "Bảo hiểm y tế không chi trả những gì: mười hai trường hợp trong Điều 23",
 "h1": "Bảo hiểm y tế không chi trả những gì",
 "desc": "Điều 23 Luật Bảo hiểm y tế liệt kê các trường hợp không được hưởng BHYT. Đây là danh sách đóng, hiện còn mười hai khoản đang áp dụng, trích nguyên văn kèm phần đã sửa đổi năm 2024.",
 "tom_tat": "Điều 23 Luật Bảo hiểm y tế là danh sách đóng. Cái gì nằm ngoài danh sách đó thì thuộc phạm vi được hưởng, còn hưởng bao nhiêu thì tuỳ thẻ. Điều này đánh số tới 14 khoản nhưng hai khoản đã bãi bỏ, nên hiện còn <b>12 khoản</b> đang áp dụng. Đọc hết mười hai khoản sẽ thấy không có bệnh có sẵn, không có bệnh mắc trước khi tham gia, và không có loại trừ nào theo tiền sử bệnh.",

 "bang": [
   {"ten": "Mười hai trường hợp không được hưởng BHYT, trích nguyên văn",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Bảo hiểm y tế, văn bản hợp nhất số 47/VBHN-VPQH năm 2023, Điều 23. Khoản 10 và khoản 12 đã được bãi bỏ nên không liệt kê. Khoản 7 và khoản 8 đã được sửa bởi Luật số 51/2024/QH15 ngày 27/11/2024, bản mới ghi ở bảng dưới.",
    "cot": ["Khoản", "Nguyên văn"],
    "hang": [
      ["1", "Chi phí trong trường hợp quy định tại khoản 1 Điều 21 đã được ngân sách nhà nước chi trả"],
      ["2", "Điều dưỡng, an dưỡng tại cơ sở điều dưỡng, an dưỡng"],
      ["3", "Khám sức khỏe"],
      ["4", "Xét nghiệm, chẩn đoán thai không nhằm mục đích điều trị"],
      ["5", "Sử dụng kỹ thuật hỗ trợ sinh sản, dịch vụ kế hoạch hóa gia đình, nạo hút thai, phá thai, trừ trường hợp phải đình chỉ thai nghén do nguyên nhân bệnh lý"],
      ["6", "Sử dụng dịch vụ thẩm mỹ"],
      ["7 <i>(bản cũ, xem bảng dưới)</i>", "Điều trị lác, cận thị và tật khúc xạ của mắt, trừ trường hợp trẻ em dưới 6 tuổi"],
      ["8 <i>(bản cũ, xem bảng dưới)</i>", "Sử dụng vật tư y tế thay thế bao gồm chân tay giả, mắt giả, răng giả, kính mắt, máy trợ thính"],
      ["9", "Khám bệnh, chữa bệnh, phục hồi chức năng trong trường hợp thảm họa"],
      ["11", "Khám bệnh, chữa bệnh nghiện ma túy, nghiện rượu hoặc chất gây nghiện khác"],
      ["13", "Giám định y khoa, giám định pháp y, giám định pháp y tâm thần"],
      ["14", "Tham gia thử nghiệm lâm sàng, nghiên cứu khoa học"],
    ]},
   {"ten": "Hai khoản đã sửa bởi Luật số 51/2024/QH15",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật số 51/2024/QH15 ngày 27/11/2024 sửa đổi, bổ sung một số điều của Luật Bảo hiểm y tế",
    "cot": ["Khoản", "Nội dung sau khi sửa"],
    "hang": [
      ["7", "Điều trị lác và tật khúc xạ của mắt đối với người từ đủ 18 tuổi trở lên"],
      ["8", "Sử dụng thiết bị y tế thay thế bao gồm chân giả, tay giả, mắt giả, răng giả, kính mắt, máy trợ thính, phương tiện trợ giúp vận động trong khám bệnh, chữa bệnh và phục hồi chức năng"],
    ]},
   {"ten": "Nguyên tắc xác định mức hưởng, để đối chiếu với bảo hiểm thương mại",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Bảo hiểm y tế, văn bản hợp nhất số 47/VBHN-VPQH năm 2023, Điều 2 và Điều 3",
    "cot": ["Tiêu chí", "Luật quy định"],
    "hang": [
      ["Tính chất", "bảo hiểm bắt buộc, không vì mục đích lợi nhuận, do Nhà nước tổ chức thực hiện (Điều 2)"],
      ["Mức đóng", "theo tỷ lệ phần trăm tiền lương (Điều 3)"],
      ["Mức hưởng", "theo mức độ bệnh tật và thời gian tham gia (Điều 3)"],
      ["Có xét tình trạng sức khoẻ khi tham gia không", "không"],
    ]},
 ],

 "y_chinh": [
   ("Vì sao nên đọc danh sách này thay vì đi tìm danh sách được chi trả",
    "Điều 23 là một danh sách đóng. Luật liệt kê những gì KHÔNG được hưởng, phần còn lại thuộc phạm vi được hưởng theo mức hưởng của thẻ. Vì vậy đọc mười hai khoản này nhanh hơn và chắc hơn là đi tìm một danh mục các bệnh được chi trả, vốn không tồn tại dưới dạng đó."),
   ("Điều 23 đánh số tới 14 nhưng chỉ còn 12 khoản áp dụng",
    "Khoản 10 và khoản 12 đã được bãi bỏ. Số thứ tự vẫn giữ nguyên trong văn bản nên nhìn qua tưởng có 14 trường hợp. Khi ai đó nói BHYT có 14 trường hợp không chi trả, họ đang đếm cả hai khoản đã bỏ."),
   ("Hai khoản đã đổi năm 2024, phần đổi liên quan trực tiếp tới nhiều người",
    "Luật số 51/2024/QH15 sửa khoản 7 thành &ldquo;Điều trị lác và tật khúc xạ của mắt đối với người từ đủ 18 tuổi trở lên&rdquo;. So với bản cũ vốn loại trừ mọi người trừ trẻ dưới 6 tuổi, bản mới thu hẹp phạm vi loại trừ lại. Khoản 8 cũng đổi từ &ldquo;vật tư y tế thay thế&rdquo; sang &ldquo;thiết bị y tế thay thế&rdquo; và bổ sung phương tiện trợ giúp vận động."),
   ("Không có loại trừ nào theo tiền sử bệnh",
    "Trong mười hai khoản không có bệnh có sẵn, không có bệnh mắc trước khi tham gia, không có bất kỳ loại trừ nào dựa trên tiền sử. Điều 3 cũng nói mức hưởng xác định theo mức độ bệnh tật và thời gian tham gia, không theo tình trạng sức khoẻ lúc tham gia. Người đã có bệnh vẫn tham gia và vẫn hưởng BHYT bình thường. Đây là khác biệt bản chất với bảo hiểm sức khoẻ thương mại."),
   ("Khám sức khoẻ và xét nghiệm chẩn đoán thai nằm ngoài phạm vi chi trả",
    "Khoản 3 loại trừ khám sức khỏe, khoản 4 loại trừ &ldquo;xét nghiệm, chẩn đoán thai không nhằm mục đích điều trị&rdquo;. Đây là hai khoản người đi khám thai hay gặp nhất. Phần khám thai định kỳ thuần tuý theo dõi, không nhằm điều trị, nằm ngoài phạm vi BHYT."),
   ("Đình chỉ thai nghén do bệnh lý là ngoại lệ nằm ngay trong khoản 5",
    "Khoản 5 loại trừ nạo hút thai và phá thai, nhưng có đuôi &ldquo;trừ trường hợp phải đình chỉ thai nghén do nguyên nhân bệnh lý&rdquo;. Vế sau này quan trọng và hay bị bỏ qua khi người ta trích khoản 5."),
   ("Danh sách này không nói mức hưởng là bao nhiêu",
    "Điều 23 chỉ trả lời câu hỏi có thuộc phạm vi hay không. Còn thuộc phạm vi thì được trả bao nhiêu phần trăm lại phụ thuộc loại thẻ, nơi đăng ký khám ban đầu và dịch vụ cụ thể. Hai câu hỏi khác nhau, đừng gộp."),
 ],

 "khong_ro": [
   "Mức hưởng phần trăm cho từng nhóm đối tượng và từng tình huống khám chữa bệnh. Nằm ở các điều khác của Luật Bảo hiểm y tế và các văn bản hướng dẫn, chúng tôi chưa đọc hết nên không đăng con số.",
   "Danh mục thuốc BHYT và cột tỷ lệ thanh toán của từng hoạt chất. Chúng tôi chưa mở được bản đầy đủ.",
   "Ranh giới thực tế giữa xét nghiệm chẩn đoán thai không nhằm điều trị và xét nghiệm nhằm điều trị. Luật không định nghĩa, thực tế do cơ sở khám chữa bệnh xác định.",
   "Thế nào là thảm hoạ theo khoản 9. Luật Bảo hiểm y tế không định nghĩa trong điều này.",
   "Các trường hợp không được hưởng do văn bản dưới luật quy định thêm, nếu có. Chúng tôi chỉ đọc Điều 23 và phần sửa đổi năm 2024.",
 ],

 "faq": [
   ("Bảo hiểm y tế không chi trả những gì?",
    "Điều 23 Luật Bảo hiểm y tế liệt kê các trường hợp không được hưởng, hiện còn mười hai khoản đang áp dụng: chi phí đã được ngân sách nhà nước chi trả, điều dưỡng và an dưỡng, khám sức khoẻ, xét nghiệm chẩn đoán thai không nhằm điều trị, hỗ trợ sinh sản và kế hoạch hoá gia đình, dịch vụ thẩm mỹ, điều trị lác và tật khúc xạ với người từ đủ 18 tuổi, thiết bị y tế thay thế, khám chữa bệnh trong thảm hoạ, điều trị nghiện, giám định y khoa và pháp y, và tham gia thử nghiệm lâm sàng."),
   ("Có bệnh sẵn thì BHYT có từ chối chi trả không?",
    "Không. Trong mười hai khoản của Điều 23 không có bệnh có sẵn, không có bệnh mắc trước khi tham gia, và không có loại trừ nào theo tiền sử bệnh. Điều 3 quy định mức hưởng xác định theo mức độ bệnh tật và thời gian tham gia, không theo tình trạng sức khoẻ lúc tham gia."),
   ("Khám thai có được BHYT chi trả không?",
    "Khoản 4 Điều 23 loại trừ xét nghiệm và chẩn đoán thai không nhằm mục đích điều trị. Nghĩa là phần theo dõi thai thuần tuý nằm ngoài phạm vi. Ranh giới cụ thể giữa theo dõi và điều trị thì luật không định nghĩa, do cơ sở khám chữa bệnh xác định."),
   ("Vì sao có nơi nói 14 trường hợp, có nơi nói 12?",
    "Vì Điều 23 đánh số tới 14 khoản nhưng khoản 10 và khoản 12 đã được bãi bỏ, số thứ tự thì giữ nguyên. Nơi nói 14 là đếm cả hai khoản đã bỏ. Hiện còn 12 khoản đang áp dụng."),
   ("Mổ mắt cận có được BHYT chi trả không?",
    "Theo khoản 7 đã sửa bởi Luật số 51/2024/QH15, điều trị lác và tật khúc xạ của mắt không được hưởng BHYT đối với người từ đủ 18 tuổi trở lên. Bản cũ loại trừ rộng hơn, chỉ trừ trẻ em dưới 6 tuổi."),
   ("BHYT chi trả bao nhiêu phần trăm?",
    "Điều 23 không trả lời câu này. Nó chỉ nói trường hợp nào nằm ngoài phạm vi. Mức hưởng phụ thuộc loại thẻ, nơi đăng ký khám ban đầu và dịch vụ cụ thể, quy định ở các điều khác mà bài này chưa đọc hết nên không đưa con số."),
 ],
 "lien_quan": ["chi-phi-dieu-tri-ung-thu", "chi-phi-dieu-tri-dot-quy"],
},


# =====================================================================
{
 "slug": "bao-lanh-vien-phi-hoat-dong-the-nao",
 "cum": "D",
 "ngay_dang": "2026-09-08",
 "tag": "Viện phí",
 "doc": "8 phút đọc",
 "title": "Bảo lãnh viện phí hoạt động thế nào: khảo sát 19 bệnh viện công bố những gì",
 "h1": "Bảo lãnh viện phí hoạt động thế nào",
 "desc": "Chúng tôi rà trang chính thức của 19 bệnh viện. Bốn nơi công bố danh sách đối tác có tên, hai nơi chỉ có con số, năm nơi nói có mà không nói ai, một nơi nói thẳng là không áp dụng, bảy nơi không nhắc tới.",
 "tom_tat": "Bảo lãnh viện phí là bệnh viện thu tiền thẳng từ công ty bảo hiểm, thay vì bắt bạn ứng trước rồi đi đòi lại. Nghe đơn giản, nhưng thứ quyết định là bệnh viện đó có thoả thuận với đúng đơn vị phát hành thẻ của bạn hay không. Chúng tôi mở trang chính thức của <b>19 bệnh viện</b> đã viết bài và đếm: 4 nơi đăng danh sách đối tác kèm tên, 2 nơi chỉ đưa con số, 5 nơi nói có mà không nói ai, 1 nơi nói thẳng là không áp dụng, 7 nơi không nhắc tới.",

 "bang": [
   {"ten": "19 bệnh viện công bố những gì về bảo lãnh viện phí",
    "kiem_chung": "chinh-thuc",
    "nguon": "Tổng hợp từ các trang bệnh viện chúng tôi đã đọc trực tiếp và đã đăng thành bài riêng, ngày rà từ 01/09 đến 08/09/2026. Mỗi con số đều dẫn về trang chính thức của bệnh viện đó, xem bài riêng để có URL và ngày.",
    "cot": ["Mức độ công bố", "Bệnh viện", "Con số bệnh viện tự nêu"],
    "hang": [
      ["Có danh sách đối tác kèm tên", "FV", "102 đơn vị thanh toán trực tiếp"],
      ["Có danh sách đối tác kèm tên", "Vinmec", "35 công ty"],
      ["Có danh sách đối tác kèm tên", "Tâm Anh", "khoảng 18 công ty"],
      ["Có danh sách đối tác kèm tên", "Hoàn Mỹ Sài Gòn", "6 đối tác quốc tế công bố 03/2026, thêm 4 đơn vị nêu ở trang giới thiệu"],
      ["Chỉ có con số, không có tên", "Việt Pháp Hà Nội", "43 công ty bảo hiểm, 7 đơn vị hỗ trợ, 1 công ty quản lý"],
      ["Chỉ có con số, không có tên", "Xuyên Á", "hơn 30 công ty"],
      ["Nói có, không nêu số cũng không nêu tên", "Quốc tế City", "không có"],
      ["Nói có, không nêu số cũng không nêu tên", "Quốc tế Hạnh Phúc", "chỉ có hai bản tin lẻ, không có trang tổng hợp"],
      ["Nói có, không nêu số cũng không nêu tên", "Thu Cúc", "có chuyên mục nhưng không mở được nội dung"],
      ["Nói có, không nêu số cũng không nêu tên", "Hồng Ngọc", "trang bảo lãnh viện phí trả về lỗi 404"],
      ["Nói có, không nêu số cũng không nêu tên", "Bảo Sơn", "không tìm thấy công bố chính thức"],
      ["Nói rõ KHÔNG áp dụng", "An Sinh", "khách có quyền lợi bảo hiểm thương mại sẽ không được bảo lãnh trực tiếp"],
      ["Không nhắc tới trên trang thai sản", "Từ Dũ, Hùng Vương, Phụ sản MêKông, ĐH Y Dược TP.HCM, Nhân dân Gia Định, Phụ sản Hà Nội, Phụ sản Trung ương", "không có"],
    ]},
   {"ten": "Hai cách bệnh viện xử lý khi thư bảo lãnh chưa về hoặc thấp hơn dự toán",
    "kiem_chung": "chinh-thuc",
    "nguon": "Trang chính sách giá của Bệnh viện Quốc tế City và của Bệnh viện Việt Pháp Hà Nội, cùng trang hướng dẫn nhập viện của FV. Đây là ví dụ chính các bệnh viện tự đưa ra.",
    "cot": ["Bệnh viện", "Cách xử lý bệnh viện công bố"],
    "hang": [
      ["Quốc tế City", "ví dụ bệnh viện tự nêu: phẫu thuật ước tính 10 triệu, bảo hiểm chỉ xác nhận bảo lãnh 8 triệu, phần chênh 2 triệu do người bệnh đặt cọc; nếu thư bảo lãnh về sau thì tiền cọc được hoàn"],
      ["Việt Pháp Hà Nội", "nội trú phải đặt cọc theo dự toán, bệnh viện ghi rõ không chấp nhận công nợ cá nhân"],
      ["FV", "phải đặt cọc nếu chưa có thư bảo lãnh, bệnh viện không nêu mức cọc"],
    ]},
 ],

 "y_chinh": [
   ("Bảo lãnh viện phí là gì, nói cho gọn",
    "Thay vì bạn trả tiền cho bệnh viện rồi nộp chứng từ đòi công ty bảo hiểm hoàn lại, bệnh viện làm việc thẳng với công ty bảo hiểm. Bạn chỉ trả phần chênh nếu có. Điều kiện là giữa bệnh viện đó và công ty bảo hiểm đó phải có thoả thuận sẵn. Không có thoả thuận thì thẻ vẫn dùng được, chỉ là bạn phải ứng tiền trước."),
   ("Con số quan trọng nhất không phải bệnh viện có bảo lãnh hay không, mà là có với hãng của bạn hay không",
    "Gần như bệnh viện tư nào cũng nói có bảo lãnh viện phí. Nhưng số đối tác chênh nhau rất xa: FV công bố 102 đơn vị, Việt Pháp Hà Nội 43, Vinmec 35, Xuyên Á hơn 30, Tâm Anh khoảng 18, Hoàn Mỹ Sài Gòn thì hẹp hơn nhiều. Một bệnh viện có 102 đối tác vẫn có thể không có hãng của bạn. Vì vậy câu hỏi đúng luôn là hỏi tên hãng cụ thể, không phải hỏi chung chung."),
   ("Chỉ 4 trong 19 bệnh viện cho bạn tự kiểm tra được",
    "Bốn nơi đăng danh sách kèm tên là FV, Vinmec, Tâm Anh và Hoàn Mỹ Sài Gòn. Với 15 nơi còn lại, bạn không có cách nào tự tra trước khi gọi điện. Hai nơi đưa con số mà giấu tên, năm nơi chỉ nói chung là có, một nơi nói không, bảy nơi không nhắc gì. Đây là lý do bước gọi hỏi trước khi nhập viện không bỏ được."),
   ("Danh sách đối tác thay đổi, và bệnh viện không phải lúc nào cũng cập nhật",
    "Trang thai sản của Tâm Anh có ghi một đơn vị đã dừng bảo lãnh tại cơ sở TP.HCM, nghĩa là người cầm thẻ đó phải tự thanh toán rồi đòi lại sau. Đây là loại thay đổi nhiều người chỉ biết khi đứng ở quầy thu ngân. Danh sách bạn đọc trên mạng hôm nay có thể đã cũ, kể cả danh sách trên chính website bệnh viện."),
   ("Có bảo lãnh không có nghĩa là không phải đặt cọc",
    "Ba bệnh viện nói rõ vẫn thu cọc. Quốc tế City đưa hẳn ví dụ: ca ước tính 10 triệu, bảo hiểm xác nhận bảo lãnh 8 triệu, bạn đặt cọc phần chênh 2 triệu, thư bảo lãnh về sau thì hoàn lại. Việt Pháp Hà Nội yêu cầu đặt cọc theo dự toán và ghi thẳng là không nhận công nợ cá nhân. FV yêu cầu cọc nếu chưa có thư bảo lãnh. Nên chuẩn bị tiền mặt kể cả khi đã có thẻ."),
   ("Một bệnh viện nói thẳng là không áp dụng, và đó là thông tin đáng giá",
    "Điều kiện mua gói của An Sinh ghi khách hàng có quyền lợi bảo hiểm sức khoẻ của công ty bảo hiểm thương mại sẽ không được áp dụng bảo lãnh viện phí trực tiếp tại bệnh viện. Bệnh viện này cũng ghi thanh toán một lần trọn gói, không nhận tạm ứng. Nói rõ như vậy tốt hơn nhiều so với nói chung chung, vì bạn biết đường chuẩn bị."),
   ("Bệnh viện công gần như không nói gì về bảo lãnh thương mại",
    "Bảy bệnh viện công trong danh sách không nhắc tới bảo lãnh viện phí trên trang thai sản. Điều đó không có nghĩa là chắc chắn không có, chỉ là không công bố. Ở khối công, cơ chế chính vẫn là BHYT, còn phần bảo hiểm thương mại thường xử lý theo hướng bạn tự trả rồi lấy chứng từ."),
   ("Bốn câu nên hỏi trước khi nhập viện",
    "Một: thẻ của tôi do đơn vị này phát hành, bệnh viện có nhận bảo lãnh trực tiếp không, xin xác nhận bằng văn bản hoặc tin nhắn. Hai: nếu có thì tôi cần nộp giấy tờ gì và nộp trước bao lâu. Ba: có phải đặt cọc không, bao nhiêu, và hoàn lại khi nào. Bốn: khoản nào chắc chắn nằm ngoài phạm vi bảo lãnh để tôi chuẩn bị tiền."),
 ],

 "khong_ro": [
   "Tên đầy đủ các đơn vị bảo lãnh của 15 bệnh viện không công bố danh sách. Chúng tôi không đăng lại tên từ nguồn thứ ba vì các danh sách lưu hành trên mạng không trùng khớp nhau.",
   "Danh sách nào còn hiệu lực tính đến hôm nay. Bệnh viện thay đổi đối tác mà không phải lúc nào cũng cập nhật trang web.",
   "Mức cọc cụ thể của từng bệnh viện. Chỉ Quốc tế City đưa ví dụ bằng số, còn lại nói theo dự toán.",
   "Thủ tục và thời gian xử lý thư bảo lãnh. Không bệnh viện nào trong danh sách công bố mốc thời gian.",
   "Bảo lãnh áp dụng cho những nhóm chi phí nào và loại trừ nhóm nào. Đây là phần thuộc hợp đồng bảo hiểm của bạn, không phải thông tin bệnh viện công bố.",
 ],

 "faq": [
   ("Bảo lãnh viện phí là gì?",
    "Là việc bệnh viện thanh toán trực tiếp với công ty bảo hiểm thay vì để bạn ứng tiền trước rồi nộp chứng từ đòi lại. Điều kiện là bệnh viện và công ty bảo hiểm đó có thoả thuận sẵn với nhau."),
   ("Bệnh viện nào công bố danh sách đối tác bảo lãnh?",
    "Trong 19 bệnh viện chúng tôi đã rà, bốn nơi đăng danh sách kèm tên: FV (102 đơn vị), Vinmec (35 công ty), Tâm Anh (khoảng 18 công ty) và Hoàn Mỹ Sài Gòn (6 đối tác quốc tế công bố tháng 3/2026 cộng vài đơn vị nêu ở trang giới thiệu). Việt Pháp Hà Nội và Xuyên Á có công bố con số nhưng không nêu tên."),
   ("Có thẻ bảo hiểm sức khoẻ là chắc chắn được bảo lãnh phải không?",
    "Không. Phải có thoả thuận giữa đúng bệnh viện đó và đúng đơn vị phát hành thẻ của bạn. Ngay cả bệnh viện có hơn một trăm đối tác cũng có thể không có đơn vị của bạn. Và danh sách thay đổi theo thời gian."),
   ("Được bảo lãnh rồi thì có phải đặt cọc không?",
    "Nhiều nơi vẫn thu. Quốc tế City nêu ví dụ ca ước tính 10 triệu mà bảo hiểm chỉ xác nhận 8 triệu thì bạn đặt cọc phần chênh 2 triệu. Việt Pháp Hà Nội yêu cầu đặt cọc theo dự toán và ghi rõ không chấp nhận công nợ cá nhân. FV yêu cầu cọc nếu chưa có thư bảo lãnh."),
   ("Bệnh viện công có bảo lãnh viện phí không?",
    "Bảy bệnh viện công trong danh sách của chúng tôi không nhắc tới việc này trên trang thai sản. Không công bố không có nghĩa là chắc chắn không có, nhưng bạn nên hỏi trực tiếp và chuẩn bị phương án tự thanh toán rồi lấy chứng từ."),
   ("Vì sao bài này không liệt kê tên các công ty bảo hiểm?",
    "Vì phần lớn bệnh viện không công bố tên, và các danh sách lưu hành trên mạng không trùng khớp nhau nên không kiểm chứng được. Chúng tôi chỉ đăng con số do chính bệnh viện nêu, và khuyên bạn hỏi tên hãng cụ thể của mình trực tiếp với bệnh viện."),
 ],
 "lien_quan": ["bhyt-khong-chi-tra-nhung-gi"],
},

# =====================================================================
{
 "slug": "dieu-khoan-loai-tru",
 "cum": "C",
 "ngay_dang": "2026-09-08",
 "tag": "Hợp đồng",
 "doc": "7 phút đọc",
 "title": "Điều khoản loại trừ: luật buộc doanh nghiệp phải chứng minh đã giải thích cho bạn",
 "h1": "Điều khoản loại trừ trong hợp đồng bảo hiểm",
 "desc": "Điều 19 Luật Kinh doanh bảo hiểm 2022 buộc doanh nghiệp phải giải thích rõ điều khoản loại trừ và phải có bằng chứng bạn đã hiểu. Nghĩa vụ chứng minh nằm ở phía doanh nghiệp.",
 "tom_tat": "Điều khoản loại trừ liệt kê những trường hợp doanh nghiệp bảo hiểm không phải trả tiền. Phần này ngắn nhưng khi có chuyện thì nó quyết định. Chỗ ít người biết nằm ở <b>Điều 19</b> Luật Kinh doanh bảo hiểm số 08/2022/QH15: luật không dừng ở việc buộc doanh nghiệp giải thích, mà còn buộc phải có bằng chứng rằng bạn đã được giải thích đầy đủ và đã hiểu. Nghĩa vụ chứng minh nằm ở phía doanh nghiệp, không phải phía bạn. Bài trích nguyên văn để bạn tự đối chiếu, không thay cho tư vấn pháp lý cho trường hợp cụ thể.",

 "bang": [
   {"ten": "Ba khoản của Điều 19, trích nguyên văn",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Kinh doanh bảo hiểm số 08/2022/QH15, Điều 19, hiệu lực từ 01/01/2023",
    "cot": ["Khoản", "Nguyên văn"],
    "hang": [
      ["1", "Điều khoản loại trừ trách nhiệm bảo hiểm quy định các trường hợp doanh nghiệp bảo hiểm, chi nhánh doanh nghiệp bảo hiểm phi nhân thọ nước ngoài không phải bồi thường, trả tiền bảo hiểm."],
      ["2", "Trường hợp có điều khoản loại trừ trách nhiệm bảo hiểm, doanh nghiệp bảo hiểm... phải quy định rõ trong hợp đồng bảo hiểm, phải giải thích rõ ràng, đầy đủ và có bằng chứng xác nhận việc bên mua bảo hiểm đã được doanh nghiệp bảo hiểm... giải thích đầy đủ và hiểu rõ nội dung này khi giao kết hợp đồng bảo hiểm."],
      ["3", "Trường hợp có sự kiện bất khả kháng hoặc trở ngại khách quan dẫn đến bên mua bảo hiểm chậm thông báo sự kiện bảo hiểm thì doanh nghiệp bảo hiểm... không được áp dụng điều khoản loại trừ trách nhiệm bảo hiểm về việc chậm thông báo."],
    ]},
   {"ten": "Ba điều kiện khoản 2 đặt ra cho doanh nghiệp",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Kinh doanh bảo hiểm số 08/2022/QH15, Điều 19 khoản 2. Đây là phần bóc tách câu chữ của chính khoản đó.",
    "cot": ["Điều kiện", "Nguyên văn"],
    "hang": [
      ["Phải có trong hợp đồng", "&ldquo;phải quy định rõ trong hợp đồng bảo hiểm&rdquo;"],
      ["Phải giải thích", "&ldquo;phải giải thích rõ ràng, đầy đủ&rdquo;"],
      ["Phải chứng minh được là đã giải thích và bạn đã hiểu", "&ldquo;có bằng chứng xác nhận việc bên mua bảo hiểm đã được... giải thích đầy đủ và hiểu rõ nội dung này&rdquo;"],
    ]},
 ],

 "y_chinh": [
   ("Chữ đáng giá nhất trong Điều 19 là cụm có bằng chứng xác nhận",
    "Khoản 2 không dừng ở việc buộc doanh nghiệp giải thích. Nó buộc phải có bằng chứng xác nhận rằng bên mua đã được giải thích đầy đủ và đã hiểu rõ. Nghĩa là khi tranh chấp, bên phải trưng ra bằng chứng là doanh nghiệp, không phải bạn. Đây là điểm nhiều người không biết nên mặc định là mình phải chứng minh mình không được giải thích."),
   ("Loại trừ phải nằm trong hợp đồng, không phải ở tài liệu bán hàng",
    "Khoản 2 mở đầu bằng &ldquo;phải quy định rõ trong hợp đồng bảo hiểm&rdquo;. Một điều khoản loại trừ chỉ xuất hiện trong tờ rơi, bài đăng hay lời tư vấn miệng mà không có trong hợp đồng thì không đáp ứng câu chữ của điều này. Khi nhận bộ hợp đồng, việc đầu tiên là tìm mục loại trừ và đọc hết."),
   ("Chậm thông báo vì lý do bất khả kháng thì không bị áp loại trừ",
    "Khoản 3 nói rõ: khi có sự kiện bất khả kháng hoặc trở ngại khách quan dẫn đến bên mua chậm thông báo, doanh nghiệp không được áp dụng điều khoản loại trừ về việc chậm thông báo. Đây là điều khoản bảo vệ trực tiếp trong tình huống thực tế hay gặp, ví dụ người được bảo hiểm đang nằm viện nặng nên gia đình không kịp báo đúng hạn."),
   ("Luật không liệt kê trường hợp nào được loại trừ",
    "Điều 19 chỉ đặt ra thủ tục: phải ghi rõ, phải giải thích, phải có bằng chứng. Còn nội dung loại trừ cụ thể thì do quy tắc điều khoản của từng sản phẩm quy định. Không có danh mục loại trừ chung do Nhà nước ban hành. Vì vậy đọc quy tắc điều khoản của chính sản phẩm mình mua là việc không ai làm thay được."),
   ("Việc cần làm khi ký, và việc cần giữ",
    "Khi ký, yêu cầu người tư vấn chỉ đúng trang có mục loại trừ và đọc qua từng dòng. Sau khi ký, giữ lại mọi thứ chứng minh quá trình đó: bộ hợp đồng đầy đủ, biên bản hoặc phiếu xác nhận đã được giải thích, tin nhắn và email trao đổi. Không phải để đi kiện, mà vì Điều 19 khoản 2 đặt nghĩa vụ chứng minh ở phía doanh nghiệp và hồ sơ đầy đủ giúp làm rõ chuyện đó nhanh hơn."),
   ("Điều 19 đi kèm với Điều 22, đọc cùng nhau mới đủ",
    "Điều 19 nói về nghĩa vụ giải thích của doanh nghiệp. Điều 22 nói về hậu quả khi bên mua cung cấp thông tin sai. Hai điều này thường cùng xuất hiện trong một vụ tranh chấp: doanh nghiệp viện dẫn Điều 22 để huỷ hợp đồng, còn người mua viện dẫn Điều 19 để hỏi bằng chứng đã giải thích. Chúng tôi có bài riêng về Điều 22."),
 ],

 "khong_ro": [
   "Bằng chứng thế nào thì được coi là đủ theo khoản 2. Luật không nêu hình thức, có thể là chữ ký xác nhận, bản ghi âm, hoặc tài liệu khác. Không có văn bản nào chúng tôi đọc được quy định cụ thể.",
   "Danh mục các trường hợp loại trừ. Luật không ban hành, do quy tắc điều khoản từng sản phẩm quy định.",
   "Chế tài khi doanh nghiệp không có bằng chứng đã giải thích. Điều 19 không nêu hậu quả cụ thể trong chính điều này.",
   "Thế nào là sự kiện bất khả kháng hoặc trở ngại khách quan theo khoản 3. Điều 19 không định nghĩa.",
   "Số liệu về tỷ lệ tranh chấp liên quan tới điều khoản loại trừ. Chúng tôi không tìm thấy thống kê công khai chính thức nào.",
 ],

 "faq": [
   ("Điều khoản loại trừ là gì?",
    "Theo Điều 19 khoản 1 Luật Kinh doanh bảo hiểm 2022, đó là phần quy định các trường hợp doanh nghiệp bảo hiểm không phải bồi thường hoặc trả tiền bảo hiểm."),
   ("Công ty bảo hiểm có bắt buộc phải giải thích điều khoản loại trừ không?",
    "Có. Điều 19 khoản 2 buộc doanh nghiệp phải quy định rõ trong hợp đồng, phải giải thích rõ ràng và đầy đủ, và phải có bằng chứng xác nhận rằng bên mua đã được giải thích đầy đủ và hiểu rõ nội dung đó khi giao kết hợp đồng."),
   ("Nếu tôi không được giải thích thì ai phải chứng minh?",
    "Theo câu chữ của Điều 19 khoản 2, doanh nghiệp là bên phải có bằng chứng xác nhận đã giải thích và bên mua đã hiểu rõ. Luật đặt nghĩa vụ đó ở phía doanh nghiệp. Kết quả từng vụ vẫn phụ thuộc hồ sơ thực tế, bài này không kết luận thay cho trường hợp của bạn."),
   ("Báo tin chậm thì có bị từ chối không?",
    "Điều 19 khoản 3 quy định nếu có sự kiện bất khả kháng hoặc trở ngại khách quan dẫn đến chậm thông báo thì doanh nghiệp không được áp dụng điều khoản loại trừ về việc chậm thông báo. Luật không định nghĩa thế nào là bất khả kháng trong chính điều này."),
   ("Có danh sách chung các trường hợp bị loại trừ không?",
    "Không. Luật chỉ đặt ra thủ tục phải ghi rõ, phải giải thích và phải có bằng chứng. Nội dung loại trừ cụ thể nằm trong quy tắc điều khoản của từng sản phẩm, nên phải đọc đúng bộ hợp đồng của mình."),
 ],
 "lien_quan": ["ly-do-ho-so-bi-tu-choi-boi-thuong", "benh-co-san-duoc-hieu-the-nao"],
},


# =====================================================================
{
 "slug": "21-ngay-can-nhac-hop-dong-bao-hiem",
 "cum": "C",
 "ngay_dang": "2026-09-09",
 "tag": "Hợp đồng",
 "doc": "6 phút đọc",
 "title": "21 ngày cân nhắc: Điều 35 Luật Kinh doanh bảo hiểm nói gì và để trống những gì",
 "h1": "Thời gian cân nhắc 21 ngày",
 "desc": "Điều 35 Luật Kinh doanh bảo hiểm 2022 cho bên mua quyền từ chối tiếp tục tham gia trong 21 ngày. Nhưng điều luật chỉ áp dụng cho hợp đồng trên 01 năm, và không nói được hoàn 100%. Trích nguyên văn.",
 "tom_tat": "Câu hay nghe khi ký hợp đồng: <i>cứ ký đi, có 21 ngày cân nhắc, không thích thì trả lại</i>. Câu đó dựa vào <b>Điều 35 Luật Kinh doanh bảo hiểm số 08/2022/QH15</b>, hiệu lực từ 01/01/2023. Điều luật có thật, quyền có thật. Nhưng điều luật chỉ dài một đoạn, và trong một đoạn đó có hai chỗ hay bị nói tắt thành sai: nó chỉ áp dụng cho hợp đồng <b>thời hạn trên 01 năm</b>, và nó <b>không nói</b> bạn được hoàn lại toàn bộ phí. Bài này trích nguyên văn để bạn tự đối chiếu, không thay cho tư vấn pháp lý cho trường hợp cụ thể.",

 "bang": [
   {"ten": "Điều 35, trích nguyên văn toàn bộ",
    "kiem_chung": "chinh-thuc",
    "nguon": "Luật Kinh doanh bảo hiểm số 08/2022/QH15, Điều 35 &mdash; <i>Thời gian cân nhắc tham gia bảo hiểm</i>, hiệu lực từ 01/01/2023",
    "cot": ["Điều", "Nguyên văn"],
    "hang": [
      ["35", "Đối với các hợp đồng bảo hiểm có thời hạn trên 01 năm, trong thời hạn 21 ngày kể từ ngày nhận được hợp đồng bảo hiểm, bên mua bảo hiểm có quyền từ chối tiếp tục tham gia bảo hiểm. Trường hợp bên mua bảo hiểm từ chối tiếp tục tham gia bảo hiểm thì hợp đồng bảo hiểm sẽ bị hủy bỏ, bên mua bảo hiểm được hoàn lại phí bảo hiểm đã đóng sau khi trừ đi chi phí hợp lý (nếu có) theo thỏa thuận trong hợp đồng bảo hiểm; doanh nghiệp bảo hiểm không phải bồi thường, trả tiền bảo hiểm khi xảy ra sự kiện bảo hiểm."],
    ]},
   {"ten": "Bốn câu hay nói tắt, và điều luật thật sự viết gì",
    "kiem_chung": "chinh-thuc",
    "nguon": "Đối chiếu với nguyên văn Điều 35 trích ở bảng trên",
    "cot": ["Cách nói thường gặp", "Điều 35 viết gì"],
    "hang": [
      ["Hợp đồng bảo hiểm nào cũng có 21 ngày cân nhắc", "Điều luật mở đầu bằng <i>đối với các hợp đồng bảo hiểm có thời hạn trên 01 năm</i>. Hợp đồng một năm hoặc ngắn hơn không nằm trong phạm vi điều này."],
      ["Trong 21 ngày trả lại thì được hoàn 100% phí", "Điều luật viết <i>được hoàn lại phí bảo hiểm đã đóng sau khi trừ đi chi phí hợp lý (nếu có) theo thỏa thuận trong hợp đồng bảo hiểm</i>. Có trừ hay không, trừ bao nhiêu, là chuyện của hợp đồng cụ thể."],
      ["21 ngày tính từ ngày ký", "Điều luật viết <i>kể từ ngày nhận được hợp đồng bảo hiểm</i>. Ngày ký đơn yêu cầu và ngày nhận bộ hợp đồng thường không trùng nhau."],
      ["Trả lại rồi thì coi như chưa từng có gì", "Điều luật ghi rõ doanh nghiệp <i>không phải bồi thường, trả tiền bảo hiểm khi xảy ra sự kiện bảo hiểm</i>. Huỷ là hết bảo vệ, kể cả với chuyện xảy ra sau đó."],
    ]},
   {"ten": "Bốn chỗ Điều 35 để trống",
    "kiem_chung": "chinh-thuc",
    "nguon": "Đọc toàn văn Điều 35. Những nội dung dưới đây không xuất hiện trong điều luật; chúng có thể nằm ở văn bản khác hoặc ở hợp đồng, chúng tôi không kết luận thay.",
    "cot": ["Câu hỏi", "Điều 35 có trả lời không"],
    "hang": [
      ["Chi phí hợp lý gồm những khoản gì", "Không. Điều luật chỉ viết <i>chi phí hợp lý (nếu có) theo thỏa thuận trong hợp đồng bảo hiểm</i> và không định nghĩa."],
      ["Từ chối bằng cách nào, có mẫu đơn không, nộp ở đâu", "Không quy định thủ tục."],
      ["Doanh nghiệp phải hoàn tiền trong bao nhiêu ngày", "Không quy định thời hạn hoàn."],
      ["Ngày nhận được hợp đồng chứng minh bằng gì", "Không quy định cách xác định hay chứng minh."],
    ]},
 ],

 "y_chinh": [
   ("Điều 35 là một đoạn liền, không chia khoản",
    "Đây là chi tiết nhỏ nhưng có ích khi bạn đọc tài liệu do người khác viết. Nhiều bài trên mạng dẫn <i>Điều 35 khoản 1</i> hoặc <i>khoản 2</i>. Trong Luật Kinh doanh bảo hiểm số 08/2022/QH15, Điều 35 chỉ có một đoạn văn, không đánh số khoản. Gặp trích dẫn có số khoản thì nên kiểm tra lại nguồn."),
   ("Chữ quan trọng nhất là trên 01 năm",
    "Điều 35 không nói mọi hợp đồng bảo hiểm. Nó nói hợp đồng có thời hạn trên 01 năm. Bảo hiểm nhân thọ và các sản phẩm dài hạn nằm trong phạm vi này. Các hợp đồng ngắn hạn thì không, và nếu sản phẩm ngắn hạn nào có chính sách đổi ý thì đó là chính sách của doanh nghiệp, không phải quyền do Điều 35 trao. Hai thứ đó khác nhau ở chỗ: quyền theo luật thì doanh nghiệp không được bỏ, còn chính sách thì doanh nghiệp đặt ra và sửa được."),
   ("Chữ quan trọng thứ hai là sau khi trừ đi chi phí hợp lý",
    "Nhiều người nhớ 21 ngày mà quên vế sau. Luật cho phép trừ, nhưng buộc phần trừ đó phải <i>theo thỏa thuận trong hợp đồng bảo hiểm</i>. Nghĩa là nếu hợp đồng không thoả thuận khoản trừ nào thì không có căn cứ để trừ, còn nếu có thì nó phải nằm trong hợp đồng chứ không phải nói miệng lúc bạn gọi lên tổng đài. Trước khi ký, đây là câu đáng hỏi: <i>nếu tôi dùng quyền 21 ngày thì hợp đồng ghi trừ những khoản nào, ở trang mấy</i>."),
   ("21 ngày đếm từ ngày nhận hợp đồng, không phải ngày ký",
    "Điều luật viết <i>kể từ ngày nhận được hợp đồng bảo hiểm</i>. Trong thực tế, ngày bạn ký hồ sơ yêu cầu, ngày doanh nghiệp phát hành, và ngày bộ hợp đồng đến tay bạn là ba mốc khác nhau. Luật không nói chứng minh ngày nhận bằng cách nào, nên việc giữ lại bằng chứng nhận bàn giao là việc của bạn: biên bản giao nhận có chữ ký, tin nhắn hoặc email báo giao, phiếu chuyển phát. Không có gì trong tay thì lúc tranh luận sẽ khó."),
   ("Huỷ trong 21 ngày là mất bảo vệ ngay, không có vùng đệm",
    "Vế cuối của điều luật nói rõ doanh nghiệp không phải bồi thường, trả tiền bảo hiểm khi xảy ra sự kiện bảo hiểm. Nghĩa là nếu bạn từ chối tiếp tục tham gia rồi mà sau đó có chuyện, bạn không có gì. Điều này nghe hiển nhiên nhưng đáng nói, vì có người nghĩ tiền đã đóng thì ít nhất còn được bảo vệ hết tháng đó."),
   ("Nên làm gì trong 21 ngày đó",
    "Đọc phần điều khoản loại trừ và phần thời gian chờ trước, vì hai phần này quyết định lúc có chuyện. Đối chiếu bảng minh hoạ quyền lợi với điều khoản: nếu có chỗ nào bảng nói mà điều khoản không nói thì hỏi. Kiểm tra lại thông tin sức khoẻ đã kê khai xem có sót gì không, vì đây vẫn là khoảng thời gian sửa được dễ nhất. Và giữ lại bằng chứng ngày nhận hợp đồng."),
   ("Từ chối thì gửi cho ai và giữ gì",
    "Luật không quy định thủ tục nên cách an toàn là làm bằng văn bản và giữ dấu vết: gửi văn bản đề nghị tới doanh nghiệp qua kênh chính thức, lưu lại xác nhận đã gửi và đã nhận, ghi rõ ngày. Nếu doanh nghiệp có mẫu riêng thì dùng mẫu của họ nhưng vẫn giữ bản sao. Đây không phải yêu cầu của luật, mà là cách tự bảo vệ khi luật để trống."),
 ],

 "khong_ro": [
   "Chi phí hợp lý cụ thể là bao nhiêu. Điều 35 giao cho hợp đồng, mà mỗi hợp đồng một khác, nên không có con số chung để đăng.",
   "Thời hạn doanh nghiệp phải hoàn tiền. Điều 35 không quy định, và chúng tôi chưa đọc hết các văn bản hướng dẫn để khẳng định có hay không quy định ở nơi khác.",
   "Cách xác định ngày nhận được hợp đồng khi giao nhận bằng phương thức điện tử. Điều 35 không nói.",
   "Điều gì xảy ra nếu bên mua từ chối sau ngày thứ 21. Điều 35 chỉ nói về khoảng 21 ngày, không nói phần sau đó.",
   "Quy định tương ứng trong các văn bản dưới luật. Bài này chỉ đọc Điều 35 của Luật số 08/2022/QH15.",
 ],

 "faq": [
   ("Thời gian cân nhắc 21 ngày được quy định ở đâu?",
    "Điều 35 Luật Kinh doanh bảo hiểm số 08/2022/QH15, tên điều là <i>Thời gian cân nhắc tham gia bảo hiểm</i>, hiệu lực từ 01/01/2023. Điều này chỉ có một đoạn văn, không chia khoản."),
   ("Hợp đồng nào cũng có 21 ngày cân nhắc phải không?",
    "Không. Điều 35 mở đầu bằng <i>đối với các hợp đồng bảo hiểm có thời hạn trên 01 năm</i>. Hợp đồng thời hạn một năm hoặc ngắn hơn không thuộc phạm vi điều này."),
   ("Trả lại hợp đồng trong 21 ngày có được hoàn đủ tiền không?",
    "Điều luật viết được hoàn lại phí bảo hiểm đã đóng <i>sau khi trừ đi chi phí hợp lý (nếu có) theo thỏa thuận trong hợp đồng bảo hiểm</i>. Nghĩa là có thể bị trừ, và phần trừ phải nằm trong hợp đồng. Nên hỏi trước khi ký rằng hợp đồng ghi khoản trừ nào và ở trang nào."),
   ("21 ngày tính từ lúc nào?",
    "Từ ngày nhận được hợp đồng bảo hiểm, theo đúng chữ trong điều luật, không phải từ ngày ký hồ sơ yêu cầu. Luật không quy định cách chứng minh ngày nhận, nên bạn nên giữ biên bản giao nhận, tin nhắn hoặc email báo giao."),
   ("Từ chối trong 21 ngày rồi mà xảy ra chuyện thì sao?",
    "Điều 35 ghi rõ doanh nghiệp bảo hiểm không phải bồi thường, trả tiền bảo hiểm khi xảy ra sự kiện bảo hiểm. Hợp đồng đã huỷ thì không còn bảo vệ."),
   ("Muốn từ chối thì làm thủ tục gì?",
    "Điều 35 không quy định thủ tục, mẫu đơn hay nơi nộp. Cách an toàn là gửi văn bản qua kênh chính thức của doanh nghiệp, ghi rõ ngày, và giữ lại bằng chứng đã gửi cùng bản sao. Nếu doanh nghiệp có quy trình riêng thì làm theo nhưng vẫn lưu giấy tờ."),
 ],
 "lien_quan": ["dieu-khoan-loai-tru", "ly-do-ho-so-bi-tu-choi-boi-thuong"],
},

# =====================================================================
{
 "slug": "gia-mot-ngay-giuong-11-benh-vien",
 "cum": "D",
 "ngay_dang": "2026-09-09",
 "tag": "Viện phí",
 "doc": "8 phút đọc",
 "title": "Giá một ngày giường ở 11 bệnh viện: từ 203.600đ tới 36 triệu, và chênh lệch trong cùng một toà nhà",
 "h1": "Giá một ngày giường ở 11 bệnh viện",
 "desc": "Chúng tôi gom bảng giá giường của 11 bệnh viện đã đọc trực tiếp. Mức thấp nhất 203.600đ, cao nhất 36.000.000đ một ngày. Nhưng con số đáng chú ý hơn là chênh lệch bên trong một bệnh viện: có nơi gấp gần 20 lần.",
 "tom_tat": "Khi ước chi phí nằm viện, người ta hay nhìn giá ca mổ hoặc giá gói. Khoản làm vỡ dự tính thường là tiền giường, vì nó nhân với số đêm. Chúng tôi lấy bảng giá giường của <b>11 bệnh viện</b> đã đọc trực tiếp và đăng thành bài riêng, xếp lại thành một bảng. Mức thấp nhất là <b>203.600đ</b> một ngày, cao nhất là <b>36.000.000đ</b> một ngày. Hai con số đó không so sánh trực tiếp được với nhau, và bài này sẽ nói rõ vì sao. Thứ so sánh được, và đáng chú ý hơn, là chênh lệch bên trong cùng một bệnh viện.",

 "bang": [
   {"ten": "Mức giường thấp nhất và cao nhất mỗi bệnh viện công bố",
    "kiem_chung": "chinh-thuc",
    "nguon": "Tổng hợp từ bảng giá trên trang chính thức của từng bệnh viện, chúng tôi đã đọc trực tiếp và đăng thành bài riêng. Mỗi bài riêng có URL và ngày công bố cụ thể. 11 bệnh viện nhưng 12 dòng, vì Xuyên Á công bố hai bảng riêng cho hai cơ sở.",
    "cot": ["Bệnh viện", "Mức thấp nhất", "Mức cao nhất", "Bảng giá công bố"],
    "hang": [
      ["Từ Dũ (công, TP.HCM)", "<b>203.600đ</b> &mdash; ngày giường điều trị nội trú", "4.000.000đ &mdash; phòng hậu sản dịch vụ", "các bản công bố 2022&ndash;2023"],
      ["Nhân dân Gia Định (công, TP.HCM)", "232.900đ &mdash; nội khoa loại 3", "928.100đ &mdash; hồi sức tích cực", "Thông báo 586/TB-BVNDGĐ ngày 23/02/2026"],
      ["Phụ sản Hà Nội (công)", "280.000đ &mdash; khu thường", "<b>5.000.000đ</b> &mdash; khu dịch vụ B3, 1 giường", "đăng 20/08/2026"],
      ["Xuyên Á &mdash; cơ sở Củ Chi (tư, TP.HCM)", "320.000đ &mdash; phòng 10 giường khoa Sản", "1.700.000đ &mdash; phòng Tiêu chuẩn A", "Bảng giá dịch vụ kỹ thuật 2025"],
      ["Xuyên Á &mdash; cơ sở Tây Ninh (tư)", "460.000đ &mdash; phòng 6 giường", "1.100.000đ &mdash; phòng 1 giường", "Công văn 206/CV-BVXATN/2025 ngày 22/05/2025"],
      ["Phụ sản &ndash; Nhi Đà Nẵng (công)", "650.000đ &mdash; giường Yêu cầu, 4 giường/phòng", "2.000.000đ &mdash; giường Yêu cầu Quốc tế, 2 giường/phòng", "Quyết định 296/QĐ-BVPSNĐN ngày 19/09/2025"],
      ["Phụ sản Trung ương &mdash; Cơ sở 2 (công, Hà Nội)", "800.000đ &mdash; giường loại 5", "1.500.000đ &mdash; giường loại 3", "Quyết định 2312/QĐ-PSTW ngày 30/07/2026"],
      ["Phụ sản MêKông (tư, TP.HCM)", "từ 1.600.000đ &mdash; phòng Đôi", "từ 3.200.000đ &mdash; phòng VIP", "công bố 01/09/2022, bệnh viện ghi giá có thể đã thay đổi"],
      ["Quốc tế City (tư, TP.HCM)", "1.650.000đ &mdash; phòng 2 giường", "3.300.000đ &mdash; phòng chăm sóc đặc biệt", "sửa đổi lần cuối 24/06/2026"],
      ["Quốc tế Hạnh Phúc (tư, TP.HCM)", "2.800.000đ &mdash; hạng Tiêu Chuẩn", "6.800.000đ &mdash; VIP Suite", "tờ thông tin gói sinh, file không ghi ngày hiệu lực"],
      ["Hùng Vương (công, TP.HCM)", "3.000.000đ &mdash; phòng 1 giường tiêu chuẩn", "3.700.000đ &mdash; phòng nằm sau mổ", "Hỏi&ndash;Đáp 09/04/2024 và 23/08/2023"],
      ["Việt Pháp Hà Nội (quốc tế)", "9.900.000đ &mdash; phòng chung nhi và hậu phẫu", "<b>36.000.000đ</b> &mdash; hồi sức tích cực", "cập nhật 01/04/2026, giá đã gồm phí bác sĩ"],
    ]},
   {"ten": "Chênh lệch bên trong cùng một bệnh viện",
    "kiem_chung": "chinh-thuc",
    "nguon": "Tính từ chính hai đầu bảng giá của mỗi bệnh viện ở bảng trên. Số lần là phép chia đơn giản, chúng tôi làm tròn.",
    "cot": ["Bệnh viện", "Thấp nhất", "Cao nhất", "Chênh"],
    "hang": [
      ["Từ Dũ", "203.600đ", "4.000.000đ", "<b>gần 20 lần</b>"],
      ["Phụ sản Hà Nội", "280.000đ", "5.000.000đ", "<b>gần 18 lần</b>"],
      ["Xuyên Á &mdash; Củ Chi", "320.000đ", "1.700.000đ", "hơn 5 lần"],
      ["Nhân dân Gia Định", "232.900đ", "928.100đ", "gần 4 lần"],
      ["Việt Pháp Hà Nội", "9.900.000đ", "36.000.000đ", "khoảng 3,6 lần"],
      ["Phụ sản &ndash; Nhi Đà Nẵng", "650.000đ", "2.000.000đ", "hơn 3 lần"],
      ["Quốc tế Hạnh Phúc", "2.800.000đ", "6.800.000đ", "gần 2,5 lần"],
      ["Quốc tế City", "1.650.000đ", "3.300.000đ", "đúng 2 lần"],
      ["Phụ sản MêKông", "1.600.000đ", "3.200.000đ", "đúng 2 lần"],
      ["Phụ sản Trung ương &mdash; Cơ sở 2", "800.000đ", "1.500.000đ", "gần 2 lần"],
    ]},
   {"ten": "Số giường trong phòng không quyết định giá",
    "kiem_chung": "chinh-thuc",
    "nguon": "Các dòng dưới đây nằm trong cùng một bảng giá của cùng một bệnh viện, trích nguyên văn tên loại giường.",
    "cot": ["Bệnh viện", "Dòng trong bảng giá", "Giá mỗi ngày"],
    "hang": [
      ["Phụ sản &ndash; Nhi Đà Nẵng", "Giường Yêu cầu mẹ và trẻ (Loại 4 giường/phòng)", "1.500.000đ"],
      ["Phụ sản &ndash; Nhi Đà Nẵng", "Giường Yêu cầu Chất lượng cao (Loại 2 giường/phòng)", "1.200.000đ"],
      ["Phụ sản Hà Nội", "Khu dịch vụ &mdash; 3 giường, công trình phụ, bộ sofa (khu B3)", "3.000.000đ"],
      ["Phụ sản Hà Nội", "Khu dịch vụ &mdash; 1 giường, vệ sinh khép kín, bàn ghế (khu D)", "3.000.000đ"],
      ["Phụ sản Hà Nội", "Khu dịch vụ &mdash; 6 giường, vệ sinh khép kín (khu B4)", "1.500.000đ"],
      ["Phụ sản Hà Nội", "Khu dịch vụ &mdash; 2 đến 3 giường, vệ sinh chung (khu D)", "1.500.000đ"],
    ]},
 ],

 "y_chinh": [
   ("Vì sao tiền giường mới là khoản làm vỡ dự tính",
    "Giá ca sinh hay ca mổ là con số trả một lần. Tiền giường nhân với số đêm. Ở Bệnh viện Phụ sản Hà Nội, bốn đêm khu thường mức thấp nhất là 1.120.000đ, bốn đêm ở mức cao nhất là 20.000.000đ. Chênh 18.880.000đ chỉ vì chọn phòng, trong khi ca sinh vẫn là ca sinh đó. Đây là một trong ít khoản của hoá đơn mà bạn chọn được, và cũng là khoản dễ bị quyết định vội lúc đang chuyển dạ."),
   ("203.600đ và 36.000.000đ không phải hai giá của cùng một thứ",
    "Mức 203.600đ ở Từ Dũ là ngày giường điều trị nội trú theo khung BHYT, phần lớn do quỹ chi trả. Mức 36.000.000đ ở Việt Pháp Hà Nội là hồi sức tích cực, và bệnh viện ghi rõ giá đã bao gồm tiền giường cùng phí bác sĩ, chưa gồm thuốc, xét nghiệm và chẩn đoán hình ảnh. Một bên là dòng giá hành chính, một bên là giá trọn phần chăm sóc. Đặt cạnh nhau để thấy dải rộng đến đâu thì được, nhưng nói bệnh viện này đắt gấp bao nhiêu lần bệnh viện kia thì không đúng."),
   ("Chênh lệch trong cùng một bệnh viện công lớn hơn nhiều người nghĩ",
    "Từ Dũ chênh gần 20 lần, Phụ sản Hà Nội gần 18 lần. Cùng một bệnh viện, cùng một ca sinh, cùng đội ngũ. Khoảng cách đó nằm ở hạng phòng chứ không nằm ở chuyên môn. Với người có BHYT và không cần phòng riêng, đây là chỗ tiết kiệm được nhiều nhất mà không ảnh hưởng tới phần y tế."),
   ("Số giường trong phòng không quyết định giá",
    "Ở Phụ sản &ndash; Nhi Đà Nẵng, giường mẹ và trẻ loại 4 giường một phòng có giá 1.500.000đ, cao hơn giường Chất lượng cao loại 2 giường một phòng giá 1.200.000đ. Ở Phụ sản Hà Nội, phòng 3 giường khu B3 và phòng 1 giường khu D cùng 3.000.000đ; phòng 6 giường khu B4 và phòng 2 đến 3 giường khu D cùng 1.500.000đ. Cái quyết định là tên hạng và tiện nghi kèm theo, không phải bạn nằm chung với mấy người. Vì vậy khi hỏi giá, hãy hỏi đúng tên hạng giường như trong bảng, đừng hỏi <i>phòng hai giường bao nhiêu</i>."),
   ("Ngày của bảng giá lệch nhau tới bốn năm",
    "Bảng mới nhất trong nhóm này là Quyết định 2312/QĐ-PSTW ngày 30/07/2026 của Phụ sản Trung ương và bảng Phụ sản Hà Nội đăng 20/08/2026. Bảng cũ nhất là Phụ sản MêKông công bố 01/09/2022, và chính bệnh viện ghi chú rằng giá có thể đã thay đổi, đề nghị gọi hỏi. Bảng của Hạnh Phúc thì không ghi ngày hiệu lực. Khi đọc bất kỳ bảng giá giường nào, xem ngày trước khi xem số."),
   ("Từ 01/01/2025 mỗi bệnh viện tự định giá phần theo yêu cầu",
    "Thông tư 22/2023/TT-BYT hết hiệu lực ngày 31/12/2024. Từ 01/01/2025, giá dịch vụ theo yêu cầu do cơ sở khám chữa bệnh tự xây dựng theo Thông tư 21/2024/TT-BYT. Đó là lý do các bảng giường của bệnh viện công giờ nằm trong quyết định riêng của từng bệnh viện, và vì sao hai bệnh viện công cùng hạng có thể ra hai bộ số khác nhau. Không có một bảng giá giường chung để tra."),
   ("Bốn câu nên hỏi trước khi chọn phòng",
    "Một: hạng phòng này tên chính xác là gì trong bảng giá, bao nhiêu một ngày. Hai: dự kiến nằm mấy đêm, và cách tính ngày ra viện thế nào. Ba: BHYT có chi trả phần nào của tiền giường không, hay tự trả toàn bộ. Bốn: nếu bé phải nằm theo dõi riêng thì tính thêm giường nào và bao nhiêu."),
 ],

 "khong_ro": [
   "Giá giường của các bệnh viện không công bố bảng riêng. Trong nhóm bài của chúng tôi, một số nơi chỉ đưa giá gói đã gồm phòng mà không tách đơn giá ngày giường.",
   "Mỗi mức giá đã bao gồm những gì. Chỉ Việt Pháp Hà Nội nói rõ giá gồm tiền giường và phí bác sĩ. Phần lớn bảng còn lại chỉ có tên phòng và số tiền.",
   "Bảng nào còn đúng tính đến hôm nay. Chúng tôi ghi ngày công bố của từng bảng, nhưng bệnh viện có thể đã sửa mà không đổi ngày trên trang.",
   "Phần BHYT chi trả trong tiền giường ở từng bệnh viện. Đây phụ thuộc tuyến, mức hưởng và loại giường, không có con số chung.",
   "Giá giường tại các cơ sở khác của cùng một bệnh viện. Nhiều nơi có nhiều cơ sở nhưng chỉ đăng bảng của một cơ sở.",
 ],

 "faq": [
   ("Một ngày giường bệnh viện hết bao nhiêu tiền?",
    "Tuỳ bệnh viện và hạng phòng, dải rất rộng. Trong 11 bệnh viện chúng tôi đã đọc bảng giá trực tiếp, mức thấp nhất là 203.600đ một ngày (ngày giường điều trị nội trú ở Từ Dũ) và mức cao nhất là 36.000.000đ một ngày (hồi sức tích cực ở Việt Pháp Hà Nội, giá đã gồm phí bác sĩ). Hai con số này không cùng loại nên không so trực tiếp được."),
   ("Vì sao cùng một bệnh viện mà giá giường chênh nhau nhiều thế?",
    "Vì bảng giá có cả giường theo khung BHYT lẫn giường dịch vụ hoặc theo yêu cầu. Ở Từ Dũ chênh gần 20 lần, ở Phụ sản Hà Nội gần 18 lần. Phần chênh nằm ở hạng phòng và tiện nghi, không nằm ở phần điều trị."),
   ("Phòng ít giường hơn thì đắt hơn phải không?",
    "Không hẳn. Ở Phụ sản &ndash; Nhi Đà Nẵng, giường mẹ và trẻ loại 4 giường một phòng 1.500.000đ đắt hơn giường Chất lượng cao loại 2 giường một phòng 1.200.000đ. Ở Phụ sản Hà Nội, phòng 3 giường và phòng 1 giường có hai dòng cùng giá 3.000.000đ. Nên hỏi theo đúng tên hạng giường trong bảng."),
   ("BHYT có trả tiền phòng dịch vụ không?",
    "Phần vượt khung giá BHYT thì không. Ví dụ Từ Dũ ghi rõ phòng hậu sản dịch vụ là khoản tự trả 100%, trong khi ngày giường điều trị nội trú nằm trong phạm vi BHYT. Mức hưởng cụ thể còn tuỳ tuyến và loại thẻ, nên hỏi phòng tài chính bệnh viện trước khi chọn phòng."),
   ("Vì sao giá giường giữa các bệnh viện công lại khác nhau?",
    "Thông tư 22/2023/TT-BYT hết hiệu lực ngày 31/12/2024. Từ 01/01/2025, giá dịch vụ theo yêu cầu do từng cơ sở tự xây dựng theo Thông tư 21/2024/TT-BYT. Vì vậy mỗi bệnh viện công ra một quyết định giá riêng, và không còn một bảng chung để tra."),
   ("Nên hỏi gì để không bị bất ngờ tiền phòng?",
    "Hỏi tên chính xác của hạng phòng và đơn giá một ngày, hỏi dự kiến nằm mấy đêm và cách tính ngày ra viện, hỏi BHYT có trả phần nào không, và hỏi nếu bé nằm theo dõi riêng thì tính thêm giường nào. Bốn câu này nên hỏi trước khi nhập viện, không phải lúc đang chuyển dạ."),
 ],
 "lien_quan": ["bhyt-khong-chi-tra-nhung-gi", "bao-lanh-vien-phi-hoat-dong-the-nao"],
},

]