# -*- coding: utf-8 -*-
"""
Du lieu chi phi sinh con theo tung benh vien.

NGUYEN TAC BIEN TAP - doc truoc khi sua file nay:
  1. Moi con so PHAI co nguon va ngay cong bo. Khong co nguon -> khong dang.
  2. Khong bao gio ghi "gia 2026" neu benh vien chua cong bo bang gia 2026.
  3. Neu benh vien khong cong bo gia (vi du Vinmec) -> noi thang la khong cong bo,
     va ghi ro so tham khao lay tu dau. Khong bia.
  4. Truong "kiem_chung" cua moi bang: "chinh-thuc" | "thu-cap" | "chua-xac-minh"
"""

CAP_NHAT = "01/09/2026"   # ngay ra soat noi dung gan nhat

BV_DATA = [

# =====================================================================
{
 "slug": "tu-du",
 "ten": "Bệnh viện Từ Dũ",
 "tinh": "TP. Hồ Chí Minh",
 "loai": "Bệnh viện công tuyến cuối",
 "calc_key": "tudu",
 "nguon_ngay": "16/09/2025",
 "nguon_nhan": "Bản hướng dẫn chi phí bệnh viện công bố gần nhất mà chúng tôi truy cập được là <b>ngày 16/09/2025</b>; một số dòng giá chi tiết là bản 2022&ndash;2023 và được ghi rõ trong từng bảng. Từ Dũ chưa công bố bảng giá 2026.",
 "nguon_url": "https://www.tudu.com.vn/vn/huong-dan-dich-vu/dich-vu-sanh-mo/huong-dan-di-sanh-tai-benh-vien-tu-du/",
 "title": "Chi phí sinh con ở Bệnh viện Từ Dũ: bảng giá bệnh viện công bố và phần BHYT không trả",
 "desc": "Sinh thường và sinh mổ ở Từ Dũ hết bao nhiêu, tiền phòng dịch vụ mỗi ngày, giá gây tê ngoài màng cứng, và ba khoản BHYT không chi trả. Số liệu dẫn nguồn từ bệnh viện, ghi rõ ngày công bố.",
 "tom_tat": "Sinh thường không dịch vụ ở Từ Dũ khoảng <b>3&ndash;5 triệu</b>, có dịch vụ <b>10&ndash;15 triệu</b>. Sinh mổ không dịch vụ <b>7&ndash;10 triệu</b>, có dịch vụ <b>18&ndash;20 triệu</b>. Đó là tổng hoá đơn trước khi trừ bảo hiểm y tế. Phần khiến ngân sách vỡ không nằm ở đây &mdash; mà ở tiền phòng dịch vụ, khoản BHYT không trả một đồng nào.",

 "bang": [
   {"ten": "Chi phí sinh thường",
    "kiem_chung": "chinh-thuc",
    "nguon": "tudu.com.vn, công bố 16/09/2025",
    "cot": ["Hình thức", "Tổng chi phí (chưa trừ BHYT)", "Số ngày nằm viện"],
    "hang": [
      ["Sanh <b>không</b> dịch vụ", "3.000.000 &ndash; 5.000.000đ", "khoảng 3 ngày"],
      ["Sanh <b>có</b> dịch vụ", "10.000.000 &ndash; 15.000.000đ", "khoảng 3 ngày"],
      ["Tạm ứng khi nhập viện (có dịch vụ)", "từ 10.000.000đ", "&mdash;"],
      ["Tạm ứng khi nhập viện (không dịch vụ)", "5.000.000đ", "&mdash;"],
    ]},
   {"ten": "Chi phí sinh mổ",
    "kiem_chung": "chinh-thuc",
    "nguon": "tudu.com.vn, công bố 16/09/2025 (riêng tiền công mổ: bản 02/02/2023)",
    "cot": ["Hình thức", "Số tiền", "Ghi chú"],
    "hang": [
      ["Tổng, <b>không</b> dịch vụ", "7.000.000 &ndash; 10.000.000đ", "nằm viện khoảng 5 ngày"],
      ["Tổng, <b>có</b> dịch vụ", "18.000.000 &ndash; 20.000.000đ", "nằm viện khoảng 5 ngày"],
      ["Tiền công mổ lần đầu", "2.604.000đ", "số niêm yết bản 2023"],
      ["Tiền công mổ lần 2 trở lên", "3.376.200đ", "số niêm yết bản 2023"],
      ["Mổ dịch vụ theo yêu cầu", "4.000.000 &ndash; 4.500.000đ", "số niêm yết bản 2023"],
      ["Phụ phí mổ gia đình", "cộng thêm 1.000.000đ", "số niêm yết bản 2023"],
    ]},
   {"ten": "Tiền phòng và các khoản cộng thêm",
    "kiem_chung": "chinh-thuc",
    "nguon": "tudu.com.vn, các bản công bố 2022&ndash;2023",
    "cot": ["Khoản mục", "Giá", "BHYT có trả không"],
    "hang": [
      ["Phòng hậu sản dịch vụ (khu N, M, H, B)", "600.000 &ndash; 4.000.000đ / ngày", "<b>Không</b> &mdash; tự trả 100%"],
      ["Ngày giường điều trị nội trú", "203.600đ / ngày", "Có, trong phạm vi BHYT"],
      ["Giảm đau sản khoa (gây tê ngoài màng cứng)", "1.849.000đ", "Tuỳ chỉ định"],
      ["Chọn bác sĩ đỡ sinh", "<b>0đ &mdash; không thu thêm phí</b>", "Không phát sinh"],
      ["Bộ khăn phẫu thuật (dùng 1 lần)", "586.000đ", "Không"],
    ]},
 ],

 "khong_cong_bo": [
   "<b>Giá NICU / chăm sóc đặc biệt sơ sinh hiện hành.</b> Bảng giá duy nhất Từ Dũ từng công bố là bản năm 2015 &mdash; đã hơn 10 năm, chắc chắn không còn đúng. Chúng tôi không đăng lại con số đó. Điểm quan trọng vẫn còn giá trị: bệnh viện xác nhận các khoản điều trị cho trẻ sơ sinh <b>được BHYT thanh toán</b> khi nộp đủ giấy tờ; gia đình chủ yếu tự trả sữa, tã và thuốc Surfactant từ lọ thứ ba trở đi.",
   "<b>Giá sàng lọc sơ sinh mở rộng.</b> Không tìm thấy công bố công khai.",
   "<b>Bảng giá từng dòng theo loại phòng.</b> Từ Dũ đăng dưới dạng file ảnh trên website, không tra cứu được bằng máy. Muốn biết chính xác phòng nào bao nhiêu, phải hỏi trực tiếp lúc nhập viện.",
 ],

 "luu_y": [
   ("Không cần đăng ký sinh trước",
    "Bệnh viện nói rõ: tất cả trường hợp nhập viện sinh tại Từ Dũ đều không cần đăng ký trước. Bạn chọn hình thức dịch vụ ngay lúc làm thủ tục nhập viện, tại cổng số 1 &mdash; 284 Cống Quỳnh."),
   ("Chọn bác sĩ không mất thêm tiền",
    "Rất nhiều người tưởng phải &ldquo;lót tay&rdquo; để được bác sĩ mình muốn. Từ Dũ công bố rõ: khi đã đăng ký sinh dịch vụ, sản phụ được quyền yêu cầu bác sĩ mà không thu thêm phí."),
   ("Có BHYT thì được tính như đúng tuyến, kể cả không có giấy chuyển tuyến",
    "Đây là thay đổi nhiều người chưa cập nhật. Sản phụ có thẻ BHYT sinh tại Từ Dũ được hưởng đúng tuyến 100% chi phí nội trú trong phạm vi BHYT, kể cả khi thẻ đăng ký ở tỉnh khác và không có giấy chuyển tuyến."),
   ("Có cả BHYT và bảo hiểm dịch vụ thì chỉ được chọn một",
    "Điểm này hay bị hiểu sai nhất. Tại bệnh viện, bạn chỉ được chọn một loại để hưởng &mdash; không cộng dồn. Loại còn lại phải tự làm hồ sơ đòi bồi thường sau."),
   ("Bệnh viện phát sẵn túi tiện ích",
    "Chăn, khăn, quần lót giấy, băng vệ sinh, bàn chải, kem đánh răng, bình nước, hộp trữ cuống rốn đều có sẵn. Mẹ không cần mang vác nhiều như các danh sách trên mạng khuyên."),
 ],

 "faq": [
   ("Sinh ở Bệnh viện Từ Dũ hết bao nhiêu tiền?",
    "Theo hướng dẫn bệnh viện công bố ngày 16/09/2025: sinh thường không dịch vụ khoảng 3&ndash;5 triệu, có dịch vụ 10&ndash;15 triệu, nằm viện khoảng 3 ngày. Sinh mổ không dịch vụ 7&ndash;10 triệu, có dịch vụ 18&ndash;20 triệu, nằm viện khoảng 5 ngày. Đây là tổng chi phí trước khi trừ bảo hiểm y tế."),
   ("Tiền phòng dịch vụ ở Từ Dũ bao nhiêu một ngày?",
    "Phòng hậu sản dịch vụ dao động 600.000 đến 4.000.000đ mỗi ngày tuỳ khu và loại phòng. Đây là khoản bảo hiểm y tế <b>không chi trả</b> đồng nào, và cũng là khoản khiến ngân sách vỡ nhiều nhất vì nhân với số ngày nằm viện."),
   ("Có bảo hiểm y tế thì sinh ở Từ Dũ được hưởng bao nhiêu?",
    "Sản phụ có thẻ BHYT được tính hưởng đúng tuyến 100% chi phí nội trú trong phạm vi BHYT, kể cả khi không có giấy chuyển tuyến. Nhưng phần vượt phạm vi BHYT &mdash; đặc biệt là tiền phòng dịch vụ &mdash; vẫn phải tự thanh toán toàn bộ."),
   ("Đẻ không đau ở Từ Dũ giá bao nhiêu?",
    "Bệnh viện niêm yết giảm đau sản khoa (gây tê ngoài màng cứng) là 1.849.000đ, theo bản công bố ngày 29/08/2022. Nên gọi xác nhận lại trước khi sinh vì đây là số của năm 2022."),
   ("Chọn bác sĩ đỡ sinh ở Từ Dũ có phải trả thêm tiền không?",
    "Không. Bệnh viện công bố rõ: khi đã đăng ký sinh dịch vụ, sản phụ được quyền chỉ định bác sĩ mà không thu thêm phí."),
   ("Có cần đăng ký sinh ở Từ Dũ trước không?",
    "Không cần. Bệnh viện xác nhận mọi trường hợp nhập viện sinh đều không cần đăng ký trước; chọn hình thức dịch vụ ngay khi làm thủ tục nhập viện. Tạm ứng từ 10 triệu nếu chọn dịch vụ, 5 triệu nếu không."),
   ("Nên chuẩn bị sẵn bao nhiêu tiền mặt khi đi sinh ở Từ Dũ?",
    "Tối thiểu bằng mức tạm ứng (5 hoặc 10 triệu). Nhưng nếu tính cả kịch bản chuyển từ sinh thường sang sinh mổ và nằm phòng dịch vụ thêm vài ngày, con số an toàn nên gấp đôi mức bạn dự tính ban đầu."),
 ],
},

# =====================================================================
{
 "slug": "hung-vuong",
 "ten": "Bệnh viện Hùng Vương",
 "tinh": "TP. Hồ Chí Minh",
 "loai": "Bệnh viện công tuyến cuối",
 "calc_key": "hungvuong",
 "nguon_ngay": "23/09/2025",
 "nguon_nhan": "Câu trả lời chính thức gần nhất của bệnh viện là <b>ngày 23/09/2025</b>. Hùng Vương phát hành bảng giá qua file Google Sheets và file này hiện khoá quyền truy cập, nên không ai tra cứu trước được.",
 "nguon_url": "https://bvhungvuong.vn/hoi-dap/goi-sinh-va-chi-phi-sinh-cua-benh-vien",
 "title": "Chi phí sinh con ở Bệnh viện Hùng Vương: tạm ứng bao nhiêu, tiền phòng bao nhiêu một ngày",
 "desc": "Hùng Vương không bán gói trọn gói, thanh toán theo thực tế. Mức tạm ứng sinh thường và sinh mổ, giá phòng một giường, chọn bác sĩ có mất phí không, và mức BHYT thực tế được hưởng.",
 "tom_tat": "Hùng Vương <b>không bán gói sinh trọn gói</b> &mdash; bệnh viện khẳng định chi phí thanh toán theo thực tế sử dụng từng trường hợp. Bạn đóng tạm ứng lúc nhập viện: <b>6&ndash;7 triệu</b> diện nhà nước, <b>10&ndash;18 triệu</b> diện dịch vụ. Dư thì hoàn lại, thiếu thì đóng thêm. Khoản đắt nhất và ít ai tính trước là tiền phòng một giường: <b>3&ndash;3,7 triệu mỗi ngày</b>.",

 "bang": [
   {"ten": "Mức tạm ứng khi nhập viện sinh",
    "kiem_chung": "chinh-thuc",
    "nguon": "bvhungvuong.vn, mục Hỏi&ndash;Đáp do bệnh viện trả lời, 15/06/2024 và 23/09/2025",
    "cot": ["Hình thức", "Tạm ứng", "Ghi chú"],
    "hang": [
      ["Sinh thường &mdash; diện nhà nước", "6.000.000 &ndash; 7.000.000đ", "quyết toán theo thực tế"],
      ["Sinh thường &mdash; diện dịch vụ", "10.000.000 &ndash; 18.000.000đ", "quyết toán theo thực tế"],
      ["Sinh mổ &mdash; diện dịch vụ", "10.000.000 &ndash; 18.000.000đ", "quyết toán theo thực tế"],
    ]},
   {"ten": "Tiền công mổ &mdash; con số niêm yết duy nhất bệnh viện công bố",
    "kiem_chung": "chinh-thuc",
    "nguon": "bvhungvuong.vn, Hỏi&ndash;Đáp 12/04/2024",
    "cot": ["Khoản mục", "Số tiền", "Ai trả"],
    "hang": [
      ["Tiền công mổ (trường hợp mổ lần 3)", "7.193.000đ", "tổng"],
      ["&mdash; phần BHYT chi trả", "3.102.000đ", "bảo hiểm y tế"],
      ["&mdash; phần gia đình tự trả", "khoảng 4.091.000đ", "<b>gia đình</b>"],
    ]},
   {"ten": "Tiền phòng và dịch vụ cộng thêm",
    "kiem_chung": "chinh-thuc",
    "nguon": "bvhungvuong.vn, Hỏi&ndash;Đáp 09/04/2024 và 23/08/2023",
    "cot": ["Khoản mục", "Giá", "Ghi chú"],
    "hang": [
      ["Phòng 1 giường tiêu chuẩn", "3.000.000 &ndash; 3.700.000đ / ngày", "khoản đắt nhất, BHYT không trả"],
      ["Phòng nằm sau mổ", "3.500.000 &ndash; 3.700.000đ / ngày", "nhân với 4&ndash;5 ngày"],
      ["Chọn bác sĩ mổ / đỡ sinh", "<b>0đ &mdash; không thu thêm phí</b>", "khi đã chọn sinh dịch vụ"],
      ["Massage thư giãn cho bé", "250.000đ", "dịch vụ tự chọn"],
      ["Cắt rốn kèm chụp hình", "500.000đ", "dịch vụ tự chọn"],
      ["Tắm sơ sinh", "30.000đ", "dịch vụ tự chọn"],
    ]},
   {"ten": "Khám thai dịch vụ",
    "kiem_chung": "chinh-thuc",
    "nguon": "bvhungvuong.vn, Hỏi&ndash;Đáp 09/07/2023",
    "cot": ["Loại khám", "Tạm ứng", "Ghi chú"],
    "hang": [
      ["Khám thai dịch vụ", "500.000 &ndash; 1.600.000đ", "trừ dần vào thẻ khám"],
      ["Khám thai chuyên gia", "1.500.000 &ndash; 3.000.000đ", "trừ dần vào thẻ khám"],
    ]},
 ],

 "khong_cong_bo": [
   "<b>Bảng giá viện phí đầy đủ.</b> Hùng Vương phát hành bảng giá qua file Google Sheets, và file này hiện <b>khoá quyền truy cập</b> với người ngoài. Nghĩa là không ai tra cứu trước được &mdash; phải gọi tổng đài (028) 3855 8532.",
   "<b>Giá NICU / chăm sóc đặc biệt sơ sinh.</b> Không có bất kỳ công bố nào. Chúng tôi <b>không mượn số của bệnh viện khác</b> để lấp chỗ trống này.",
   "<b>Số ngày nằm viện chuẩn.</b> Bệnh viện không công bố. Không suy từ Từ Dũ sang được.",
   "<b>Giá gói khám thai trọn gói.</b> Bệnh viện xác nhận có triển khai dịch vụ này tại Phòng khám Chuyên gia &mdash; nhưng trang giá không truy cập được.",
 ],

 "luu_y": [
   ("Không có gói trọn gói &mdash; đây là khác biệt lớn nhất so với bệnh viện tư",
    "Bệnh viện nói rõ ngày 23/09/2025: không áp dụng gói sinh trọn gói, chi phí thanh toán theo thực tế sử dụng mỗi trường hợp. Ưu điểm: không trả cho thứ mình không dùng. Nhược điểm: bạn không biết trước con số cuối cùng."),
   ("Thẻ BHYT ở tỉnh khác vẫn được hưởng như đúng tuyến",
    "Bệnh viện xác nhận (04/2024): nhập viện sinh thì dù thẻ đăng ký ở tỉnh khác vẫn hưởng như đúng tuyến, mức 80% trong danh mục BHYT, không cần giấy chuyển tuyến."),
   ("Đừng tin con số &ldquo;trái tuyến chỉ 48%&rdquo; còn trôi nổi trên mạng",
    "Đó là câu trả lời của bệnh viện từ năm 2019 và <b>đã bị chính bệnh viện thay thế</b> bằng hướng dẫn 2024 ở trên. Nhiều bài viết vẫn chép lại con số cũ này và làm người đọc tính sai ngân sách."),
   ("Sanh VIP và sanh gia đình khác nhau ở thời điểm người nhà được vào",
    "Phòng sanh VIP cho người nhà vào từ lúc nhập sanh. Box sanh gia đình chỉ cho vào sau khi đã chuyển lên khoa sanh. Nếu điều quan trọng với bạn là có chồng bên cạnh suốt quá trình, đây là điểm cần hỏi kỹ."),
   ("Không gây tê ngoài màng cứng thì vẫn phải chích tê tại chỗ",
    "Khi rạch và khâu tầng sinh môn, tê tại chỗ là bắt buộc. Đây không phải khoản tuỳ chọn."),
 ],

 "faq": [
   ("Sinh ở Bệnh viện Hùng Vương hết bao nhiêu tiền?",
    "Bệnh viện không bán gói trọn gói mà thu tạm ứng rồi quyết toán theo thực tế. Tạm ứng sinh thường diện nhà nước 6&ndash;7 triệu, diện dịch vụ 10&ndash;18 triệu; sinh mổ dịch vụ cũng 10&ndash;18 triệu. Dư được hoàn lại khi xuất viện."),
   ("Bệnh viện Hùng Vương có gói sinh trọn gói không?",
    "Không. Bệnh viện khẳng định ngày 23/09/2025 rằng không áp dụng gói sinh trọn gói, chi phí sẽ thanh toán theo thực tế sử dụng của mỗi trường hợp."),
   ("Tiền phòng một giường ở Hùng Vương bao nhiêu?",
    "Từ 3.000.000 đến 3.700.000đ mỗi ngày theo công bố tháng 4/2024. Đây là khoản đắt nhất trong hoá đơn nếu bạn nằm 4&ndash;5 ngày sau mổ, và bảo hiểm y tế không chi trả phần này."),
   ("Thẻ BHYT ở tỉnh khác sinh ở Hùng Vương có được hưởng không?",
    "Có. Bệnh viện xác nhận khi nhập viện sinh, dù thẻ đăng ký ở tỉnh khác vẫn được hưởng như đúng tuyến, mức 80% trong danh mục BHYT và không cần giấy chuyển tuyến."),
   ("Chọn bác sĩ mổ ở Hùng Vương có tốn thêm phí không?",
    "Không. Bệnh viện trả lời rõ: chọn sinh dịch vụ thì được quyền yêu cầu bác sĩ mổ sinh mà không đóng thêm phí."),
   ("Gây tê ngoài màng cứng ở Hùng Vương giá bao nhiêu?",
    "Con số bệnh viện từng trả lời là 1.200.000đ, nhưng đó là năm 2018 &mdash; đã tám năm. Chúng tôi không đăng con số này như giá hiện hành. Gọi (028) 3855 8532 để xác nhận."),
   ("Sinh ở Từ Dũ hay Hùng Vương rẻ hơn?",
    "Ở mức không dịch vụ, Từ Dũ nhỉnh hơn về giá (3&ndash;5 triệu so với tạm ứng 6&ndash;7 triệu). Nhưng ở mức dịch vụ hai bên gần tương đương. Khác biệt thật nằm ở tiền phòng: phòng một giường Hùng Vương 3&ndash;3,7 triệu/ngày, còn Từ Dũ có dải rộng hơn từ 600.000đ. Nếu ngân sách chặt, dải phòng của Từ Dũ cho bạn nhiều lựa chọn hơn."),
 ],
},

# =====================================================================
{
 "slug": "tam-anh",
 "ten": "Bệnh viện Đa khoa Tâm Anh",
 "tinh": "TP.HCM và Hà Nội",
 "loai": "Bệnh viện tư",
 "calc_key": "tamanh",
 "nguon_ngay": "31/08/2026",
 "nguon_nhan": "Bảng giá dưới đây là bảng <b>đang hiển thị trên website bệnh viện</b>, chúng tôi truy cập ngày 31/08/2026. Tâm Anh không ghi ngày hiệu lực trên trang giá.",
 "nguon_url": "https://tamanhhospital.vn/sinh-con-tron-goi/",
 "title": "Chi phí sinh con ở Bệnh viện Tâm Anh: bảng giá gói trọn gói và khoản 10 triệu phát sinh ngoài gói",
 "desc": "Bảng giá gói thai sản Tâm Anh TP.HCM và Hà Nội theo từng tuần đăng ký. Kèm số liệu nghiên cứu bình duyệt: trung bình mỗi ca phát sinh thêm 10,2 triệu ngoài gói.",
 "tom_tat": "Tâm Anh là bệnh viện <b>minh bạch giá nhất</b> trong nhóm bệnh viện tư &mdash; đăng bảng giá chi tiết từng gói, từng loại sinh ngay trên website. Gói TP.HCM từ <b>31,4 triệu</b> đến <b>71,1 triệu</b>. Nhưng có một con số quan trọng hơn cả bảng giá, và nó không nằm trên website bệnh viện: một nghiên cứu khoa học bình duyệt năm 2024 đo được mỗi ca sinh <b>phát sinh thêm trung bình 10,2 triệu ngoài gói</b>.",

 "bang": [
   {"ten": "Gói TIÊU CHUẨN &mdash; Tâm Anh TP.HCM, đơn thai",
    "kiem_chung": "chinh-thuc",
    "nguon": "tamanhhospital.vn/sinh-con-tron-goi/",
    "cot": ["Đăng ký từ tuần", "Sinh thường", "Sinh thường + giảm đau", "Sinh mổ lần 1", "Sinh mổ lần 2"],
    "hang": [
      ["Tuần 12", "41.010.000đ", "44.670.000đ", "46.520.000đ", "48.920.000đ"],
      ["Tuần 22", "35.110.000đ", "38.770.000đ", "40.620.000đ", "43.020.000đ"],
      ["Tuần 32", "32.870.000đ", "36.520.000đ", "38.370.000đ", "40.780.000đ"],
      ["Tuần 36", "31.430.000đ", "35.080.000đ", "36.930.000đ", "39.340.000đ"],
    ]},
   {"ten": "Gói VIP &mdash; Tâm Anh TP.HCM, đơn thai",
    "kiem_chung": "chinh-thuc",
    "nguon": "tamanhhospital.vn/sinh-con-tron-goi/",
    "cot": ["Đăng ký từ tuần", "Sinh thường", "Sinh thường + giảm đau", "Sinh mổ lần 1", "Sinh mổ lần 2"],
    "hang": [
      ["Tuần 12", "59.280.000đ", "62.600.000đ", "68.870.000đ", "71.060.000đ"],
      ["Tuần 22", "49.140.000đ", "52.460.000đ", "58.730.000đ", "60.920.000đ"],
      ["Tuần 32", "44.640.000đ", "47.960.000đ", "54.240.000đ", "56.420.000đ"],
      ["Tuần 36", "41.510.000đ", "44.840.000đ", "51.110.000đ", "53.290.000đ"],
    ]},
   {"ten": "Tâm Anh Hà Nội &mdash; cấu trúc giá khác TP.HCM",
    "kiem_chung": "chinh-thuc",
    "nguon": "tamanhhospital.vn/cham-soc-thai-san-tron-goi/",
    "cot": ["Gói", "Loại", "Phòng 1 giường", "Phòng 2 giường"],
    "hang": [
      ["Tuần 12", "Đơn thai, sinh thường", "43.080.000đ", "38.140.000đ"],
      ["Tuần 12", "Đơn thai, mổ lần 1", "58.740.000đ", "53.090.000đ"],
      ["Tuần 12", "Song thai, sinh thường", "54.670.000đ", "48.570.000đ"],
      ["Tuần 12", "Ba thai, sinh thường", "64.870.000đ", "57.750.000đ"],
      ["Tuần 36", "Đơn thai, sinh thường", "&mdash;", "28.340.000đ"],
      ["VIP tuần 12", "Đơn thai, sinh thường", "67.240.000đ", "&mdash;"],
    ]},
   {"ten": "Song thai &mdash; Tâm Anh TP.HCM",
    "kiem_chung": "chinh-thuc",
    "nguon": "tamanhhospital.vn/sinh-con-tron-goi/",
    "cot": ["Gói / tuần", "Sinh thường", "Sinh thường + giảm đau", "Sinh mổ lần 1", "Sinh mổ lần 2"],
    "hang": [
      ["Tiêu chuẩn &mdash; tuần 32", "35.940.000đ", "39.600.000đ", "41.570.000đ", "44.150.000đ"],
      ["Tiêu chuẩn &mdash; tuần 34", "33.910.000đ", "37.560.000đ", "39.530.000đ", "42.110.000đ"],
      ["VIP &mdash; tuần 32", "49.830.000đ", "53.160.000đ", "59.540.000đ", "61.890.000đ"],
      ["VIP &mdash; tuần 34", "45.620.000đ", "48.940.000đ", "55.320.000đ", "57.670.000đ"],
    ]},
 ],

 "diem_nhan": {
   "tieu_de": "Con số quan trọng nhất trên trang này không nằm trong bảng giá",
   "noi_dung": "Có một nghiên cứu khoa học bình duyệt đo đúng câu hỏi &ldquo;mua gói rồi thì còn phải trả thêm bao nhiêu&rdquo;. Nghiên cứu mô tả cắt ngang trên các sản phụ mua gói trọn gói tại Tâm Anh từ tháng 12/2023 đến tháng 5/2024, đăng trên Tạp chí Y học Cộng đồng năm 2024.",
   "so": [
     ("Tổng chi phí trung bình mỗi ca sinh", "45.532.846đ", "độ lệch chuẩn 14,3 triệu"),
     ("Phần nằm trong gói", "35.293.286đ", "độ lệch chuẩn 8,5 triệu"),
     ("<b>Phần phát sinh ngoài gói</b>", "<b>10.239.560đ</b>", "<b>độ lệch chuẩn 12,1 triệu</b>"),
   ],
   "ket": "Hãy nhìn kỹ dòng cuối: độ lệch chuẩn 12,1 triệu <b>lớn hơn cả giá trị trung bình 10,2 triệu</b>. Về mặt thống kê, điều đó nghĩa là khoản phát sinh này <b>không dự đoán được</b>. Nhiều gia đình gần như không phát sinh gì; một số phát sinh vài chục triệu. Nếu bạn lập ngân sách bằng đúng giá gói, xác suất vỡ kế hoạch là rất cao. Nguồn: An, P.T., An, N.T.B., Cần, M.N. (2024), Tạp chí Y học Cộng đồng 65(6), DOI 10.52163/yhc.v65i6.1707.",
 },

 "khong_bao_gom": [
   "Khám cấp cứu ngoài giờ hành chính khi <b>chưa</b> chuyển dạ thực sự &mdash; rất hay xảy ra với con so.",
   "<b>Mổ lấy thai theo yêu cầu, không có chỉ định y khoa</b> &mdash; phụ thu thêm.",
   "Khám chuyên khoa cho bệnh lý không liên quan đến sinh nở.",
   "<b>Giảm đau đẻ tại TP.HCM là mức giá riêng</b>, cộng thêm khoảng 3,3&ndash;3,7 triệu. Đây là lỗi so sánh giá phổ biến nhất khi người ta đặt giá Tâm Anh cạnh giá bệnh viện khác.",
   "Chi phí vượt ngoài phác đồ chuẩn.",
   "Khám tặng sau sinh chỉ có hiệu lực trong 30 ngày.",
 ],

 "khong_cong_bo": [
   "<b>Giá NICU / chăm sóc đặc biệt sơ sinh.</b> Không công bố đơn giá theo ngày. Đây là rủi ro tài chính lớn nhất và không ước tính trước được.",
   "<b>Giá ngày giường theo hạng phòng.</b> File PDF bảng giá trên website hiện lỗi 404.",
   "<b>Giá sinh lẻ trọn ca</b> nếu không mua gói.",
 ],

 "luu_y": [
   ("Bảo hiểm y tế bù lại rất ít, đừng trông chờ",
    "Tâm Anh nhận mọi thẻ BHYT, mức hưởng 70/80/100% tuỳ đối tượng. Nhưng mức hưởng được tính <b>theo khung giá bệnh viện công</b>. Với hoá đơn 40&ndash;70 triệu ở bệnh viện tư, phần BHYT bù lại chỉ là một tỷ lệ nhỏ."),
   ("Có bảo lãnh viện phí trực tiếp với khoảng 18 công ty bảo hiểm",
    "Gồm Bảo Việt, Pacific Cross, Generali, Dai-ichi Life, Bảo Minh, GIC, BIC, Papaya, MIC, PTI, <b>AIA</b>, VBI, PJICO, InSmart, Fullerton, ATACC và một số đơn vị khác."),
   ("PVI đã dừng bảo lãnh tại cơ sở TP.HCM từ 01/11/2024",
    "Nếu bạn cầm thẻ PVI, phải tự thanh toán rồi lấy chứng từ đòi lại sau. Đây là thay đổi nhiều người không biết cho tới lúc đứng ở quầy thu ngân."),
   ("Khám thai định kỳ thường không được bảo hiểm tư nhân chi trả",
    "Danh mục loại trừ của hầu hết hợp đồng có mục &ldquo;khám thai sản định kỳ&rdquo;. Ca sinh có thể được chi trả, nhưng phần khám thai trong gói thì thường không."),
   ("Đăng ký sớm đắt hơn, nhưng không hẳn là đắt hơn",
    "Gói tuần 36 rẻ hơn gói tuần 12 khoảng 9,6 triệu ở TP.HCM. Nhưng gói tuần 12 đã bao gồm toàn bộ khám thai từ tuần 12 trở đi. Mua gói muộn thì bạn vẫn phải trả riêng các lần khám thai đó. Hãy so tổng chi, đừng so giá gói."),
 ],

 "faq": [
   ("Sinh ở Bệnh viện Tâm Anh hết bao nhiêu tiền?",
    "Gói trọn gói TP.HCM từ 31,43 triệu (tuần 36, sinh thường, tiêu chuẩn) đến 71,06 triệu (tuần 12, mổ lần 2, VIP). Hà Nội từ 28,34 triệu đến khoảng 118,78 triệu cho gói VIP đa thai. Nhưng nghiên cứu năm 2024 cho thấy tổng thực chi trung bình khoảng 45,5 triệu mỗi ca."),
   ("Mua gói thai sản Tâm Anh sớm hay muộn thì rẻ hơn?",
    "Về giá niêm yết, gói tuần 36 rẻ hơn gói tuần 12 khoảng 9,6 triệu tại TP.HCM. Nhưng gói tuần 12 bao gồm toàn bộ các lần khám thai từ tuần 12 đến khi sinh. Nếu mua gói muộn, bạn vẫn phải trả riêng những lần khám đó, nên tổng chi có thể không rẻ hơn."),
   ("Giá gói đã bao gồm đẻ không đau chưa?",
    "Tại TP.HCM là chưa. Giảm đau đẻ được tính thành một mức giá riêng, chênh khoảng 3.320.000 đến 3.660.000đ. Đây là chỗ hay bị so sánh sai khi đặt giá Tâm Anh cạnh bệnh viện khác."),
   ("Mua gói rồi thì còn phải trả thêm gì nữa không?",
    "Có, và khoản này lớn. Nghiên cứu bình duyệt năm 2024 đo được trung bình mỗi ca phát sinh thêm 10.239.560đ ngoài gói, với độ lệch chuẩn 12,1 triệu. Các khoản chính gồm: mổ theo yêu cầu không có chỉ định y khoa, khám cấp cứu ngoài giờ khi chưa chuyển dạ thực sự, nằm viện dài hơn dự kiến, bệnh lý ngoài sản khoa, và chăm sóc đặc biệt cho bé."),
   ("Sinh mổ ở Tâm Anh đắt hơn sinh thường bao nhiêu?",
    "Tại TP.HCM, gói tiêu chuẩn tuần 12: sinh thường 41,01 triệu, mổ lần 1 46,52 triệu &mdash; chênh khoảng 5,5 triệu. Tại Hà Nội cùng mốc tuần 12 phòng một giường: 43,08 lên 58,74 triệu &mdash; chênh tới 15,7 triệu."),
   ("Bảo hiểm y tế dùng được ở Tâm Anh không?",
    "Được, Tâm Anh nhận thẻ BHYT đăng ký ban đầu ở bất kỳ cơ sở nào, mức hưởng 70/80/100% tuỳ đối tượng. Nhưng mức hưởng tính theo khung giá bệnh viện công, nên với hoá đơn vài chục triệu, phần bù lại chiếm tỷ lệ nhỏ."),
   ("Bảo hiểm tư nhân có bảo lãnh viện phí trực tiếp ở Tâm Anh không?",
    "Có, với khoảng 18 công ty gồm Bảo Việt, AIA, Generali, Dai-ichi, Bảo Minh, PTI, MIC, Pacific Cross và một số đơn vị khác. Lưu ý PVI đã tạm dừng bảo lãnh tại cơ sở TP.HCM từ 01/11/2024."),
 ],
},

# =====================================================================
{
 "slug": "vinmec",
 "ten": "Bệnh viện Vinmec",
 "tinh": "Toàn quốc",
 "loai": "Bệnh viện tư quốc tế",
 "calc_key": "vinmec",
 "nguon_ngay": "31/08/2026",
 "nguon_nhan": "Chúng tôi truy cập website Vinmec ngày 31/08/2026 và <b>không tìm thấy bất kỳ con số giá nào</b>. Bệnh viện chỉ ghi &ldquo;áp dụng bảng giá mới từ 14/10/2025&rdquo; mà không đăng bảng.",
 "nguon_url": "https://www.vinmec.com/vie/di-sinh-tai-vinmec-dich-vu-thai-san-toan-dien/",
 "title": "Chi phí sinh con ở Vinmec: vì sao không tìm được bảng giá, và những gì kiểm chứng được",
 "desc": "Vinmec không công bố giá gói thai sản trên website. Trang này tách rõ phần bệnh viện xác nhận chính thức và phần chỉ là ước tính từ bên thứ ba, thay vì đưa một bảng giá không rõ nguồn.",
 "tom_tat": "Nếu bạn đã tìm mỏi mắt mà không thấy bảng giá thai sản Vinmec, thì không phải bạn tìm kém. <b>Vinmec không công bố giá công khai.</b> Trang &ldquo;Bảng giá dịch vụ thai sản trọn gói tại Vinmec&rdquo; trên website chính thức có tiêu đề nhưng không có con số nào. Mọi bảng giá Vinmec bạn thấy trên internet đều là do bên thứ ba tổng hợp &mdash; và chúng <b>mâu thuẫn nhau tới hai, ba lần</b>.",
 "canh_bao": "Chúng tôi quyết định không đăng một bảng giá Vinmec như thể đó là số chắc chắn. Thay vào đó, trang này tách làm hai phần rõ ràng: phần Vinmec xác nhận chính thức, và phần chỉ là tham khảo. Bạn tự quyết định tin đến đâu.",

 "bang": [
   {"ten": "Phần Vinmec XÁC NHẬN CHÍNH THỨC",
    "kiem_chung": "chinh-thuc",
    "nguon": "vinmec.com",
    "cot": ["Nội dung", "Xác nhận"],
    "hang": [
      ["Các mốc gói thai sản", "Tuần 12, 22, 27, 36 &mdash; và gói chuyển dạ"],
      ["Gói chuyển dạ dành cho ai", "Mẹ chưa từng đăng ký gói thai sản trước đó (tương đương &ldquo;sinh lẻ&rdquo;)"],
      ["Phạm vi áp dụng", "Toàn hệ thống Vinmec"],
      ["Ưu đãi", "<b>Giảm 10%</b> khi mua gói 12/22/27/36 tuần và gói chuyển dạ"],
      ["Ưu đãi combo", "Thai sản + vaccine + biobank: giảm thêm 1&ndash;2 triệu"],
      ["Gói bao gồm", "Khám thai, xét nghiệm, siêu âm, lớp học tiền sản, quà mẹ &amp; bé, suất ăn cho mẹ, sữa công thức cho bé"],
      ["Bảng giá mới Times City &amp; Central Park", "Hiệu lực từ 14/10/2025 &mdash; nhưng <b>không đăng số</b>"],
      ["Số đối tác bảo lãnh viện phí", "<b>35 công ty</b> &mdash; rộng hơn hầu hết bệnh viện khác"],
    ]},
   {"ten": "Phần THAM KHẢO &mdash; số từ bên thứ ba, Vinmec chưa xác nhận",
    "kiem_chung": "thu-cap",
    "nguon": "Tổng hợp từ các trang thứ ba, đối chiếu chéo giữa nhiều nguồn. KHÔNG phải số chính thức của Vinmec.",
    "cot": ["Loại sinh (Times City / Central Park, đơn thai)", "Dải giá tham khảo (tuần 36 &rarr; tuần 12)"],
    "hang": [
      ["Sinh thường", "khoảng 37.200.000 &ndash; 52.000.000đ"],
      ["Sinh mổ lần 1", "khoảng 52.000.000 &ndash; 65.000.000đ"],
      ["Sinh mổ lần 2", "khoảng 56.000.000 &ndash; 68.000.000đ"],
      ["Sinh mổ lần 3 trở lên", "khoảng 60.500.000 &ndash; 72.000.000đ"],
      ["Chi nhánh tỉnh (Hải Phòng, Nha Trang, Đà Nẵng, Hạ Long, Phú Quốc)", "thấp hơn đáng kể: sinh thường khoảng 24&ndash;33 triệu"],
    ]},
 ],

 "khong_cong_bo": [
   "<b>Toàn bộ bảng giá gói thai sản.</b> Vinmec yêu cầu gọi hotline để biết giá. Tổng đài 024 3975 6789, Times City 024 3974 3556.",
   "<b>Giá gói chuyển dạ</b> (trường hợp đến viện khi đã chuyển dạ mà chưa mua gói).",
   "<b>Giá ngày giường theo hạng phòng.</b>",
   "<b>Giá NICU / chăm sóc đặc biệt sơ sinh.</b> Chỉ xác nhận được rằng NICU nằm ngoài gói.",
   "<b>Số ngày nằm viện chính thức theo gói.</b> Nguồn thứ cấp ghi sinh thường 1&ndash;2 đêm, sinh mổ 3&ndash;4 đêm.",
 ],

 "luu_y": [
   ("Vì sao chúng tôi không đưa một bảng giá Vinmec đẹp đẽ như các trang khác",
    "Vì chúng tôi đã kiểm tra và các bảng giá đó mâu thuẫn nhau nghiêm trọng. Một trang ghi sinh thường 15&ndash;25 triệu, trang khác ghi 50&ndash;70 triệu &mdash; chênh nhau ba lần cho cùng một dịch vụ, cùng một bệnh viện. Đăng lại con số nào cũng là đánh cược bằng ngân sách của bạn."),
   ("Điểm mạnh thật của Vinmec nằm ở danh sách bảo lãnh",
    "35 đối tác bảo lãnh viện phí trực tiếp, gồm cả PVI (mà Tâm Anh TP.HCM đã dừng), International SOS, Allianz Partners, Liberty, Pacific Cross, AIA, Bảo Việt, Generali, Dai-ichi. Nếu thẻ bảo hiểm của bạn nằm trong danh sách này, phần bạn thực trả có thể thấp hơn nhiều so với giá niêm yết."),
   ("Chi nhánh tỉnh rẻ hơn đáng kể",
    "Theo nguồn tham khảo, Vinmec ở Hải Phòng, Nha Trang, Đà Nẵng, Hạ Long, Phú Quốc có giá thấp hơn Times City và Central Park khoảng 30&ndash;40%. Nếu bạn linh hoạt được về địa điểm, đây là khoản tiết kiệm lớn."),
   ("Bảo hiểm y tế: hưởng theo khung giá bệnh viện công",
    "Vinmec có hợp đồng BHYT tại Times City, Central Park, Smart City, Đà Nẵng, Nha Trang, Hải Phòng, Hạ Long, Phú Quốc, Cần Thơ. Nhưng như mọi bệnh viện tư, bạn tự trả phần chênh giữa giá Vinmec và mức BHYT chi trả &mdash; phần chênh này là phần lớn."),
 ],

 "faq": [
   ("Sinh ở Vinmec hết bao nhiêu tiền?",
    "Vinmec không công bố giá công khai nên không có câu trả lời chắc chắn. Theo các nguồn tham khảo bên thứ ba (chưa được Vinmec xác nhận), sinh thường tại Times City hoặc Central Park khoảng 37&ndash;52 triệu, sinh mổ lần 1 khoảng 52&ndash;65 triệu, tuỳ tuần đăng ký gói. Chi nhánh tỉnh thấp hơn nhiều. Bắt buộc gọi hotline 024 3975 6789 để có giá chính xác."),
   ("Vì sao không tìm thấy bảng giá thai sản Vinmec ở đâu cả?",
    "Vì Vinmec không đăng số lên website. Trang &ldquo;Bảng giá dịch vụ thai sản trọn gói tại Vinmec&rdquo; chỉ có tiêu đề và hướng dẫn liên hệ. Các trang bảng giá cơ sở cũng chỉ ghi &ldquo;áp dụng bảng giá mới từ 14/10/2025&rdquo; mà không có con số nào."),
   ("Các bảng giá Vinmec trên mạng có tin được không?",
    "Nên rất thận trọng. Chúng tôi đã đối chiếu nhiều nguồn và thấy chúng chênh nhau tới hai, ba lần cho cùng một dịch vụ &mdash; có trang ghi sinh thường 15&ndash;25 triệu, trang khác ghi 50&ndash;70 triệu. Không nguồn nào trong số đó dẫn được bảng giá gốc của Vinmec."),
   ("Vinmec có giảm giá gói thai sản không?",
    "Có, và đây là thông tin chính thức từ Vinmec: giảm 10% cho gói 12, 22, 27, 36 tuần và gói chuyển dạ. Mua combo thai sản kết hợp vaccine và biobank được giảm thêm 1&ndash;2 triệu."),
   ("Đến viện lúc đã chuyển dạ mà chưa mua gói thì sao?",
    "Vinmec có &ldquo;gói chuyển dạ&rdquo; dành riêng cho trường hợp này &mdash; đây là thông tin bệnh viện xác nhận chính thức. Giá thì không công bố."),
   ("Bảo hiểm của tôi có bảo lãnh viện phí ở Vinmec không?",
    "Vinmec có 35 đối tác bảo lãnh, gồm hầu hết công ty lớn: Bảo Việt, PVI, Bảo Minh, AIA, Dai-ichi, Generali, PTI, PJICO, MIC, BIC, VBI, Pacific Cross, Liberty, International SOS, Allianz Partners. Đây là danh sách rộng hơn phần lớn bệnh viện khác."),
   ("Sinh ở Vinmec hay Tâm Anh đắt hơn?",
    "Với dữ liệu hiện có, Tâm Anh rẻ hơn khoảng 15&ndash;30% ở cùng mốc tuần đăng ký, rõ nhất ở sinh mổ tại TP.HCM. Nhưng phải nói thẳng: so sánh này lệch về chất lượng nguồn &mdash; số Tâm Anh là số chính thức bệnh viện đăng, còn số Vinmec chỉ là ước tính từ bên thứ ba."),
 ],
},



# =====================================================================
{
 "slug": "fv",
 "ngay_dang": "2026-09-01",
 "ten": "Bệnh viện FV",
 "tinh": "TP. Hồ Chí Minh",
 "loai": "Bệnh viện quốc tế",
 "calc_key": "fv",
 "nguon_ngay": "21/05/2026",
 "nguon_nhan": "FV là một trong số rất ít bệnh viện tư đăng trọn bộ bảng giá gói sinh lên website, chia theo từng hạng phòng. Bản đọc được cập nhật gần nhất <b>ngày 21/05/2026</b>. Bản tiếng Việt của trang này hiện lỗi 404, chỉ còn đọc được bản tiếng Anh.",
 "nguon_url": "https://www.fvhospital.com/en/fv-thomson-maternity/delivery-packages/",
 "title": "Chi phí sinh con ở Bệnh viện FV: bảng giá 22 mức theo hạng phòng và phần bảo hiểm trả",
 "desc": "FV công bố đủ 22 mức giá gói sinh từ 45 đến 168 triệu theo gói và hạng phòng. Bài này có bảng giá đầy đủ, phần BHYT và bảo hiểm tư chi trả theo chính FV công bố, và những khoản bệnh viện không công bố.",
 "tom_tat": "Gói sinh thấp nhất của FV là <b>45 triệu</b>, áp dụng cho sinh thường, phòng tiêu chuẩn, 3 đêm nằm viện. Sinh mổ thấp nhất 55 triệu, 4 đêm. Cao nhất là gói Bạch Kim phòng Premium Suite: <b>168 triệu</b> cho một ca sinh mổ. Khác với phần lớn bệnh viện tư, FV đăng công khai cả 22 mức giá theo từng gói và hạng phòng, đồng thời tự công bố phần bảo hiểm chi trả.",

 "bang": [
   {"ten": "Bảng giá gói sinh FV Thomson: đủ 22 mức",
    "kiem_chung": "chinh-thuc",
    "nguon": "fvhospital.com, trang gói sinh, bản cập nhật 21/05/2026",
    "cot": ["Gói &amp; hạng phòng", "Sinh thường (3 đêm)", "Sinh mổ (4 đêm)"],
    "hang": [
      ["<b>Bạc</b>, phòng Tiêu chuẩn", "45.000.000đ", "55.000.000đ"],
      ["<b>Bạc</b>, phòng Đơn", "50.000.000đ", "61.000.000đ"],
      ["<b>Bạc</b>, phòng Gia đình", "61.000.000đ", "77.000.000đ"],
      ["<b>Vàng</b>, phòng Tiêu chuẩn", "56.000.000đ", "66.000.000đ"],
      ["<b>Vàng</b>, phòng Gia đình", "65.000.000đ", "77.000.000đ"],
      ["<b>Kim Cương</b>, phòng Tiêu chuẩn", "75.000.000đ", "85.000.000đ"],
      ["<b>Kim Cương</b>, phòng Gia đình", "84.000.000đ", "96.000.000đ"],
      ["<b>Kim Cương</b>, phòng VIP", "98.000.000đ", "112.000.000đ"],
      ["<b>Kim Cương</b>, Premium Suite", "114.000.000đ", "130.000.000đ"],
      ["<b>Bạch Kim</b>, phòng VIP", "140.000.000đ", "150.000.000đ"],
      ["<b>Bạch Kim</b>, Premium Suite", "155.000.000đ", "168.000.000đ"],
    ]},
   {"ten": "Phần tự trả sau bảo hiểm, theo con số FV công bố",
    "kiem_chung": "chinh-thuc",
    "nguon": "fvhospital.com, bài công bố áp dụng BHYT, đăng 31/12/2025",
    "cot": ["Khoản mục", "Mức FV công bố"],
    "hang": [
      ["Gói sinh trọn gói", "từ 45.000.000đ"],
      ["BHYT chi trả cho ca sinh", "gần 2.000.000 &ndash; 8.000.000đ, tuỳ quyền lợi người tham gia"],
      ["Bảo hiểm sức khoẻ tư nhân chi trả thêm", "khoảng 12.000.000 &ndash; hơn 40.000.000đ"],
      ["Thẻ hội viên FV Ưu Tiên chi trả thêm", "hơn 11.000.000đ"],
      ["Thẻ hội viên FV VIP chi trả thêm", "lên tới hơn 40.000.000đ"],
      ["<b>Phần người bệnh còn tự trả</b>", "<b>khoảng 20.000.000đ, thậm chí thấp hơn</b>"],
    ]},
   {"ten": "Quyền lợi thai sản của thẻ hội viên FV Ưu Tiên",
    "kiem_chung": "chinh-thuc",
    "nguon": "fvhospital.com, trang chương trình hội viên Ưu Tiên (trang không ghi ngày cập nhật, truy cập ngày 01/09/2026)",
    "cot": ["Quyền lợi", "Hạn mức"],
    "hang": [
      ["Hạn mức chung ốm đau, bệnh tật và chăm sóc thai sản", "110.000.000đ"],
      ["Sinh thường, chi phí nằm viện", "5.000.000đ / ngày"],
      ["Sinh mổ, phẫu thuật", "22.000.000đ"],
      ["Sinh mổ, nằm viện", "5.000.000đ / ngày"],
      ["Giới hạn chăm sóc thai sản mỗi năm", "28.600.000đ (chưa gồm khám trước sinh)"],
      ["Phí thẻ", "tính theo bậc tuổi, <b>không công bố bằng số</b>"],
    ]},
 ],

 "khong_bao_gom": [
   "Đêm nằm viện vượt quá 3 đêm (sinh thường) hoặc 4 đêm (sinh mổ). FV không công bố cách tính phần vượt.",
   "Trường hợp sinh thường chuyển thành sinh mổ giữa chừng. Trang gói sinh không nêu ca này được tính theo mức nào.",
   "Chăm sóc đặc biệt sơ sinh (NICU), sinh non, biến chứng. Trang gói sinh không nhắc tới, nên phải hỏi riêng.",
   "Song thai, đa thai. Bảng giá không có dòng nào dành cho trường hợp này.",
 ],

 "khong_cong_bo": [
   "Giá tiền phòng tính riêng theo ngày. FV bán theo gói, không đăng bảng giá phòng lẻ. Trang &ldquo;chi phí phát sinh&rdquo; chỉ liệt kê <i>loại</i> chi phí, không có con số nào.",
   "Mức tạm ứng khi nhập viện. Bệnh viện chỉ nói phải đặt cọc nếu chưa có thư bảo lãnh, không nêu số tiền.",
   "Giá gói theo dõi thai kỳ. Có trang mô tả nội dung gói, không có giá.",
   "Giá gây tê ngoài màng cứng tách riêng. FV cho biết khoản này đã nằm trong mọi gói nên không có giá lẻ.",
   "Phí thẻ hội viên Ưu Tiên và VIP bằng con số. Trang chỉ ghi &ldquo;tính theo bậc tuổi&rdquo;.",
   "Bảng giá FV năm 2022 đang lan truyền trên mạng cũng không được đăng lại ở đây. Bảng đó ghi sinh mổ từ 26 triệu, trong khi giá FV công bố hiện nay thấp nhất là <b>55 triệu</b> &mdash; chênh hơn hai lần.",
 ],

 "luu_y": [
   ("Gây tê ngoài màng cứng đã nằm trong giá gói",
    "Ở hầu hết bệnh viện tư khác, &ldquo;đẻ không đau&rdquo; là khoản tính thêm 1&ndash;2 triệu. FV ghi rõ trong mọi gói: gây tê ngoài màng cứng, gây tê vùng hoặc gây mê theo chỉ định đều đã bao gồm."),
   ("Có bảo hiểm quốc tế thì giá gói không áp dụng",
    "Câu này lặp lại ở cả bốn gói trên website FV, nguyên văn: <i>&ldquo;The package price is not applicable for clients covered by international insurance&rdquo;</i>. Người đang dùng thẻ bảo hiểm quốc tế không nên lấy bảng giá này làm căn cứ, mà phải hỏi riêng."),
   ("Gói Bạc chỉ mua được từ tuần 37&ndash;38, gói Bạch Kim từ tuần 36&ndash;37",
    "Nhiều bệnh viện bán gói thai sản từ tuần 7 hoặc tuần 12, còn gói sinh FV chỉ dành cho riêng ca sinh và đăng ký rất muộn. Vì vậy không &ldquo;khoá giá&rdquo; sớm được như ở Hạnh Phúc hay Quốc tế City."),
   ("Từ 01/01/2026 FV áp dụng BHYT cho toàn bộ nội trú, ngoại trú và cấp cứu",
    "Bệnh viện công bố ngày 31/12/2025. Có bao gồm sản khoa. BHYT trả theo khung giá BHYT, và chính FV ước tính con số đó chỉ khoảng gần 2 đến 8 triệu cho một ca sinh, trên tổng hoá đơn 45 triệu trở lên."),
   ("102 đơn vị thanh toán trực tiếp, danh sách rộng nhất trong nhóm bệnh viện tư",
    "Gồm 13 công ty bảo hiểm trong nước (Bảo Việt, Bảo Minh, BIC, PVI, PJICO, MIC, VNI, Generali, PTI Sài Gòn&hellip;), 52 công ty quốc tế (Aetna, AIA, Allianz, AXA PPP, BUPA, Cigna, Dai-ichi, Liberty&hellip;), 3 đơn vị giám định (Insmart, Bảo An Khang, Dịch vụ Nam Á), 24 công ty hỗ trợ và 10 đơn vị bảo hiểm Nhật Bản. Với ca nhập viện theo kế hoạch, FV gửi yêu cầu bảo lãnh trước 3&ndash;4 ngày; ca cấp cứu thường được xác nhận trong 24 giờ làm việc."),
   ("Hai ô cùng 77 triệu, và những ô bảng giá bị khuyết",
    "Bảng có hai ô bằng nhau đúng 77 triệu: sinh mổ phòng Gia đình của gói Bạc và của gói Vàng. Theo đối chiếu lại trang gốc, FV niêm yết đúng như vậy, không phải lỗi chép. Nghĩa là với phòng Gia đình và sinh mổ, nâng từ gói Bạc lên gói Vàng không tốn thêm tiền. Bảng cũng khuyết một số ô: gói Vàng, Kim Cương, Bạch Kim không có phòng Đơn, còn gói Bạch Kim chỉ bán kèm VIP hoặc Premium Suite. Đó là do FV chỉ công bố đúng các tổ hợp này."),
   ("Bản tiếng Việt của trang bảng giá đang lỗi",
    "Trang <code>/vi/khoa-san-fv-thomson/cac-goi-sinh-fv-thomson/</code> trả về 404 tại thời điểm rà soát. Toàn bộ số trong bài lấy từ bản tiếng Anh, là bản duy nhất còn đọc được."),
 ],

 "faq": [
   ("Sinh ở Bệnh viện FV hết bao nhiêu tiền?",
    "Theo bảng giá FV công bố (bản cập nhật 21/05/2026), thấp nhất là gói Bạc, sinh thường, phòng tiêu chuẩn, 3 đêm: 45 triệu. Sinh mổ thấp nhất 55 triệu, 4 đêm. Cao nhất là gói Bạch Kim phòng Premium Suite, 155 triệu cho sinh thường và 168 triệu cho sinh mổ."),
   ("Gói sinh FV rẻ nhất là bao nhiêu?",
    "45.000.000đ, gói Bạc, sinh thường, phòng tiêu chuẩn, 3 đêm nằm viện. Gói này đăng ký được từ tuần 37&ndash;38 của thai kỳ."),
   ("Sinh mổ ở FV bao nhiêu tiền?",
    "Thấp nhất 55 triệu (gói Bạc, phòng tiêu chuẩn, 4 đêm), cao nhất 168 triệu (gói Bạch Kim, Premium Suite). Cùng gói Bạc, đổi từ phòng tiêu chuẩn sang phòng gia đình đã tăng từ 55 lên 77 triệu. Hạng phòng là biến số đắt nhất."),
   ("Đẻ không đau ở FV có tính thêm tiền không?",
    "Không. FV ghi rõ gây tê ngoài màng cứng, gây tê vùng hoặc gây mê theo chỉ định đã bao gồm trong tất cả các gói sinh. Phần lớn bệnh viện tư khác tính thêm khoản này."),
   ("Có bảo hiểm y tế thì sinh ở FV được trả bao nhiêu?",
    "Từ 01/01/2026 FV áp dụng BHYT cho toàn bộ dịch vụ nội trú, ngoại trú và cấp cứu. Nhưng chính FV công bố mức BHYT chi trả cho một ca sinh chỉ khoảng gần 2 đến 8 triệu tuỳ quyền lợi, tức dưới 18% của gói rẻ nhất."),
   ("Bảo hiểm tư nhân trả được bao nhiêu khi sinh ở FV?",
    "Theo con số FV công bố ngày 31/12/2025: bảo hiểm sức khoẻ tư nhân chi trả thêm khoảng 12 triệu đến hơn 40 triệu. Cộng với BHYT, phần người bệnh còn tự trả khoảng 20 triệu, thậm chí thấp hơn. Thẻ sức khoẻ có quyền lợi thai sản vì vậy thay đổi đáng kể bài toán chi phí ở bệnh viện quốc tế."),
   ("FV có bảo lãnh viện phí với bảo hiểm của tôi không?",
    "Nhiều khả năng là có. FV có 102 đơn vị thanh toán trực tiếp, gồm hầu hết công ty lớn trong nước và quốc tế. Ở chiều ngược lại, với bảo hiểm quốc tế thì FV nói rõ giá gói không áp dụng, phải hỏi riêng."),
   ("Nằm quá số đêm trong gói thì tính thế nào?",
    "FV không công bố. Gói ghi 3 đêm cho sinh thường và 4 đêm cho sinh mổ, nhưng không có dòng nào nói phần vượt tính bao nhiêu. Đây là câu nên hỏi trước khi đặt cọc, số điện thoại (028) 35 11 35 35."),
 ],
},

# =====================================================================
{
 "slug": "quoc-te-city",
 "ngay_dang": "2026-09-01",
 "ten": "Bệnh viện Quốc tế City",
 "tinh": "TP. Hồ Chí Minh",
 "loai": "Bệnh viện quốc tế",
 "calc_key": "cih",
 "nguon_ngay": "27/02/2026",
 "nguon_nhan": "Bảng giá gói sinh trên cih.com.vn có ngày đăng 06&ndash;07/08/2024 và lần cập nhật gần nhất <b>27/02/2026</b>; bảng giá dịch vụ (tiền phòng) sửa đổi lần cuối <b>24/06/2026</b>. Bệnh viện không phát hành bảng giá nào đề &ldquo;năm 2026&rdquo;.",
 "nguon_url": "https://cih.com.vn/chuyen-khoa-khac/3983-goi-thai-san-tai-benh-vien-quoc-te-city/",
 "title": "Chi phí sinh con ở Bệnh viện Quốc tế City: giá gói và khoản tiền phòng gói không bao gồm",
 "desc": "Gói sinh Quốc tế City từ 25,1 triệu, nhưng bệnh viện ghi rõ giá gói chưa bao gồm tiền phòng, trong khi phòng là 1,65 đến 3,3 triệu mỗi ngày. Bảng giá đầy đủ, dẫn nguồn, kèm những khoản bệnh viện không công bố.",
 "tom_tat": "Gói sinh thường ở Quốc tế City là <b>25.100.000đ</b> (gói Như Ý), thấp hơn hẳn FV hay Hạnh Phúc. Nhưng trang gói của bệnh viện ghi rõ: &ldquo;Giá gói sinh chưa bao gồm giá phòng, người thân ở lại&rdquo;. Tiền phòng ở đây là <b>1,65 đến 3,3 triệu mỗi ngày</b>, tính riêng. Bỏ qua dòng này thì mọi phép so giá với bệnh viện khác đều lệch.",

 "bang": [
   {"ten": "Gói sinh đơn lẻ: chỉ ca sinh, chưa gồm tiền phòng",
    "kiem_chung": "chinh-thuc",
    "nguon": "cih.com.vn, trang gói sinh Như Ý và Cát Tường, cập nhật 27/02/2026",
    "cot": ["Hình thức sinh", "Gói Như Ý", "Gói Cát Tường"],
    "hang": [
      ["Sinh thường", "25.100.000đ", "31.700.000đ"],
      ["Sinh mổ đơn thai lần đầu", "36.180.000đ", "42.530.000đ"],
      ["Sinh mổ có vết mổ cũ lần 1", "41.040.000đ", "48.740.000đ"],
      ["Sinh mổ có vết mổ cũ lần 2, 3", "46.360.000đ", "55.810.000đ"],
    ]},
   {"ten": "Tiền phòng, khoản gói sinh không bao gồm",
    "kiem_chung": "chinh-thuc",
    "nguon": "cih.com.vn, bảng giá dịch vụ, sửa đổi lần cuối 24/06/2026",
    "cot": ["Loại phòng", "Giá mỗi ngày"],
    "hang": [
      ["Phòng 2 giường", "1.650.000đ"],
      ["Phòng 1 giường", "2.750.000đ"],
      ["Phòng chăm sóc đặc biệt", "3.300.000đ"],
    ]},
   {"ten": "Gói thai sản trọn gói, sinh thường, theo tuần đăng ký",
    "kiem_chung": "chinh-thuc",
    "nguon": "cih.com.vn, trang gói thai sản, cập nhật 27/02/2026",
    "cot": ["Đăng ký từ tuần", "Gói Như Ý", "Gói Cát Tường"],
    "hang": [
      ["Tuần 7 &ndash; 40", "48.200.000đ", "54.150.000đ"],
      ["Tuần 13 &ndash; 40", "40.600.000đ", "46.550.000đ"],
      ["Tuần 28 &ndash; 40", "36.700.000đ", "42.650.000đ"],
      ["Tuần 36 &ndash; 40", "32.400.000đ", "38.350.000đ"],
    ]},
   {"ten": "Gói thai sản trọn gói, sinh mổ",
    "kiem_chung": "chinh-thuc",
    "nguon": "cih.com.vn, trang gói thai sản, cập nhật 27/02/2026",
    "cot": ["Hình thức sinh mổ", "Như Ý &mdash; đăng ký tuần 36&ndash;40", "Như Ý &mdash; đăng ký tuần 7&ndash;40", "Cát Tường &mdash; tuần 7&ndash;40"],
    "hang": [
      ["Đơn thai lần đầu", "42.480.000đ", "58.280.000đ", "64.030.000đ"],
      ["Có vết mổ cũ lần 1", "47.040.000đ", "62.840.000đ", "69.740.000đ"],
      ["Có vết mổ cũ lần 2, 3", "51.960.000đ", "67.760.000đ", "76.260.000đ"],
    ]},
   {"ten": "Gói sinh Yêu Thương: rẻ hơn, nhưng chưa gồm phí bác sĩ, thuốc và vật tư",
    "kiem_chung": "chinh-thuc",
    "nguon": "cih.com.vn, trang gói sinh Yêu Thương, ghi rõ áp dụng từ 07/03/2025",
    "cot": ["Hình thức sinh", "Phòng 2 giường", "Phòng 1 giường"],
    "hang": [
      ["Sinh thường đơn thai", "17.100.000đ", "18.900.000đ"],
      ["Sinh mổ lần đầu", "25.452.000đ", "28.152.000đ"],
      ["Sinh mổ có vết mổ cũ / ngôi ngang", "28.872.000đ", "32.472.000đ"],
      ["Sinh mổ lần 2, 3", "31.608.000đ", "35.208.000đ"],
    ]},
   {"ten": "Mức hưởng BHYT tại Quốc tế City",
    "kiem_chung": "chinh-thuc",
    "nguon": "cih.com.vn, trang điều kiện và quyền lợi BHYT nhà nước (trang không ghi ngày, truy cập ngày 01/09/2026)",
    "cot": ["Trường hợp", "Mức hưởng trên khung giá BHYT"],
    "hang": [
      ["Đúng tuyến", "100% &ndash; 95% &ndash; 80% tuỳ nhóm đối tượng"],
      ["Trái tuyến (chỉ nội trú)", "60% &ndash; 57% &ndash; 48%"],
      ["Ngoại trú trái tuyến", "<b>Không áp dụng</b>"],
      ["Các gói khám thai", "<b>BHYT không chi trả</b> &mdash; bệnh viện loại trừ rõ"],
      ["Phụ thu phí quản lý thuốc", "10%"],
    ]},
 ],

 "khong_bao_gom": [
   "Tiền phòng và chỗ cho người thân ở lại. Đây là nguyên văn câu loại trừ của bệnh viện, và là khoản lớn nhất bị bỏ sót khi so giá: 1,65 đến 3,3 triệu mỗi ngày.",
   "Riêng với gói Yêu Thương: phí bác sĩ, thuốc và vật tư y tế. Đó là lý do gói này rẻ hơn hẳn, không phải vì cùng dịch vụ mà rẻ hơn.",
   "Ca đa thai, nhau tiền đạo, chảy máu, nhau bong non, ngôi mông. Bệnh viện ghi các trường hợp này &ldquo;áp dụng mức giá khác theo quy định hiện tại&rdquo; nhưng không công bố mức đó là bao nhiêu.",
 ],

 "khong_cong_bo": [
   "Giá gây tê ngoài màng cứng. Không có trên bảng giá dịch vụ, cũng không có trên bất kỳ trang gói nào. Với một bệnh viện đăng giá kỹ như Quốc tế City, đây là khoảng trống đáng chú ý.",
   "<b>Số ngày nằm viện đi kèm mỗi gói sinh.</b> Không trang nào nêu. Tiền phòng lại tính riêng theo ngày, nên không biết số ngày thì không tính được tổng.",
   "Mức tạm ứng khi nhập viện sinh. Trang chính sách đặt cọc chỉ nêu nguyên tắc chung, không có con số cho sản khoa.",
   "Danh mục bao gồm chi tiết của gói Như Ý và Cát Tường. Chỉ có hai câu loại trừ chung.",
   "Chi phí NICU, sinh non, biến chứng. Bệnh viện có khoa hồi sức tích cực sơ sinh nhưng không công bố giá.",
   "Danh sách công ty bảo hiểm bảo lãnh trực tiếp. Trang thông tin bảo hiểm không liệt kê tên. Các danh sách lưu hành trên mạng đều đến từ trang bán bảo hiểm và không trùng khớp nhau, nên không được đăng lại ở đây.",
 ],

 "luu_y": [
   ("Giá gói chưa gồm tiền phòng",
    "Nguyên văn của bệnh viện: &ldquo;Giá gói sinh chưa bao gồm giá phòng, người thân ở lại&hellip;&rdquo;. Gói sinh thường 25,1 triệu là mức dễ chịu, cho tới khi cộng thêm phòng 1 giường 2,75 triệu mỗi ngày. Bệnh viện lại không công bố số ngày nằm viện, nên cần hỏi thẳng hai điều: nằm mấy ngày và phòng hạng nào."),
   ("Gói Yêu Thương không cùng phạm vi với gói Như Ý",
    "Gói Yêu Thương sinh thường 17,1 triệu, rẻ hơn Như Ý đúng 8 triệu. Nhưng bệnh viện ghi rõ gói này chưa bao gồm phí bác sĩ, thuốc và vật tư y tế. Đó là ba khoản không nhỏ trong một ca sinh."),
   ("Đăng ký muộn rẻ hơn đăng ký sớm 15,8 triệu",
    "Gói thai sản Như Ý sinh thường đăng ký tuần 7&ndash;40 là 48,2 triệu, còn tuần 36&ndash;40 chỉ 32,4 triệu. Nhưng gói đăng ký sớm bao gồm cả chặng khám thai dài, còn gói muộn thì thai phụ tự trả tiền khám thai bên ngoài. Phải cộng cả hai vế mới so được."),
   ("BHYT có nhận, nhưng loại trừ các gói khám thai",
    "Bệnh viện nhận BHYT: ngoại trú chỉ đúng tuyến, nội trú nhận cả trái tuyến. Trang quyền lợi ghi rõ &ldquo;các gói khám thai&rdquo; nằm trong danh mục BHYT không chi trả, cùng với khám tổng quát, tầm soát và chích ngừa."),
   ("Có bảo hiểm quốc tế thì không được hưởng giá hỗ trợ",
    "Chính sách giá của bệnh viện nói rõ: mức &ldquo;giá hỗ trợ&rdquo; áp dụng cho người không có bảo hiểm và người có bảo hiểm nội địa Việt Nam, <b>không</b> áp dụng cho bảo hiểm quốc tế hoặc đa lãnh thổ, kể cả khi có thoả thuận bảo lãnh trực tiếp. Rất ít bệnh viện nêu rõ điều này."),
   ("Cách bệnh viện tính tiền đặt cọc khi có bảo hiểm",
    "Ví dụ bệnh viện tự đưa ra: phẫu thuật ước tính 10 triệu, bảo hiểm chỉ xác nhận bảo lãnh 8 triệu, phần chênh 2 triệu do người bệnh đặt cọc. Nếu thư bảo lãnh về sau, tiền cọc được hoàn."),
 ],

 "faq": [
   ("Sinh con ở Bệnh viện Quốc tế City hết bao nhiêu tiền?",
    "Theo giá công bố trên cih.com.vn (cập nhật 27/02/2026): gói sinh thường Như Ý 25.100.000đ, Cát Tường 31.700.000đ. Sinh mổ đơn thai lần đầu 36.180.000đ (Như Ý) và 42.530.000đ (Cát Tường). Các mức này <b>chưa bao gồm tiền phòng</b>."),
   ("Vì sao gói sinh ở Quốc tế City nhìn rẻ hơn các bệnh viện tư khác?",
    "Vì đây là giá chưa gồm tiền phòng, trong khi FV hay Hạnh Phúc bán gói đã gồm phòng và ghi rõ số đêm. Phòng ở Quốc tế City là 1,65 triệu (2 giường) đến 3,3 triệu (chăm sóc đặc biệt) mỗi ngày, tính riêng."),
   ("Tiền phòng ở Bệnh viện Quốc tế City bao nhiêu một ngày?",
    "Theo bảng giá dịch vụ sửa đổi lần cuối 24/06/2026: phòng 2 giường 1.650.000đ, phòng 1 giường 2.750.000đ, phòng chăm sóc đặc biệt 3.300.000đ, tính theo mỗi ngày."),
   ("Gói sinh Yêu Thương 17 triệu có phải là rẻ nhất không?",
    "Đúng là mức thấp nhất trên bảng giá, nhưng bệnh viện ghi rõ gói này chưa bao gồm phí bác sĩ, thuốc và vật tư y tế. So sánh trực tiếp với gói Như Ý là so sai, vì hai gói không cùng phạm vi."),
   ("Sinh mổ lần 2 ở Quốc tế City giá bao nhiêu?",
    "Gói sinh Như Ý cho ca có vết mổ cũ lần 2, 3 là 46.360.000đ; gói Cát Tường 55.810.000đ. Nếu mua gói thai sản trọn gói từ tuần 7 thì 67.760.000đ (Như Ý) và 76.260.000đ (Cát Tường)."),
   ("Đăng ký gói thai sản từ tuần nào thì lợi nhất?",
    "Về giá gói thì đăng ký muộn rẻ hơn: tuần 36&ndash;40 là 32,4 triệu so với tuần 7&ndash;40 là 48,2 triệu (gói Như Ý, sinh thường). Nhưng gói đăng ký sớm đã bao chặng khám thai dài. Muốn so đúng, phải cộng chi phí khám thai tự trả bên ngoài vào phương án đăng ký muộn."),
   ("Bệnh viện Quốc tế City có nhận bảo hiểm y tế không?",
    "Có. Ngoại trú chỉ áp dụng đúng tuyến; nội trú nhận cả đúng tuyến lẫn trái tuyến. Mức hưởng đúng tuyến 100/95/80% trên khung giá BHYT, trái tuyến 60/57/48%. Riêng các gói khám thai thì BHYT không chi trả, bệnh viện loại trừ rõ."),
   ("Đẻ không đau ở Quốc tế City giá bao nhiêu?",
    "Bệnh viện không công bố. Khoản này không có trên bảng giá dịch vụ lẫn trên các trang gói. Phải gọi hỏi trực tiếp: 1900 8146 hoặc khoa Phụ Sản (028) 6280 3333 ext. 8172."),
 ],
},

# =====================================================================
{
 "slug": "hanh-phuc",
 "ngay_dang": "2026-09-01",
 "ten": "Bệnh viện Quốc tế Hạnh Phúc",
 "tinh": "TP. Hồ Chí Minh (địa bàn Bình Dương cũ)",
 "loai": "Bệnh viện quốc tế",
 "calc_key": "hanhphuc",
 "nguon_ngay": "12/08/2025",
 "nguon_nhan": "Bảng giá gói sinh trên trang chính thức có lần cập nhật <b>12/08/2025</b>; các trang chi tiết từng gói sửa đổi 31/12/2025; gói khám thai cập nhật <b>05&ndash;07/01/2026</b>. Bệnh viện chưa công bố bảng giá đề năm 2026 cho gói sinh.",
 "nguon_url": "https://www.hanhphuchospital.com/goi-kham/goi-sinh/",
 "title": "Chi phí sinh con ở Bệnh viện Quốc tế Hạnh Phúc: giá gói, giá phòng và hạn mức thuốc trong gói",
 "desc": "Gói sinh Hạnh Phúc từ 29,9 triệu, phòng 2,8 đến 6,8 triệu mỗi đêm. Bài này có cả chi tiết ít nơi nhắc: hạn mức thuốc và vật tư trong gói chỉ 3 triệu với sinh thường, 7,5 triệu với sinh mổ.",
 "tom_tat": "Gói sinh thấp nhất ở Hạnh Phúc là <b>29.900.000đ</b> (An Nhiên, sinh thường, 3 ngày, phòng đơn), sinh mổ từ <b>39.900.000đ</b>, 4 ngày. Tờ thông tin của bệnh viện còn một con số ít được nhắc tới: gói chỉ bao thuốc, dịch truyền và vật tư trong 3 triệu với sinh thường và 7,5 triệu với sinh mổ. Phần vượt hạn mức do gia đình tự trả.",

 "bang": [
   {"ten": "Giá ba gói sinh",
    "kiem_chung": "chinh-thuc",
    "nguon": "hanhphuchospital.com, trang gói sinh, cập nhật 12/08/2025",
    "cot": ["Gói", "Sinh thường (3 ngày)", "Sinh mổ lần đầu (4 ngày)"],
    "hang": [
      ["Hạnh Phúc <b>An Nhiên</b>", "29.900.000đ", "39.900.000đ"],
      ["Hạnh Phúc <b>Cát Tường</b>", "39.900.000đ", "49.900.000đ"],
      ["Hạnh Phúc <b>Như Ý</b>", "59.900.000đ", "69.900.000đ"],
    ]},
   {"ten": "Hạn mức thuốc, dịch truyền và vật tư nằm trong gói",
    "kiem_chung": "chinh-thuc",
    "nguon": "Tờ thông tin gói sinh chính thức của bệnh viện (leaflet PDF trên goisinh.hanhphuchospital.com) (file không ghi ngày hiệu lực, truy cập ngày 01/09/2026)",
    "cot": ["Loại sinh", "Hạn mức trong gói", "Vượt hạn mức"],
    "hang": [
      ["Sinh thường", "3.000.000đ", "Tự trả phần vượt"],
      ["Sinh mổ", "7.500.000đ", "Tự trả phần vượt"],
    ]},
   {"ten": "Giá phòng và phụ phí nâng hạng",
    "kiem_chung": "chinh-thuc",
    "nguon": "Tờ thông tin gói sinh chính thức của bệnh viện (file không ghi ngày hiệu lực, truy cập ngày 01/09/2026)",
    "cot": ["Hạng phòng", "Giá mỗi đêm", "Phụ phí nâng từ hạng Tiêu Chuẩn"],
    "hang": [
      ["Tiêu Chuẩn", "2.800.000đ", "&mdash;"],
      ["Cao Cấp", "3.800.000đ", "+1.000.000đ / đêm"],
      ["VIP", "4.800.000đ", "+2.000.000đ / đêm"],
      ["VIP Suite", "6.800.000đ", "+4.000.000đ / đêm"],
    ]},
   {"ten": "Các khoản tính thêm ngoài gói",
    "kiem_chung": "chinh-thuc",
    "nguon": "Tờ thông tin gói sinh chính thức của bệnh viện (file không ghi ngày hiệu lực, truy cập ngày 01/09/2026)",
    "cot": ["Dịch vụ", "Giá niêm yết", "Giá ưu đãi"],
    "hang": [
      ["Gây tê ngoài màng cứng (giảm đau chuyển dạ)", "1.200.000đ", "960.000đ"],
      ["Chiếu đèn vàng da 24 giờ", "1.200.000đ", "960.000đ"],
      ["Quay phim &ldquo;Hành Trình Hạnh Phúc&rdquo;", "5.000.000đ", "4.000.000đ"],
      ["Nằm viện vượt số ngày trong gói", "tính 25% &ndash; 75% giá phòng mỗi đêm, theo khung giờ ra viện", "&mdash;"],
    ]},
   {"ten": "Gói khám thai theo tuần đăng ký",
    "kiem_chung": "chinh-thuc",
    "nguon": "goikhamthai.hanhphuchospital.com, cập nhật 05&ndash;07/01/2026",
    "cot": ["Gói", "Tuần thai bắt đầu", "Giá"],
    "hang": [
      ["Tâm An", "tuần 10 &ndash; 40", "26.000.000đ"],
      ["Mãn Nguyện", "tuần 16 &ndash; 40", "18.500.000đ"],
      ["Nở Nhụy", "tuần 24 &ndash; 40", "15.800.000đ"],
      ["Khai Hoa", "tuần 36 &ndash; 40", "9.900.000đ"],
    ]},
 ],

 "khong_bao_gom": [
   "Phần thuốc, dịch truyền và vật tư vượt hạn mức 3 triệu (sinh thường) hoặc 7,5 triệu (sinh mổ). Đây là dòng ít được chép lại, và là chỗ ngân sách hay vỡ.",
   "Gây tê ngoài màng cứng với gói An Nhiên và Cát Tường, tính thêm 1.200.000đ (ưu đãi 960.000đ). Riêng gói Như Ý có ghi &ldquo;sinh thường có giảm đau&rdquo;.",
   "Dịch vụ, thuốc và vật tư phát sinh theo tình huống đặc biệt do bác sĩ chỉ định vì lý do y tế, nguyên văn câu loại trừ của bệnh viện.",
   "Đêm nằm viện vượt số ngày trong gói, tính 25% đến 75% giá phòng mỗi đêm tuỳ khung giờ ra viện.",
 ],

 "khong_cong_bo": [
   "<b>Giá sinh mổ lần 2 trở lên.</b> Tờ thông tin chỉ ghi cột &ldquo;sinh mổ lần đầu&rdquo;. Ca có vết mổ cũ không nằm trong bảng giá nào được công bố.",
   "Mức tạm ứng khi nhập viện. Trang quy trình nhập viện nói mọi thông tin viện phí &ldquo;sẽ được tư vấn tại bộ phận Dịch vụ khách hàng&rdquo;.",
   "Giá dịch vụ lẻ ngoài gói cho sinh thường và sinh mổ. Bệnh viện không có bảng giá viện phí công khai.",
   "Chi phí NICU, sinh non, song thai, biến chứng. Chỉ có câu loại trừ chung, không có con số. Khoa NICU của bệnh viện công bố đã điều trị hơn 7.000 ca sơ sinh và cứu hơn 2.600 trẻ sinh non từ 24 đến 37 tuần: năng lực thì công bố, giá thì không.",
   "Tuần thai giới hạn để đăng ký gói sinh. Gói khám thai có mốc tuần rõ ràng, gói sinh thì không.",
   "Chính sách khi chuyển từ sinh thường sang sinh mổ giữa chừng.",
   "Danh sách đầy đủ công ty bảo hiểm bảo lãnh trực tiếp. Website chỉ có hai bản tin lẻ công bố thêm đối tác, không có trang tổng hợp.",
 ],

 "luu_y": [
   ("Hạn mức thuốc và vật tư trong gói",
    "Gói sinh mổ 39,9 triệu nghe như đã bao trọn. Nhưng tờ thông tin của bệnh viện ghi hạn mức thuốc, dịch truyền và vật tư trong gói chỉ 7,5 triệu, và 3 triệu với sinh thường. Một ca sinh diễn biến khó, dùng nhiều thuốc, sẽ vượt hạn mức đó, phần vượt do gia đình tự trả. Đây là điều khoản nên hỏi trước khi đặt cọc."),
   ("Bệnh viện bắt đầu nhận BHYT từ tháng 1/2026",
    "Trước đó bệnh viện không áp dụng BHYT. Từ tháng 1/2026 bệnh viện triển khai khám, điều trị và thanh toán BHYT, chi trả theo mức ghi trên thẻ (80%, 95% hoặc 100%), được xếp tuyến cơ bản. Chưa nguồn chính thức nào nói rõ BHYT có áp dụng cho gói sinh hay không, nên cần gọi 1900 6765 hỏi trực tiếp."),
   ("Địa chỉ bệnh viện hiện thuộc TP.HCM",
    "Sau sáp nhập địa giới hành chính, trang liên hệ chính thức của bệnh viện ghi địa chỉ 18 Đại lộ Bình Dương, Phường Bình Hoà, TP.HCM. Bệnh viện cũng có phòng khám vệ tinh tại Estella Place, 88 Song Hành, Phường Bình Trưng, TP.HCM."),
   ("Đặt cọc gói sinh trước được giảm 20% các dịch vụ khác",
    "Ưu đãi này ghi trên cả tờ thông tin lẫn trang gói. Đó cũng là lý do bảng giá có hai cột: giá niêm yết và giá ưu đãi. Ví dụ gây tê ngoài màng cứng từ 1,2 triệu xuống 960 nghìn."),
   ("Cẩn thận với bảng giá 35&ndash;83 triệu đang lưu hành trên mạng",
    "Một trang tổng hợp lớn ghi gói sinh Hạnh Phúc là 35 đến 83 triệu, có cả hạng &ldquo;phòng VIP Elite&rdquo;. Dải đó không khớp với giá chính thức 29,9 đến 69,9 triệu, nhiều khả năng là bảng giá cũ, nên không được dùng ở đây."),
   ("Trùng tên gói với Bệnh viện Quốc tế City",
    "Hạnh Phúc có gói Cát Tường và Như Ý; Bệnh viện Quốc tế City cũng có hai gói tên y hệt. Đây là hai bệnh viện khác nhau, giá khác hẳn: gói Như Ý sinh thường ở Hạnh Phúc là 59,9 triệu, ở Quốc tế City là 25,1 triệu &mdash; và chưa gồm tiền phòng. Khi tìm theo tên gói, cần kiểm tra bài viết đang nói về bệnh viện nào."),
   ("Chưa có bảng giá 2026 cho gói sinh",
    "Số mới nhất đọc được là bản cập nhật 12/08/2025, trang chi tiết gói sửa 31/12/2025. Bài nào ghi &ldquo;bảng giá sinh con Hạnh Phúc 2026&rdquo; đều đang gán một cái nhãn mà bệnh viện chưa phát hành."),
 ],

 "faq": [
   ("Sinh con ở Bệnh viện Quốc tế Hạnh Phúc hết bao nhiêu tiền?",
    "Theo bảng giá bệnh viện công bố (cập nhật 12/08/2025): gói An Nhiên sinh thường 29.900.000đ và sinh mổ 39.900.000đ; gói Cát Tường 39.900.000đ và 49.900.000đ; gói Như Ý 59.900.000đ và 69.900.000đ. Sinh thường nằm 3 ngày, sinh mổ 4 ngày."),
   ("Gói sinh Hạnh Phúc đã bao gồm tiền phòng chưa?",
    "Có. Tờ thông tin ghi gói đi kèm phòng đơn, và bảng phụ phí nâng hạng của bệnh viện tính mốc từ hạng Tiêu Chuẩn. Muốn nâng hạng thì trả thêm mỗi đêm: lên Cao Cấp +1 triệu, lên VIP +2 triệu, lên VIP Suite +4 triệu. Bệnh viện không ghi rõ &ldquo;phòng đơn&rdquo; tương ứng chính xác hạng nào trong bảng giá phòng, nên cần hỏi thẳng hạng phòng khi đặt cọc."),
   ("Gói sinh có bao hết tiền thuốc không?",
    "Không. Bệnh viện ghi hạn mức thuốc, dịch truyền và vật tư trong gói là <b>3.000.000đ</b> với sinh thường và <b>7.500.000đ</b> với sinh mổ. Vượt hạn mức thì gia đình tự trả phần vượt."),
   ("Đẻ không đau ở Hạnh Phúc bao nhiêu tiền?",
    "Gây tê ngoài màng cứng niêm yết 1.200.000đ, giá ưu đãi 960.000đ khi đã đặt cọc gói sinh. Khoản này tính thêm với gói An Nhiên và Cát Tường; riêng gói Như Ý có ghi sinh thường có giảm đau."),
   ("Sinh mổ lần 2 ở Hạnh Phúc giá bao nhiêu?",
    "Bệnh viện không công bố. Bảng giá chỉ có cột &ldquo;sinh mổ lần đầu&rdquo;. Trường hợp đã có vết mổ cũ phải gọi 1900 6765 hỏi mức riêng, tốt nhất là trước khi đóng cọc."),
   ("Bệnh viện Hạnh Phúc có nhận bảo hiểm y tế không?",
    "Từ tháng 1/2026 bệnh viện chính thức triển khai khám, điều trị và thanh toán BHYT, chi trả theo mức ghi trên thẻ 80%, 95% hoặc 100%, xếp tuyến cơ bản. Nhưng chưa có công bố nào nói rõ điều này áp dụng thế nào với gói sinh, cần hỏi trực tiếp."),
   ("Nằm viện quá số ngày trong gói thì tính tiền sao?",
    "Bệnh viện tính 25% đến 75% giá phòng mỗi đêm, tuỳ khung giờ ra viện (1&ndash;6h, 6&ndash;12h, 12&ndash;18h, 18&ndash;24h). Với phòng Tiêu Chuẩn 2,8 triệu một đêm thì phần vượt là 700 nghìn đến 2,1 triệu."),
   ("Gói khám thai Hạnh Phúc giá bao nhiêu?",
    "Bốn gói theo tuần đăng ký: Tâm An (tuần 10&ndash;40) 26.000.000đ, Mãn Nguyện (tuần 16&ndash;40) 18.500.000đ, Nở Nhụy (tuần 24&ndash;40) 15.800.000đ, Khai Hoa (tuần 36&ndash;40) 9.900.000đ. Chỉ áp dụng đơn thai, gói kích hoạt trong 365 ngày kể từ ngày mua."),
 ],
},

# =====================================================================
{
 "slug": "hoan-my-sai-gon",
 "ngay_dang": "2026-09-01",
 "ten": "Bệnh viện Hoàn Mỹ Sài Gòn",
 "tinh": "TP. Hồ Chí Minh",
 "loai": "Bệnh viện tư",
 "nguon_ngay": "11/12/2025",
 "nguon_nhan": "Trang gói sinh &ldquo;Hạnh phúc Hoàn Mỹ&rdquo; của Hoàn Mỹ Sài Gòn cập nhật <b>11/12/2025</b>; thông báo bảo lãnh viện phí quốc tế đăng <b>02/03/2026</b>. Cả hai trang đều không có mức giá nào.",
 "nguon_url": "https://hoanmy.com/saigon/thai-san/homepage/",
 "canh_bao": "Trang này không có bảng giá, vì Bệnh viện Hoàn Mỹ Sài Gòn không công bố giá gói sinh trên website. Bảng giá duy nhất có cấu trúc đầy đủ tìm được trên internet là bản đăng năm <b>2018</b>, đã tám năm, không dẫn nguồn, không ghi ngày áp dụng. Con số đó không được đăng lại ở đây. Phần đăng trong bài là những gì bệnh viện có công bố chính thức, trong đó có danh sách nguyên văn các khoản gói không bao gồm.",
 "title": "Chi phí sinh con ở Bệnh viện Hoàn Mỹ Sài Gòn: bệnh viện không công bố giá, nhưng công bố danh sách loại trừ",
 "desc": "Hoàn Mỹ Sài Gòn không đăng giá gói sinh. Nhưng bệnh viện công bố nguyên văn gói bao gồm gì và loại trừ gì, trong đó có NICU, sinh không đau, song thai và biến chứng sau mổ. Đây là danh sách cần đọc trước khi lập ngân sách.",
 "tom_tat": "Bệnh viện Hoàn Mỹ Sài Gòn <b>không công bố giá</b> gói sinh, chỉ công bố mức ưu đãi <b>giảm 10%</b> khi đăng ký online kèm đặt cọc trước. Bù lại, bệnh viện liệt kê nguyên văn những khoản gói không bao gồm: chăm sóc đặc biệt cho trẻ sơ sinh, sinh không đau, song thai và điều trị biến chứng sau phẫu thuật. Với người đang lập ngân sách, danh sách loại trừ này có giá trị hơn một con số tổng.",

 "bang": [
   {"ten": "Gói Hạnh phúc Hoàn Mỹ bao gồm những gì",
    "kiem_chung": "chinh-thuc",
    "nguon": "hoanmy.com, trang gói thai sản Hoàn Mỹ Sài Gòn, cập nhật 11/12/2025",
    "cot": ["Nhóm", "Nội dung bệnh viện công bố"],
    "hang": [
      ["Nằm viện", "Phí nằm viện, điều dưỡng chăm sóc 24/24, bác sĩ Sản và Nhi thăm khám"],
      ["Ca sinh", "Chi phí phòng sinh hoặc phòng mổ &mdash; áp dụng cho cả sinh thường và sinh mổ"],
      ["Cận lâm sàng", "Siêu âm, điện tim (ECG), theo dõi tim thai (CTG)"],
      ["Sàng lọc sơ sinh", "G6PD, TSH, Free T4, Bilirubin, thính lực, tim bẩm sinh"],
      ["Sơ sinh", "Tiêm chủng sơ sinh, tắm và vệ sinh bé"],
      ["Vận chuyển", "Xe cấp cứu đón sản phụ <b>miễn phí trong bán kính dưới 5 km</b>"],
    ]},
   {"ten": "Gói không bao gồm, trích nguyên văn từ bệnh viện",
    "kiem_chung": "chinh-thuc",
    "nguon": "hoanmy.com, trang gói thai sản Hoàn Mỹ Sài Gòn, cập nhật 11/12/2025",
    "cot": ["Khoản loại trừ", "Vì sao nó quan trọng với ngân sách"],
    "hang": [
      ["Chi phí <b>chăm sóc đặc biệt cho trẻ sơ sinh</b> (NICU)", "Khoản đắt nhất và khó đoán nhất trong mọi ca sinh"],
      ["<b>Dịch vụ sinh không đau</b>", "Gây tê ngoài màng cứng tính thêm, không nằm trong gói"],
      ["<b>Sinh song thai</b>", "Song thai không dùng giá gói tiêu chuẩn"],
      ["Điều trị <b>biến chứng sau phẫu thuật</b>", "Đúng phần mà bảo hiểm thai sản có quyền lợi biến chứng sẽ đỡ cho bạn"],
      ["Chi phí phát sinh do <b>can thiệp các chuyên khoa khác</b>", "Ca sinh có bệnh lý đi kèm sẽ vượt gói"],
      ["<b>Phí hội chẩn chuyên khoa</b> nếu có bệnh lý đi kèm", "Tính riêng"],
      ["Huyết thanh kháng viêm gan B cho trẻ, truyền máu", "Hai khoản nhỏ nhưng hay bị bỏ sót"],
    ]},
   {"ten": "Bảo lãnh viện phí trực tiếp tại Hoàn Mỹ Sài Gòn",
    "kiem_chung": "chinh-thuc",
    "nguon": "hoanmy.com, thông báo bảo lãnh viện phí quốc tế, đăng 02/03/2026",
    "cot": ["Nội dung", "Chi tiết"],
    "hang": [
      ["Đối tác bảo lãnh quốc tế", "Pacific Cross Vietnam, Trails of Indochina, April Vietnam, Assist 24/7, SafetyNet Insurance Services (Vietnam), Tokio Marine Vietnam"],
      ["Đối tác nêu trên trang giới thiệu bệnh viện", "Bảo Việt, Insmart, PVI, Bảo Minh"],
      ["Phạm vi áp dụng", "Ngoại trú, nội trú, cấp cứu, nha khoa, khu điều trị quốc tế"],
      ["Thời gian xử lý ngoại trú", "khoảng 30 phút"],
      ["Cần mang theo", "Thẻ bảo hiểm còn hiệu lực và giấy tờ tuỳ thân"],
    ]},
   {"ten": "Ưu đãi và điều kiện đăng ký",
    "kiem_chung": "chinh-thuc",
    "nguon": "hoanmy.com, trang gói thai sản Hoàn Mỹ Sài Gòn, cập nhật 11/12/2025",
    "cot": ["Nội dung", "Bệnh viện công bố"],
    "hang": [
      ["Mức ưu đãi", "Giảm <b>10%</b> khi đăng ký online kèm đặt cọc trước"],
      ["Tuần thai được đăng ký", "Bất kỳ tuần thai nào"],
      ["Giá gói", "<b>Không công bố</b> &mdash; phải liên hệ bệnh viện"],
    ]},
 ],

 "khong_cong_bo": [
   "Toàn bộ giá gói sinh: sinh thường, sinh mổ lần 1, sinh mổ lần 2 trở lên, mọi hạng phòng. Không có con số nào trên website.",
   "Tiền phòng theo hạng, mỗi ngày. Không có file bảng giá viện phí công khai của riêng cơ sở Sài Gòn. Hệ thống Hoàn Mỹ có đăng bảng giá PDF cho một số cơ sở khác như Bình Dương, Bình Phước, nhưng đó là bệnh viện khác, số của họ không dùng cho Sài Gòn được.",
   "Số ngày nằm viện tiêu chuẩn của gói.",
   "Mức tạm ứng khi nhập viện. Không tìm thấy ở bất kỳ nguồn nào.",
   "Giá gây tê ngoài màng cứng. Chỉ biết chắc là khoản này không nằm trong gói.",
   "Giá NICU và chăm sóc đặc biệt sơ sinh. Bệnh viện xác nhận nằm ngoài gói, nhưng không cho biết ngoài gói thì bao nhiêu.",
   "Mức hưởng BHYT cho ca sinh tại cơ sở này. Chưa có trang chính thức nào của riêng Hoàn Mỹ Sài Gòn khẳng định, và số của cơ sở Hoàn Mỹ khác thì không suy ra được.",
   "Bảng giá năm <b>2018</b> cũng không được đăng lại ở đây. Bản duy nhất có cấu trúc đầy đủ trên internet ghi sinh thường 13&ndash;25 triệu và sinh mổ 17&ndash;40 triệu tuỳ hạng phòng. Bài đó không dẫn nguồn, không ghi ngày áp dụng, và đã tám năm.",
 ],

 "luu_y": [
   ("Vì sao trang này không có bảng giá",
    "Theo rà soát trang gói sinh chính thức, trang giới thiệu bệnh viện và các file PDF bảng giá, không có con số nào cho ca sinh. Thay vì điền một dải giá ước chừng, bài đăng đúng thứ bệnh viện có công bố là danh sách loại trừ. Với người sắp sinh, biết <i>khoản nào không được bao</i> cũng quan trọng như biết một con số tổng."),
   ("Danh sách loại trừ trùng với quyền lợi bảo hiểm thai sản",
    "Bốn khoản bệnh viện nêu là chăm sóc đặc biệt sơ sinh, sinh không đau, song thai và biến chứng sau phẫu thuật. Đó cũng là những khoản mà một hợp đồng bảo hiểm có quyền lợi thai sản và quyền lợi biến chứng sẽ gánh. Bệnh viện đã chỉ ra chỗ ngân sách gia đình dễ hở nhất."),
   ("Ưu đãi 10% áp dụng ở bất kỳ tuần thai nào",
    "Nhiều bệnh viện bán gói theo tuần đăng ký, đăng ký càng sớm càng đắt vì bao cả chặng khám thai. Hoàn Mỹ Sài Gòn công bố một mức ưu đãi duy nhất 10%, không phụ thuộc tuần thai, điều kiện là đăng ký online và đặt cọc trước."),
   ("Đừng lấy nhầm số của cơ sở Hoàn Mỹ khác",
    "Hệ thống Hoàn Mỹ có nhiều bệnh viện. Gói thai sản có ưu đãi 8% và 5%, nằm viện 3 ngày với sinh thường và 6 ngày với sinh mổ, thường xuất hiện khi tìm kiếm, là gói của <b>Hoàn Mỹ Vinh</b>, không phải Sài Gòn. Các bảng giá PDF trên hoanmy.com cũng là của Bình Dương và Bình Phước."),
   ("Bảo lãnh viện phí có, nhưng danh sách hẹp hơn các bệnh viện quốc tế",
    "Sáu đối tác bảo lãnh quốc tế được công bố tháng 3/2026, cộng thêm Bảo Việt, Insmart, PVI, Bảo Minh nêu ở trang giới thiệu. So với 102 đơn vị của FV thì danh sách này hẹp hơn nhiều. Người có thẻ sức khoẻ nên kiểm tra trước khi chọn bệnh viện."),
   ("Hai câu cần hỏi khi gọi bệnh viện",
    "Một: gói sinh thường và sinh mổ hiện bao nhiêu, đi kèm hạng phòng nào và mấy ngày. Hai: nếu bé phải nằm chăm sóc đặc biệt thì tính tiền theo ngày là bao nhiêu. Câu thứ hai mới là câu quyết định ngân sách. Số máy 028 3990 2468, tư vấn thai sản 098 8521 242."),
 ],

 "faq": [
   ("Sinh con ở Bệnh viện Hoàn Mỹ Sài Gòn hết bao nhiêu tiền?",
    "Bệnh viện không công bố giá gói sinh trên website nên không có câu trả lời chắc chắn. Con số chính thức duy nhất là mức ưu đãi giảm 10% khi đăng ký online kèm đặt cọc trước. Muốn biết giá phải gọi 028 3990 2468 hoặc 098 8521 242."),
   ("Vì sao trang này không có bảng giá Hoàn Mỹ Sài Gòn như các trang khác?",
    "Vì bảng giá duy nhất có cấu trúc đầy đủ trên internet là bài đăng từ năm 2018 và đã tám năm, không dẫn nguồn, không ghi ngày áp dụng. Con số đó không được đăng lại dưới nhãn giá hiện nay."),
   ("Gói sinh Hoàn Mỹ Sài Gòn bao gồm những gì?",
    "Theo công bố ngày 11/12/2025: phí nằm viện, điều dưỡng 24/24, bác sĩ Sản và Nhi thăm khám, chi phí phòng sinh hoặc phòng mổ, siêu âm, ECG, CTG, sàng lọc sơ sinh (G6PD, TSH, Free T4, Bilirubin, thính lực, tim bẩm sinh), tiêm chủng sơ sinh, tắm vệ sinh bé, và xe cấp cứu đón sản phụ miễn phí trong bán kính dưới 5 km."),
   ("Gói sinh Hoàn Mỹ Sài Gòn không bao gồm những gì?",
    "Bệnh viện liệt kê rõ: chăm sóc đặc biệt cho trẻ sơ sinh, dịch vụ sinh không đau, sinh song thai, điều trị biến chứng sau phẫu thuật, chi phí phát sinh do can thiệp các chuyên khoa khác, phí hội chẩn chuyên khoa nếu có bệnh lý đi kèm, huyết thanh kháng viêm gan B cho trẻ và truyền máu."),
   ("Đẻ không đau ở Hoàn Mỹ Sài Gòn có nằm trong gói không?",
    "Không. Bệnh viện ghi rõ &ldquo;dịch vụ sinh không đau&rdquo; nằm trong danh sách gói không bao gồm. Giá của dịch vụ này thì bệnh viện không công bố."),
   ("Sinh đôi ở Hoàn Mỹ Sài Gòn có dùng giá gói không?",
    "Không. &ldquo;Sinh song thai&rdquo; nằm trong danh sách loại trừ của gói. Mức giá cho trường hợp này phải hỏi riêng."),
   ("Bệnh viện Hoàn Mỹ Sài Gòn có bảo lãnh viện phí không?",
    "Có. Theo thông báo ngày 02/03/2026: Pacific Cross Vietnam, Trails of Indochina, April Vietnam, Assist 24/7, SafetyNet Insurance Services (Vietnam), Tokio Marine Vietnam. Trang giới thiệu bệnh viện nêu thêm Bảo Việt, Insmart, PVI, Bảo Minh. Áp dụng cho ngoại trú, nội trú, cấp cứu, nha khoa và khu điều trị quốc tế; xử lý ngoại trú khoảng 30 phút."),
   ("Đăng ký gói sinh Hoàn Mỹ Sài Gòn từ tuần thứ mấy?",
    "Bệnh viện công bố đăng ký được ở bất kỳ tuần thai nào, và mức ưu đãi 10% không phụ thuộc tuần đăng ký, chỉ cần đăng ký online kèm đặt cọc trước."),
 ],
},


]
